### ISSUE TITLE
Fedora support

### ISSUE THREAD

**Issue by lauren-elise-thomas** [psieg/Lightpack#104]
Is supporting fedora planned? It would be nice to use my Lightpack on a modern distro.

**Comment by psieg** [comment]
Spontaneous googling says Fedora uses Wayland, which is #90. Any help is welcome.

**Comment by lauren-elise-thomas** [comment]
Fedora can use xorg if the user selects it when logging in. Wayland is default, but optional.

**Comment by psieg** [comment]
In that case Prismatik should work just as it does under Ubuntu.
In that case I assume you are asking for a package, which would be #30?

**Comment by lauren-elise-thomas** [comment]
That would be nice. Are there plans to port Lightpack to Wayland?

**Comment by psieg** [comment]
The issue is #90. I am not currently working on it, but anyone is welcome to help
