### ISSUE TITLE
Firmware built from source doesn't work with RPI3

### ISSUE THREAD

**Issue by Dolnor** [psieg/Lightpack#106]
Excellent work with all the additional amendments. I had a bright idea to switch to this fork, but building the firmware from source, I've discovered it seems to not work with Raspberry Pi3/Hyperion. Someone else has reported this flashing a modified fw, but appears to be resolved without much detail - https://github.com/hyperion-project/hyperion/issues/225

But I'm not introducing any changes and merely compiling the current source. Just to be sure it's not the fork itself, I've tried the official woodenshark repo and built 7.6 FW from that, which leads to the same problem. I've even got as far as downloading the Source.tar.gz from Releases on the main Lightpack repo and compiled the sources to no avail. The only firmware that allows the daemon to communicate with the device without error is the one from lightpack.tv or from the Release section on the Lightpack repo - https://github.com/woodenshark/Lightpack/releases/tag/FW_version_6

Had official 7.5 before I've started tinkering with the Lightpack unit. In all other attempts to flash self-compiled FW I end up with _unable to claim interface(-5): LIBUSB_ERROR_NOT_FOUND_. Another thing is, like the guys there is saying, with self-compiled FW the unit will do blue LED flashes as 3x short and 2x long indefinitely if you have plugged it after booting the Pi.

One observation is that building under Ubuntu 16.04 LTS, I see the self-compiled firmware ends up as 17.3 Kb whereas the official unmodified 7.6 is 16.8 Kb. 

Any help is appreciated.

**Comment by psieg** [comment]
Well, from the issue you linked:

> I'm a little behind but the USB HID reporting bug I reported to the lightpack github
https://github.com/Atarity/Lightpack/issues/71
>
> The only change is returning false on the HID report, which means don't force a transfer every period, only every timeout.

While the issue link is dead, you can try changing `CALLBACK_HID_Device_CreateHIDReport` in `LightpackUSB.c line 89-103` to return false and see if that works. I don't run Hyperion so I can't try.
Let me know how it works out

**Comment by psieg** [comment]
@Dolnor any news on this?

**Comment by Dolnor** [comment]
Hi, I'm currently on holidays so coudlt really check. Will give it a go once back to the usual routines and general tinkering. Thanks!

**Comment by psieg** [comment]
@Dolnor ping

**Comment by psieg** [comment]
I'll consider this dead, sorry
