### ISSUE TITLE
How to uninstall Prismatik manually completely?

### ISSUE THREAD

**Issue by twistedminddnb** [psieg/Lightpack#108]
Hi,

I want to uninstall Prismatik manually as adviced. Maybe my problems are due to version interference.

I have deinstalled the previous version with windows deinstallation.

Most games work with  Ambibix. But it seems only boarderless window.

As I understood prismatik can do full screen games. I would really like to get it running.

I have Ws2801 strip BGR

With normal LEDstream on Arduino found in every tutorial it does not work. In  Prismatik and Ambibox. The leds flicker in scren capture.

With a altered Fast LED WS2812B sketch it works flawless in Ambibox with Windows 8 screen capture in most games. However it does not in Prismatik.

I want to chek if I made a mistake during deinstallation of prismatik to narrow down the problem.

Thank you.

**Comment by psieg** [comment]
Prismatik installs all its files to `C:\Program Files\Prismatik`, the old version installls to `Program Files (x86)`. Configuration files and log files are placed at `C:\Users\Yourname\Prismatik`.
There is a shortcut installed in the start menu and (if you selected the option) the startup folder.

**Comment by twistedminddnb** [comment]
that worked.

thank you so much

**Comment by psieg** [comment]
you're welcome
