### ISSUE TITLE
Too sensitive in games. COlors change too quick and sensitive.

### ISSUE THREAD

**Issue by twistedminddnb** [psieg/Lightpack#110]
Hi,

one last issue i have is that in prismatik is realy responsponsive. If I run next to walls in games the sides flicker and adapt to every little thing. Also clouds and heaven are a bit too fast and much.

This is cool for a movie i think but in games it is too much. 

Ambibox has a setting called smoothing or something. This makes it just creating the atmosphere but not adapt to every little thing.

Is there also a settuing for that in Prismatik?

Thanks

**Comment by psieg** [comment]
Please explore the UI and try some things before asking everything. There is a grab delay slider and a smoothness setting, which should help
