### ISSUE TITLE
Stopped working with creators update

### ISSUE THREAD

**Issue by DayGlow** [psieg/Lightpack#111]
Screen grabbing no longer works. I can setup the mood lighting, but screen grabbing no longer works once the Windows 10 creators update is applied.

**Comment by psieg** [comment]
It works perfectly fine for me. Please be more specific
- Are there errors in the logs?
- What does the FPS counter say?
- Does WinAPI grabbing work?
- What have you tried?
- Which device are you using? Does it work with the virtual device?

**Comment by DayGlow** [comment]
A reinstall of the utility fixed the issue.

**Comment by psieg** [comment]
Okay, thanks. Did this happen to anyone else?
