### ISSUE TITLE
Sound Visualization API feature for setting Visualization colors

### ISSUE THREAD

**Issue by alexg636** [psieg/Lightpack#112]
Allowing the user to set the colors of visualization through the API will allow for conditional on-the-fly switching.

For example, my script dissects the two most prevalent colors of a flag of the country of origin, for whichever artist is currently playing on Spotify; it would be incredible to have the LEDs change on the fly with Sound Visualization. Thanks for all the work you put into this version of Prismatik!

**Comment by psieg** [comment]
Implemented and released
