### ISSUE TITLE
Firmware 7 doesn't turn off blue LED

### ISSUE THREAD

**Issue by mattkhaw** [psieg/Lightpack#114]
I've tried the modified firmware 7 and it seems that the blue LED is still on after flashing my current unit. I'm actually running the latest official firmware before flashing. I've tried flashing firmware before on my unit and it seems to be fine. Is it missing a line of code to turn it on or off?

**Comment by mattkhaw** [comment]
Okay, I think I've found why it's not working. The setting have to be set in the profile, right? If yes, then I'll close this later once I've tried it.

**Comment by psieg** [comment]
Yes, the firmware enables a switch in the Software. There are alternative firmware versions out there that totally disable the LED, too
