### ISSUE TITLE
Faster Serial Baud Rates?

### ISSUE THREAD

**Issue by dmadison** [psieg/Lightpack#116]
Would it be possible to add faster baud rates than 115200 for 3rd party devices? I'm not sure if it's a matter of just appending the list or if there's more to it on the back end.

**Comment by psieg** [comment]
Honestly I have no idea. Since I don't have any such device I don't use know anything about that. Are there other common rates?

**Comment by dmadison** [comment]
[Here's a reference I found](http://digital.ni.com/public.nsf/allkb/D37754FFA24F7C3F86256706005B9BE7). Relevant quotes:

> Most serial devices accept only a predefined set of baud rates. The maximum rate for most standard serial ports is 115200. However, some serial devices...support any arbitrary baud rate below a specified maximum rate. 

So while 115200 seems to be the fastest rate for "standard" hardware, some hardware will support faster rates. If I recall correctly a typical Arduino can do up to 1M, assuming that the PC's port can support it.

Typical faster rates, also from that link:

> Standard baud rates supported by some serial ports:
> 
> - 128000
> - 153600
> - 230400
> - 256000
> - 460800
> - 921600

Continuing the doubling theme, I'd recommend 230400, 460800, and 921600 be added. Maybe an added checkbox or the like warning about unsupported hardware would be prudent.

I've tested rates of 230400, 460800, and 921600 successfully on a genuine Arduino Uno, just using it to relay messages. Notably none of the rates above 115200 worked on a _knockoff_ Uno, presumably because of the lower quality FTDI chip.

**Comment by psieg** [comment]
You should be able to set any baud rate in the config file, it appears the value is not vaildated when loaded. Have you tried that?

**Comment by dmadison** [comment]
Which config file is that? I didn't see any serial options listed in the profile files.

**Comment by psieg** [comment]
The baud rate is a device setting, which is saved in main.conf

**Comment by dmadison** [comment]
Thanks, I found the file and the settings. I don't know how I missed it!

I did some quick tests with the Arduino Nano I have driving my LEDs, and changing the serial speed in `main.conf` appears to work perfectly. Although in the future it  would be nice to be able to set baud rate through the configuration wizard.

Interestingly, the USB -> Serial chip on my knockoff Nano doesn't work with 230400, 460800, or 921600 baud, but _does_ work with 250000, 500000, and 1M baud (I haven't tested others). So it may be better to leave the current dropdown setting as-is, and maybe add a text field for a "Custom baud rate" instead.

**Comment by dmadison** [comment]
Related: because the white balance adjustment in the wizard ( #86, #95) is after the baud rate setting, the firmware on 3rd party devices would need to be flashed to a lower baud rate to utilize the global GUI white balance adjustment in the current release.

**Comment by psieg** [comment]
I don't understand. If the baud rate page is first, the rest of the wizard should use the configured baud rate. Why would one need to flash a different firmware?

**Comment by dmadison** [comment]
Sorry, reading it back now I see I was being a bit too vague.

It's only an issue if you're running a 3rd party device at a higher baud rate than 115200 by editing `main.conf`, which is the current workaround. Because the white balance portion of the wizard is after the baud rate setting, you cannot get to the white balance page because it will force you to a lower baud rate.

**Comment by psieg** [comment]
Does the device does not work with slower baud rates or is it just slower?

**Comment by dmadison** [comment]
It does not work. The baud rate is set on firmware upload, and the board won't communicate properly at other rates.

**Comment by Benik3** [comment]
For the BaudRates I recommend to look at this tables, where you can find speed vs Error. The Speed is on AVR set by dividers from clock so you can't choose any speed you want. http://wormfood.net/avrbaudcalc.php
Also if you want to use higher speeds then 115200 don't use Arduino Nano, mini etc. with Atmega328P and dedicated USB-serial converter.
Instead use Arduino micro (Leonardo) with Atmega32u4 which has USB in the CPU. Much faster, no problem here to use 1M Bd ;)

**Comment by Dallas-J** [comment]
I know this issue is a bit old at this point, but did anyone here ever get a baud rate above 115200 working? When I try setting the baud rate above 115200 in `main.conf`, I get random colors on all of my LEDs. I have tested the board (Arduino Uno) and it is fine all the way to a 2M baud rate, so I thought I'd make sure I wasn't doing anything wrong before investigating further.

**Comment by dmadison** [comment]
I've successfully tested all the way up to 1M without issue.

**Comment by Dallas-J** [comment]
I was using an algorithm to convert from RGB to RGBW - turns out the algorithm wasn't fast enough. I can run at 2M baud now with no problems. Maybe I'll try implementing an RGBW algorithm on the program side at some point but this is good enough for now.

**Comment by psieg** [comment]
Added in 5.11.2.16
