### ISSUE TITLE
Adjust brightness per led

### ISSUE THREAD

**Issue by LunarBear** [psieg/Lightpack#118]
Hi,

First thank your for this amazing fork of the official Prismatik.

Would it be possible to add a setting to adjust brightness independently per LED? I have a curved monitor (like more and more people) and I would LOVE to make the side LEDs a bit brighter compared to the other so I can achieve the similar level of light intensity on my wall. It would make a huge difference. 

On the official wiki in the settings description there is an item called: "Color balance" which seems to do just that but I can't find it in the unofficial Prismatik settings.

Thanks!

**Comment by psieg** [comment]
You can adjust it individually using the small arrow on the capture zones (show grab zones setting)

**Comment by LunarBear** [comment]
Oh wow sorry I had no idea that was an option, didn't see that at all and this wasn't in any documentation... My bad for opening an issue for this.

Thank you for your time and have a good day.
