### ISSUE TITLE
my verision is not connecting to my new windows update before it worked find please fix

### ISSUE THREAD

**Issue by Piloisback** [psieg/Lightpack#119]
or any help please?

**Comment by psieg** [comment]
This report is in no way helpful. Which windows update? What exactly stopped working? What device are you using? Have you tried restarting Prismatik / the computer? Have you tried reinstalling?

ref #111

**Comment by Piloisback** [comment]
I’m using the product primastic unoffial for my lightpack and I’m currently running windows version 10 and they replaced a patch that broke the lighting effect.

Sent from Mail for Windows 10

**Comment by psieg** [comment]
Which patch? A build update or a regular window update?
Have you tried uninstalling and reinstalling?

**Comment by psieg** [comment]
Closed due to missing feedback.
