### ISSUE TITLE
Implement api method 'getbrightness'.

### ISSUE THREAD

**Issue by damianromanowski** [psieg/Lightpack#13]
Something I've been looking for a while. A way to retrieve the current brightness level via the api.

**Comment by psieg** [comment]
By brightness do you mean the overall brightness multiplier of the LEDs or the average brightness of the captured screen?

**Comment by damianromanowski** [comment]
I guess I mean the last known brightness level that was set by the api call for `setbrightness:*`. Average brightness of all LED's would be a plus. But some way of using the api and being able to retrieve the brightness level instead of relying on a local program cache. If that makes sense..

**Comment by psieg** [comment]
I haven't used nor understood the API implementation yet, but if I see it correctly, this applies to all of those calls, like `setcolor`, `setsmooth` etc. Is that correct?

**Comment by damianromanowski** [comment]
Correct. Neither of those have a get command. And no reliable way to poll for current settings aside from current active profile. Which doesn't do much but return the profile name.

**Comment by psieg** [comment]
I'll look into it when I find a few hours. I haven't worked on Prismatik for a few months so I can't give you a time frame.

**Comment by psieg** [comment]
Well the assumed use-case for Prismatik plugins is having an external source that defines what colors to show. What do you want to do with the values you've just set yourself?

**Comment by damianromanowski** [comment]
Actually I'm using prismatik with my homekit setup. But since I cannot ask prismatik about its current brightness level, there is no reliable way for me to return data back to homekit. This is more of a wish-item. I can certainly just keep the setup the way it is right now. But if you implement it, I can adjust my setup and my homebridge plugin accordingly.

**Comment by psieg** [comment]
Implemented, will be included in the next release. You can try [the PR build](https://psieg.de/jenkins/job/Prismatik_Windows/78/), but is does not have its own version, so make sure to remove all other Prismatik versions first and use the next release once it's out.

**Comment by damianromanowski** [comment]
Awesome, thank you
