### ISSUE TITLE
Unable to detect change in-game

### ISSUE THREAD

**Issue by flathopps** [psieg/Lightpack#130]
Hi

I've been having an issue regarding the DX hooking whilst attempting to run my games full screen. It does not seem to detect any changes on the screen. When I alt-tab out of the game and back in, it will update the LEDs to what is present on the screen however, no further updates happen whilst in the game. 

Furthermore, I've found that even though the game Starbound supports borderless windows, Prismatik will fail to register any changes on the screen either. Although, this could be an issue with Starbound. (I've tried using Borderless Gaming and yet it did not seem to help.)

I found that Half Life 2, when ran in borderless mode, would result in Prismatik working correctly. 

I've had the official Prismatik work previously with the experimental DX hooking so I'm not sure as to why this isn't working. Any help would be greatly appreciated.

I also wanted to say thanks for taking the time out to modify their software to optimise it for us end users; we all really appreciate it!

Thanks for your time.

**Comment by psieg** [comment]
What OS are you on?. Probably just disabling DX hooking will do the trick

**Comment by psieg** [comment]
Assuming it works without hooking
