### ISSUE TITLE
Colors off

### ISSUE THREAD

**Issue by Yabdelwahed** [psieg/Lightpack#131]
I have three lightpacks behind the living room TV. The unofficial app detected 30 LEDs correctly, I had setup the zones (I placed each lightpack connected to 10 sequential strips so no skipping of zones or anything). The capturing is smooth. I fired up Kodi, it seemed that everything is fine then I noticed that on one part the colors are a little off. I went back to the program and use the white only zones option, and sure enough one of the lightpacks had all its 10 strips with a blue hue to it.

I have gone as far as ordering a new light pack and replacing that, it didn't make a difference. I installed the official 6.0 app, it didn't make a difference, and I changed the USB cable and port its plugged into and tried to even change some of the strips from the old one with the new one, it didn't matter, the new ones had a blue hue to them.

I also used the little arrow to try to individually control the RGD saturations of the 10 LEDs to that lightpack but never able to achieve similar colors representation as the others, can't ever get them to display 100% white color without a hue to it.

I tried to rerun the wizard, select different zone layouts, and no matter what I do that specific light pack gave all the colors with a blue hue to them. 

The other two lightpacks display 100% accurate color representation of the screen!!!

Is there anything I am missing here.

![20170713_194635](https://user-images.githubusercontent.com/30163471/28193517-62c05116-680b-11e7-811f-87d7d267d409.jpg)
![20170713_194647](https://user-images.githubusercontent.com/30163471/28193518-62cfd35c-680b-11e7-86cf-0dd2035ba614.jpg)
![20170713_194702](https://user-images.githubusercontent.com/30163471/28193519-62d26f0e-680b-11e7-9378-bfd9894577d7.jpg)

**Comment by psieg** [comment]
It might be they changed the LEDs they use. As a test, you can try plugging a strip with hue into one of the other Lightpacks.
Other than playing with the coefficents in the grab zone windows (the small arrow thing) there isn't much more you can do, without changing the hardware.
