### ISSUE TITLE
API functionality to unlock without reverting to pre-lock mood lamp colour

### ISSUE THREAD

**Issue by mihalski** [psieg/Lightpack#132]
Hi,

I've started working on a Home Assistant light platform for Lightpack and I just realised that when you unlock it reverts to pre-lock mood lamp colour.

Could we have some way (perhaps an additional toggle like persist:on/persist:off) to maintain the colour settings after unlock?

Would make the API MUCH more useful for many scenarios.

Regards,
Michal

**Comment by psieg** [comment]
Valid point, will consider for next release - but no timeline, sorry. Feel free to build it yourself, it should be rather straightforward. Let me know if you need directions

**Comment by MichaelSchemmer** [comment]
Hi mihalski,
Any progress on the Lightpack integration with HASS? I used to be able to contol the lights through HASS AIO, but since migrating to HASSIO its become a little more tricky, as I'd have to create my own add-on.
Let me know how its going and thanks for the work into this!
