### ISSUE TITLE
can't build it from source (opensuse)

### ISSUE THREAD

**Issue by allusernamesalreadytaken** [psieg/Lightpack#133]
Hello!

I am not an expert for building software by no means. I am using opensuse 42.2.

I tried to solve/install all dependencies. Unfortunately they are called here a little bit different then on debian.

Some warnings and errors are resolved but the remaining ones leave me clueless.
E.g.: 

" Function 'system' is not implemented" <- no idea whats causing this, did some googleing but without luck

"Package gtk+-2.0 not found" <- is installed, also the -devel package, the same goes for libnotify

Could someone please give me a hint? 

My outputs look like:

`linux-ae2v:/home/roman/Downloads/Prismatik/Lightpack/Software # ./update_locales.sh

=================================================
Updating translation files for Lightpack project:

/home/roman/Downloads/Prismatik/Lightpack/Software/src/src.pro(196): Function 'system' is not implemented/home/roman/Downloads/Prismatik/Lightpack/Software/src/qtsingleapplication/common.pri(10): 'qt5LibraryTarget' is not a recognized replace function/usr/share/qt4/mkspecs/features/qt_functions.prf(117): Function 'system' is not implementedProject ERROR: Package libusb-1.0 not found/usr/share/qt4/mkspecs/features/qt_functions.prf(117): Function 'system' is not implementedProject ERROR: Package gtk+-2.0 not found/usr/share/qt4/mkspecs/features/qt_functions.prf(117): Function 'system' is not implementedProject ERROR: Package appindicator-0.1 not found/usr/share/qt4/mkspecs/features/qt_functions.prf(117): Function 'system' is not implementedProject ERROR: Package libnotify not foundProject MESSAGE: Warning: unknown QT: serialportProject MESSAGE: Warning: unknown QT: serialport/home/roman/Downloads/Prismatik/Lightpack/Software/src/Settings.cpp:1688: Discarding unconsumed meta data
/home/roman/Downloads/Prismatik/Lightpack/Software/src/Settings.cpp:1707: Discarding unconsumed meta data
Bringe 'res/translations/ru_RU.ts' auf aktuellen Stand...
    Found 179 source text(s) (0 new and 179 already existing)
Bringe 'res/translations/uk_UA.ts' auf aktuellen Stand...
    Found 179 source text(s) (0 new and 179 already existing)
done

===========================================================
Generating release translation files for Lightpack project:

/home/roman/Downloads/Prismatik/Lightpack/Software/src/src.pro(196): Function 'system' is not implemented/home/roman/Downloads/Prismatik/Lightpack/Software/src/qtsingleapplication/common.pri(10): 'qt5LibraryTarget' is not a recognized replace function/usr/share/qt4/mkspecs/features/qt_functions.prf(117): Function 'system' is not implementedProject ERROR: Package libusb-1.0 not found/usr/share/qt4/mkspecs/features/qt_functions.prf(117): Function 'system' is not implementedProject ERROR: Package gtk+-2.0 not found/usr/share/qt4/mkspecs/features/qt_functions.prf(117): Function 'system' is not implementedProject ERROR: Package appindicator-0.1 not found/usr/share/qt4/mkspecs/features/qt_functions.prf(117): Function 'system' is not implementedProject ERROR: Package libnotify not foundProject MESSAGE: Warning: unknown QT: serialportProject MESSAGE: Warning: unknown QT: serialportUpdating '/home/roman/Downloads/Prismatik/Lightpack/Software/src/../res/translations/ru_RU.qm'...
    Generated 149 translation(s) (148 finished and 1 unfinished)
    Ignored 30 untranslated source text(s)
Updating '/home/roman/Downloads/Prismatik/Lightpack/Software/src/../res/translations/uk_UA.qm'...
    Generated 95 translation(s) (77 finished and 18 unfinished)
    Ignored 84 untranslated source text(s)

linux-ae2v:/home/roman/Downloads/Prismatik/Lightpack/Software # qmake -r
Reading /home/roman/Downloads/Prismatik/Lightpack/Software/math/math.pro
Reading /home/roman/Downloads/Prismatik/Lightpack/Software/grab/grab.pro
Reading /home/roman/Downloads/Prismatik/Lightpack/Software/src/src.pro
/home/roman/Downloads/Prismatik/Lightpack/Software/src/src.pro(196): Function 'system' is not implemented/home/roman/Downloads/Prismatik/Lightpack/Software/src/qtsingleapplication/common.pri(10): 'qt5LibraryTarget' is not a recognized replace function/usr/share/qt4/mkspecs/features/qt_functions.prf(117): Function 'system' is not implementedProject ERROR: Package libusb-1.0 not found/usr/share/qt4/mkspecs/features/qt_functions.prf(117): Function 'system' is not implementedProject ERROR: Package gtk+-2.0 not found/usr/share/qt4/mkspecs/features/qt_functions.prf(117): Function 'system' is not implementedProject ERROR: Package appindicator-0.1 not found/usr/share/qt4/mkspecs/features/qt_functions.prf(117): Function 'system' is not implementedProject ERROR: Package libnotify not foundProject MESSAGE: Warning: unknown QT: serialportProject MESSAGE: Warning: unknown QT: serialportUpdating '/home/roman/Downloads/Prismatik/Lightpack/Software/src/../res/translations/ru_RU.qm'...
    Generated 149 translation(s) (148 finished and 1 unfinished)
    Ignored 30 untranslated source text(s)
Updating '/home/roman/Downloads/Prismatik/Lightpack/Software/src/../res/translations/uk_UA.qm'...
    Generated 95 translation(s) (77 finished and 18 unfinished)
    Ignored 84 untranslated source text(s)
linux-ae2v:/home/roman/Downloads/Prismatik/Lightpack/Software # make
cd math/ && make -f Makefile 
make[1]: Entering directory '/home/roman/Downloads/Prismatik/Lightpack/Software/math'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/home/roman/Downloads/Prismatik/Lightpack/Software/math'
cd grab/ && make -f Makefile 
make[1]: Entering directory '/home/roman/Downloads/Prismatik/Lightpack/Software/grab'
g++ -c -pipe -O2 -fPIC -Wall -W -D_REENTRANT -DX11_GRAB_SUPPORT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -Iinclude -I../src -I../math/include -I.. -I. -o GrabberBase.o GrabberBase.cpp
In file included from ../src/GrabWidget.hpp:29:0,
                 from GrabberBase.cpp:27:
../src/GrabConfigWidget.hpp:28:29: fatal error: QtWidgets/QWidget: Datei oder Verzeichnis nicht gefunden
 #include <QtWidgets/QWidget>
                             ^
compilation terminated.
Makefile:243: recipe for target 'GrabberBase.o' failed
make[1]: *** [GrabberBase.o] Error 1
make[1]: Leaving directory '/home/roman/Downloads/Prismatik/Lightpack/Software/grab'
Makefile:77: recipe for target 'sub-grab-make_default-ordered' failed
make: *** [sub-grab-make_default-ordered] Error 2
`

**Comment by psieg** [comment]
The system errors aren't so important, what kills your compilation is `../src/GrabConfigWidget.hpp:28:29: fatal error: QtWidgets/QWidget: Datei oder Verzeichnis nicht gefunden
#include <QtWidgets/QWidget>`
Something about including the Qt Framework did not go right

**Comment by allusernamesalreadytaken** [comment]
Thank you for the hint! I was lost with the other warnings.

The package name which contains qmake qt5 is called `libqt5-qtbase-devel` here (and it was already installed).

It's under
/usr/lib64/qt5/bin/qmake

Now I used `qmake-qt5` which seems to use qt5 now. The following `make` command did build the binary which I could finally start :)

I could report if it's working properly if you like.

**Comment by psieg** [comment]
It's hard to tell, the logs look normal so far.
Since 10 GrabWidgets are created, please retry with a setup with more than 10 LEDs, does that fix it?
If you can, please provide a stack trace of the crash (for example based on this: https://github.com/JPNaude/dev_notes/wiki/Produce-a-stacktrace-when-something-goes-wrong-in-your-application)

**Comment by allusernamesalreadytaken** [comment]
Now there are 41 LEDs attached (that's the amount I need for the top of my display). The strange thing: I got some steps further in the wizard and could define the number and location of the LEDs. Trying to go to the next step crashed Prismatik again. With a segmentation fault error.
All following trials ended at the "choose profile" dialoge as before, although I deleted the Prismatik folder in my home folder. 

Is Prismatik writing config files somewhere else too, which I need to delete?


Did some further testing:
1) Not deleting the folder home/.Prismatik (after an attempt which crashed) . Restarting the wizzard, it crashes at the "choose profile" dialog after 10 GrabWidgets were created. Without the segmentation fault error (no error is written in the terminal)
2) Deleting the Prismatik folder. Going through the wizard, it crashes at the same dialog. But with the segmentation fault error and it creates 25 GrabWidgets.

The results described above are always the same. Sometimes I can see (second case) that there are some of these rectangular boxes drawn (just a short flashing) before Prismatik segmentation faults.

I attached the logs (firefox was causing the error yesterday, maybe noscript ...)

[Logs_prismatik_folder_deleted.zip](https://github.com/psieg/Lightpack/files/1253852/Logs_prismatik_folder_deleted.zip)
[Logs_prismatik_folder_not_deleted.zip](https://github.com/psieg/Lightpack/files/1253853/Logs_prismatik_folder_not_deleted.zip)

Regarding the stack trace, I haven't done something like that before. 
But if I understand it right, I do need to edit the source code and rebuild the binary to get the stack trace printed to a file?

**Comment by allusernamesalreadytaken** [comment]
Hello,

I got this issue solved! Thank you for your help :)

I updated the whole qt5 packages yesterday night and rebuild Prismatik and now everything seems to work as intended. 

I can't tell which qt5 version was installed before (it should have been 5.6xx), now it's

```
qmake-qt5 -v
QMake version 3.0
Using Qt version 5.6.1 in /usr/lib64
```

Thank you for your help :)
