### ISSUE TITLE
Lightpack not working on Win 10 1703 games and Netflix app

### ISSUE THREAD

**Issue by Couchmast3r** [psieg/Lightpack#134]
Hi,

Just realized that Lightpack is no longer working with the Netflix Win 10 app. 

Tried DX hooking and Desktop Duplication and it doesn't work for games or the Netflix app. Also no support in some browsers.

Please let me know if there is any solution to this.

Thank you

Prismatik Unofficial software 5.11.2.13 (revision cb8c711)
GTX 1070
i5-6600K
Win 10 1703 latest updates
NVIDIA driver latest

**Comment by psieg** [comment]
Netflix on Windows 10 (and probably 8) uses what is called the Microsoft Protected Media Pipeline, which disables Desktop Duplication for their window and prevents DirectX hooking into the process.
Nothing we can do, sorry.

**Comment by Couchmast3r** [comment]
Ok, thanks for clarifying. The same goes for most newer games and browsers?

Thank you for all the work you are putting into this - love it (where it works).

**Comment by psieg** [comment]
No, usually not. I have not yet seen a game that enables this protection. It goes for things that have to do with DRM and Copyright, mostly movies. Netflix in the browser works as far as I know.
