### ISSUE TITLE
Prismatik keeps crashing

### ISSUE THREAD

**Issue by saschakrohn** [psieg/Lightpack#138]
noticed my lightpack stopped working yesterday
re-launched the app, but the LEDs are not turning on, adjusted settings, its acting all weird and buggy
mood lamp works, but screen capture seems to not work right
then i got a pop up saying DX hooking isnt working since the app isnt running in administator mode
closed the app, relaunched in administrator mode, still doesnt work right
every time i click on SETUP WIZZARD now to configure the capture zones, the app just crashes
and changing some of the other settings also causes the app to crash... 

i didnt install anything new... 
only thing i can think of is that either avira antivir or windows pushed out an update and somehow block or broke the app?

**Comment by psieg** [comment]
Standard questions:
- What OS
- What device
- Have you tried rebooting, replugging etc
- Is it just the setup wizard? You can also adjust the zones by making them visible from the main menu
- Does it crash if you rename the `C:\Users\You\Prismatik` folder?

AV updates are unlikely to cause this.

**Comment by monstar10** [comment]
I'm having the same issue minus the DX error popup. Windows 10 PC with current updates, rebooting doesn't help. Sometimes running the configuration wizard will fix it, but most times it just crashes when I try that. I can tell if this is happening after right clicking the system tray icon, just moving the mouse over settings/profiles/etc will be a second or two delayed which carries over into the settings page if I open that. Clicking to view zones will check the box after a few seconds but the zone display never shows up.
The only way I can consistently get it to work again is to uninstall, delete all files in the users\Prismatik folder, then reinstall/redo my settings.

**Comment by saschakrohn** [comment]
win 10 64bit
PC lightpack with 10 LED strips
tried rebooting, replugging, reinstalling app
it doesnt reproduce the colors of the capture zones, the LEDs are either off or all white, and the setup wizzard crashes and sometimes the app itself crashes too, it seems really buggy and weird all of a sudden.
i didnt try renaming the folder... so that might help?

**Comment by saschakrohn** [comment]
more details:
screen grabbing mode
grab frequency 50fps
grab interval 19ms
over brightening 73
scene luminosity threshold 25
minimum luminosity level
overall brightness 98%
gamme correction 2.00
smoothness 15
capture source winAPI (fullscreen)
enable DX hooking CHECK
also hook D3D9 (high performance impact) CHECK
ping lightpack device every second CHECK
send data only if colors changed CHECK

**Comment by saschakrohn** [comment]
wow... it started working again! 0_o
i just ran through the config wizzard and this time after completing it, it works...

so i guess it WAS the nvidia driver causing issues, because i updated it again a few days again due to other issues, and now its working again?
I also noticed a windows update was installing last night, so that could have solved the issue as well?

monstar10, does it work for you again?
if not, check windows updates and then see if it works
and if not, update your nvidia/amd driver and check again if it works

**Comment by saschakrohn** [comment]
Btw, this is a good way to check if its working properly
https://www.youtube.com/watch?v=sr_vL2anfXA&list=PLr2ymV2BIrMecX3Jt8vnW0gkutWuPEchA

**Comment by psieg** [comment]
Happy to hear :+1:

As you are on windows 10, do yourself a favor and switch the capture source to Win8 Desktop Duplication and disable DX hooking.

**Comment by monstar10** [comment]
Sorry for the late response, just confirming that after downgrading my nvidia driver it seems to be working normally again. Hopefully this issue doesn't come up again with the next driver, because I'll need that for a few new games.

**Comment by saschakrohn** [comment]
im confused... i just looked at the prismatik app and all the settings are changed
grab interval has changed to 33ms
over brightening is set to 100
scene luminosity threshold is now at only 3
overall brightness is set to 100
capture source is set to winAPI (fullscreen)
DX hooking is disabled

how can this all change all of a sudden by itself?
i didnt update windows or the prismatik app since i last checked... what is going on? 0_o

**Comment by psieg** [comment]
If the settings are unreadable or have invalid values, they are reset to defaults, yes. WinAPI is not the default capture source however.
So no - should not.

**Comment by monstar10** [comment]
I'm having this issue again, it just started yesterday. Going back to the previous Nvidia driver did not seem to fix it this time. Any ideas? 
Official Prismatik does work, but without over-brightening it is almost useless for me.
