### ISSUE TITLE
Prismatik already running

### ISSUE THREAD

**Issue by Fing3rz** [psieg/Lightpack#14]
Whenever I start up windows i get this notification. "Prismatik already running". Like it tried to start twice or something. I did set it to start with windows. when i installed it? i think. i'm on win10 x64. no biggie just wanted to make you aware.

**Comment by psieg** [comment]
If you previously had the original Lightpack installed, it added a shortcut in your start menu folder. The new installer adds a different way to automatically launch with administrative privileges, so it seems both are active in your case.

If you did not uninstall Lightpack before installing the fork, you probably have the shortcut left over. Take a look at `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup`. If there is a shortcut to Prismatik, remove it.

**Comment by Fing3rz** [comment]
Yeah I seen the startup entry. It was listed as Prismatik(unofficial) so I left it thinking it was your's. I didn't realize your's is a task that starts at logon. So problem solved. thanks
