### ISSUE TITLE
Screen grabbing moving from 1st monitor to 2nd

### ISSUE THREAD

**Issue by Dawider10** [psieg/Lightpack#141]
I've configured Prismatik screen grabbing areas to be on the Monitor 1 (primary, with auto-sleep) but every time when I turn off Monitor 1 manually, they are moving to the Monitor 2 (secondary, without auto-sleep). Areas are not moving from Monitor 2 to Monitor 1 when I turn off Monitor 1.

**Comment by psieg** [comment]
Duplicate of #140
