### ISSUE TITLE
API Leds Indexed at 1

### ISSUE THREAD

**Issue by dmadison** [psieg/Lightpack#143]
I'm playing around with the API for the first time and I noticed something odd.  I was trying to get the `setColorToAll` function working, and what finally succeeded was starting the index at 1 rather than 0. Although the LED map received from the API is indexed at 0, Prismatik won't respond to a `set` command starting with a 0 index. A `set` command for indices 1 through n+1 seems to fill all LEDs, but it's still inconsistent and should be fixed.

I tested this with both my Adalight setup and a virtual LED device.

**Comment by psieg** [comment]
Indeed. I noticed this too, but I don't want to break compatibility with existing API consumers, so it will have to stay that way
