### ISSUE TITLE
Turn off lights when monitor is turned off

### ISSUE THREAD

**Issue by nhadrian** [psieg/Lightpack#147]
Hi, I'm using 5.11.2.13 on Windows 10 64bit, with an Arduino Nano and WS2812b LED stipe, code is by [Wifsimster](https://github.com/Wifsimster/adalight_ws2812).
Everything works fine, even LEDs are turned off uppon sleep mode.

But if the monitor is turned off by Windows, the LEDs remain on.
Since I didn't find any option in settings related this behaviour, I'd like to ask you to modify code with this feature.

Another useful feature would be to turn off LEDs when application closes but perhaps this can't be done because of Windows limitations. 

Many thanks in advance, regards
Adrian

**Comment by psieg** [comment]
There is an option to turn of LEDs when the Application closes.
I don't know if an Application can be informed that the screen has turned off. If the screen also locks (default on Windows I think) you can use that option

**Comment by zomfg** [comment]
If by "monitor turned off" you mean windows putting display to sleep then #201 does it.

**Comment by zomfg** [comment]
@psieg I guess depends on when you are planning to release it, but since it's merged, you can take over :p and I'll take a second look at Night Light thing.
