### ISSUE TITLE
Prismatik LEDs limitation 

### ISSUE THREAD

**Issue by sofos1990** [psieg/Lightpack#148]
Possible to lift the limitation of 99 for each direction?

**Comment by psieg** [comment]
The number is more or less arbitrarily chosen, yes. I'm not sure about the total limit of 255 (which would also be exceeded in your case I guess)

**Comment by sofos1990** [comment]
My case is for 314 LEDs. Horizontally 110 LEDs and vertically 47 for each side.
I think with the 144 LEDs/m strips and the Ultrawide monitors nowdays it might make sense for this.
What is weird for me is that max. LED support is up to 255 but the application allows you to select 99 for each side which doesn't make a total of 255.
I saw your other post on how to change the AsboluteMaximum which I did but unfortunately I don't know how to compile the software. I see there are instructions but my level of knowledge is not that high :(

**Comment by psieg** [comment]
Fixed with #154, will ship with the next release
