### ISSUE TITLE
More than 255 led strip ?

### ISSUE THREAD

**Issue by asgardc3r** [psieg/Lightpack#149]
hello, 

i'm trying to make prismatik work with a 262 SK9822 led strip.
it is working perfectly until 255 led, but no more

i've tried to change the number of led in main.conf but keeps crashing prismatik after.

do anyone have a solution ?

Thanks

**Comment by sofos1990** [comment]
That would be so useful! I'm looking for exactly the same.
In fact if you go to custom layout you can have up to 99 LEDs per side but even that is not enough with the 144 LEDs/m strip these days. I would appreciate if somebody could fix this.

**Comment by psieg** [comment]
I don't remember whether or not there was a good reason for that. Feel free to change the number [here](https://github.com/psieg/Lightpack/blob/b5edd7b95322ca36244a7a6ffbfd431abeb47366/Software/src/enums.hpp#L96) and try

**Comment by asgardc3r** [comment]
hi, 
i've tried to get this compile but no success so far.
could anyone help me get this done ?

**Comment by sofos1990** [comment]
Same here. I can't compile it.

**Comment by asgardc3r** [comment]
@psieg i've get it to work ( althought some warning in visual studio).
works perfects with 262 SK9822 leds.

do you think it will be possible to increase the max number of led to the original code and unlock the max number of led per side ?

thanks a lot for the work

**Comment by psieg** [comment]
If it works I can consider it for the next release, sure.

In the meantime, you should be able to try it by adding
```
<property name="maximum">
          <number>999</number>
</property>
```
[here](https://github.com/psieg/Lightpack/blob/master/Software/src/wizard/ZonePlacementPage.ui#L120) for `sbBottomLeds`, `sbSideLeds` and `sbTopLeds`.

Let me know how it works out

**Comment by asgardc3r** [comment]
![nouvelle image bitmap](https://user-images.githubusercontent.com/33607176/33455713-34455720-d61d-11e7-941a-3c181e2be93a.png)

hi, 
It works perfectly. How can i merge the changes with the main sources ? I have put the number of led to 511 without any probleme.

2 more things :
1/ i have modified the baudrate to 1500000 then 2000000 and every thing is working great. i think the code should have those baud rates.
2/ i have several warning and error. but the code works. i put the log out.

thanks

**Comment by asgardc3r** [comment]
@psieg , how do i merge the code ?
#

**Comment by psieg** [comment]
If it's only the three changes I described, it's probably easiest if I just do the changes for the next release.
If you want to, you can create a pull request.

Given your fork has no new commit, I assume you downloaded a zip archive (and are unfamiliar with git)?
In that case, just open the file in your fork (https://github.com/asgardc3r/Lightpack/blob/master/Software/src/wizard/ZonePlacementPage.ui) click the pen in the upper right corner and do the changes there.
Then click new pull request

**Comment by dtydings** [comment]
Hey hey! This was the only thread on the entire internets that mentioned increasing the max led count in prismatik. Were you all able to get this working? If so, would anyone be so kind as to help me understand how to install the modified version of prismatik on macOS? If you're still reading this thread 3 years later, thank you in advance!

**Comment by dtydings** [comment]
What I meant was to have prismatik send the same UDP packets to multiple IP addresses at once which should indeed sync all 4 strips. Unfortunately it seems like the WLED UDP sync only works for commands sent from other WLED platforms and it doesn't forward UDP packets to other controllers. 

I did some digging though and it turns out it's possible to just set the IP address in prismatik to broadcast IP address 192.168.x.255 and the UDP port to 21324. This makes the router duplicate and forward the UDP packets to anything on the network listening on port 21324. So far it seems like this is working very well! Probably this would work with Hyperion as well.

**Comment by mekochapo** [comment]
@mannebanco, I have the same issue that you had.... I bough a Dream color ambilight kit with a 5 meters led strip but its not enough to go around my 108 inch projector screen so I added 2 meters of LED strip.
Installed the unofficial version of prismatik ( that is ment to support up to 511 LED) but it still doesnt work.

What did you do to get yours working?

Thanks,
