### ISSUE TITLE
Plugins / API Server not working with > 99 LEDS

### ISSUE THREAD

**Issue by ctrahan625** [psieg/Lightpack#152]
I have a light project I am working on, it contains 184 leds. This version of Prismatik is the best software I found yet, I did however realize the new "Animate script" that was ported does not work (I fixed it with the API key, I put into the source it self), but then the animate script would "run" but the lights would not change, Prismatik it self would also not change to anything I did as it was locked by the API. After looking more into this, and testing and troubleshooting I found that if the led count > 99 then the plugins and android app do not work via the API.

Are others having the same issue? I was debugging the python script and I can see I am sending data to the API Server and I receive the Data, the API Server says its setting the color but infact physically if there s over 99 leds it does not.

Can someone shed some light? 

(I originally thought this was resolved, but after reading more, I think this is a different issue, but may be related.)

**Comment by dmadison** [comment]
Can confirm this. Just tested with the updated `testall.py` script from #151 and a virtual LED device. Setting LEDs up to 99 works fine, but LED 100 and beyond fail with a returned message of 'error' from the API server. Setting an entire frame fails similarly.

This line processes successfully:
`setcolor:99-255,0,0`

This line fails:
`setcolor:100-255,0,0`

**Comment by ctrahan625** [comment]
I am working on the source now, I finally figured out how to fully compile it and my first compile is a success, If I find a answer I will update this right away :)

**Comment by dmadison** [comment]
Just taking a quick glance [at the source](../blob/master/Software/src/ApiServerSetColorTask.cpp), it looks like it doesn't parse 3-digit LED numbers:

```C++
// Read led number
int ledNumber = PrismatikMath::getDigit(buffer[0]); // first char of ledNumber
int ledNumber2 = PrismatikMath::getDigit(buffer[1]); // second char of ledNumber
if (ledNumber > 0)
{
	if (buffer[1] == '-')
	{
		buffer.remove(0, 2); // remove "2-"
	}
	else if (ledNumber2 >= 0 && buffer[2] == '-')
	{
		ledNumber = ledNumber * 10 + ledNumber2; // 10,11,12..99
		buffer.remove(0, 3); // remove "10-"
	} else {
		API_DEBUG_OUT << "lednumber fail:" << QString(buffer);
		isReadFail = true;
		goto end;
	}
```

I don't have the source set up for compiling, but I'd try writing a short snippet for getting the 3-digit LED number and recompile.

**Comment by ctrahan625** [comment]
I'll take a look now :),  If I can confirm, then someone will have to figure out how to upload it to git lol

**Comment by ctrahan625** [comment]
Just as an Update,  I slightly modified the source dmadison mentioned, i added a few lines of code and now have it recognizing up to 999 leds with python scripting (Yeah ), However, I noticed only 99 led's now still only light :)  ,  Utilizing the Virtual LED showcase I can also see only 99 of the led's of the 184 light.  Now off to fix that code :)

**Comment by ctrahan625** [comment]
Last update of the night, I have accomplished the task at hand thanks to @dmadison for your help, Its really early and I do not have the effort to document the changes, They are pretty simple and I will update this tomorrow and see if we can't get this added into the next release.

**Comment by ctrahan625** [comment]
Final Followup on this for future reference.  I am just posting my changes, hopefully someone can implement them into the final version.

in file 'ApiServerSetColorTask.cpp' around line 68, you will see code simular to the following, replace from //Read led Number to  "API_DEBUG_OUT << "lednumber-" << ledNumber << "buff-" << QString(buffer); "
```
        // Read led number
        int ledNumber = PrismatikMath::getDigit(buffer[0]); // first char of ledNumber
		int ledNumber2 = PrismatikMath::getDigit(buffer[1]); // second char of ledNumber
		int ledNumber3 = PrismatikMath::getDigit(buffer[2]); // second char of ledNumber
		
        if (ledNumber > 0)
        {
			if (buffer[1] == '-') //Single LED Number
			{
				buffer.remove(0, 2); // remove "2-" //Get rid of the first 2 chars from the RGB Values.
			}
			else if (ledNumber2 >= 0 && buffer[2] == '-') //2 Digit Number
			{
				ledNumber = ledNumber * 10 + ledNumber2; // 10,11,12..99
				buffer.remove(0, 3); // remove "10-" from the buffer
			}
			else if (ledNumber3 >= 0 && buffer[3] == '-') // 3 digit number
			{
				ledNumber = (ledNumber * 100) + (ledNumber2 * 10)  + ledNumber3;
				buffer.remove(0, 4); // remove "100-" from the buffer
			}
			else {
				API_DEBUG_OUT << "lednumber fail:" << QString(buffer);
				isReadFail = true;
				goto end;
            }
        } else {
            API_DEBUG_OUT << "isdigit fail:" << QString(buffer);
            isReadFail = true;
            goto end;
        }

        API_DEBUG_OUT << "lednumber-" << ledNumber << "buff-" << QString(buffer);
```

**Comment by psieg** [comment]
This isn't solved in the master branch, right? Then please leave it open.
@ctrahan625 does everything work for you with the changes you mentioned?
