### ISSUE TITLE
Invert order settings uninvert when prismatik is closed and relaunched

### ISSUE THREAD

**Issue by rogermoorez** [psieg/Lightpack#157]
When i select invert order during the wizard setup process and close and relaunch prismatik it will uninvert my profile and i have to recreate it.

I have tried setting it to read only and it still changes.

**Comment by psieg** [comment]
I'll try to reproduce next time I work on it. Can you please provide some more details:
*Which LED device?
*Does it happen with virtual LED device?
*How many LEDs?
Thanks

**Comment by rogermoorez** [comment]
Hi sorry I missed your last message, I reformatted my Windows 10 installation and I'm no longer having this issue and I'm unable to reproduce it either, I guess something on my end was causing the problem.

Thanks

**Comment by psieg** [comment]
Happy to hear :)
