### ISSUE TITLE
API Server port not working

### ISSUE THREAD

**Issue by Portanna** [psieg/Lightpack#160]
API Server port not working when "listen only on local device is disabled
![image](https://user-images.githubusercontent.com/20915660/35298841-b1c0b600-0083-11e8-84f1-d28abb6ab277.png)

**Comment by dmadison** [comment]
Just tested and everything is working fine for me. The API server starts with the checkbox disabled and I was able to send commands from another PC on the same network.

I'd check your firewall and proxy settings.

**Comment by psieg** [comment]
I can't reproduce this either, sorry.
