### ISSUE TITLE
Full DirectX HDR Support

### ISSUE THREAD

**Issue by melgu** [psieg/Lightpack#175]
I'd love to see full HDR Support for Prismatik.

Using the native Windows HDR Setting is no problem, all colors look correct. Also playing HDR10 movies via MPC-HC or -BE with MadVR does work and everything looks normal.

For some reason though, the colors in Battlefield 1 are way off when in HDR10 mode. White on Screen becomes pink in the LEDs. There seems to be an issue with the DirectX grabber.

**Comment by psieg** [comment]
By DirectX grabber, do you mean DX hooking or Desktop Duplication? You should be able to turn off DX hooking and have everything work, if not better.

**Comment by psieg** [comment]
Closing some old issues, sorry for the spam, if any.

**Comment by melgu** [comment]
Sorry for not closing it myself. I didn’t experience it anymore. Everything works fine 👍
