### ISSUE TITLE
Color Calibration Wizard Broken for Adalight Devices

### ISSUE THREAD

**Issue by dmadison** [psieg/Lightpack#176]
Using an Adalight device on 5.11.2.15, moving the sliders in the calibration wizard does not change the color sent to the LEDs, which is always pure white.

(Except for the initial few frames, which are black re: #123)

**Comment by dmadison** [comment]
Evidently :worried:. Last tested with 5.11.2.12 it was updating but the LED count was wrong. With x.15 the LED count is correct but the colors aren't updating. Some change between those two broke it.

**Comment by psieg** [comment]
I was able to reproduce the issue, fix will be in the next release.
Thanks for the report 👍

**Comment by psieg** [comment]
Fixed in 5.11.2.17

**Comment by dmadison** [comment]
Confirmed fixed!
