### ISSUE TITLE
Windows Night Light Support

### ISSUE THREAD

**Issue by raulnor516** [psieg/Lightpack#177]
Love this improvement of Prismatic, I can finally stop using AmbiBox! I see that Flux support is included, is there a way of supporting the Windows 10 built in Night Light?

**Comment by psieg** [comment]
The windows night light works differently than f.lux.

If you can tell me how I can figure out it's state via API, I'll take a look.

There seems to be a registry key, but how to get the state from those binary values?
https://stackoverflow.com/questions/43340619/get-status-of-night-light-mode-in-windows-10
