### ISSUE TITLE
Enormous sized log files from prismatik

### ISSUE THREAD

**Issue by Kristijan007** [psieg/Lightpack#182]
Today windows informed me of low disk space on my C: drive. And the cause was from prismatik log files which were two files ranging from 15-17GB. Please check it out. 
I've deleted one but then I thought to share it here and provide proof.
![image](https://user-images.githubusercontent.com/37227513/39614637-9e789792-4f71-11e8-981e-ab1e69e33c5e.png)

**Comment by psieg** [comment]
That's interesting. Which log level do you have set? How long does Prismatik usually run?

If you still have the file, please zip it (should be just a few megabytes then) and attach it here.

**Comment by psieg** [comment]
@Kristijan007 any update? Do you still have one of the files and what is your log level?

**Comment by psieg** [comment]
Which file is it exactly? You can change the log level in the experimental section, which you can enable from the profiles section. It should be 0, which logs only very few lines, unless you regularly have errors....

**Comment by dimd13** [comment]
Thanks, I found the log level setting. It was set to 2 and I changed to 0. Log file no longer grows.

**Comment by Pokounekcz** [comment]
Yeah, i have the same problem but i use prismatik daily it boots right up with my pc as my ambient lightning and today i found out that i have no space on C disk then i went searching whats wrong and my file has already 107GB :D
![image](https://github.com/psieg/Lightpack/assets/174823643/459de201-b7fc-4df0-af9f-5a818488b1dd)
on photo i already deleted one file
![image](https://github.com/psieg/Lightpack/assets/174823643/e123917e-b84a-4d16-8252-3f3682565622)
