### ISSUE TITLE
Need help on setting up 2 monitors with 2 different light strips

### ISSUE THREAD

**Issue by JoeMarko** [psieg/Lightpack#188]
I currently have two ambilight pack for dual monitors but i can only set up one of them, cant set both.
Can anyone show me how to set both light up?
Thanks

**Comment by spacemanspiff2007** [comment]
Wondering the same here. Or is it possible to aggregate both monitors to one and then have the leds go around both monitors?

**Comment by psieg** [comment]
Except for Lightpack devices, Prismatik supports a single device only. So the solution would be to control all LEDs with one device and set that up in Prismatik.

**Comment by spacemanspiff2007** [comment]
Thank you for your reply.
