### ISSUE TITLE
LEDs flicker on and off when bright white color are on screen

### ISSUE THREAD

**Issue by atunnard** [psieg/Lightpack#189]
I'm sometimes having problems when a large amount of white or grey is on part of the screen (bright sky scenes or windows menus) the LED's will flicker rapidly on and off. sometimes it fixes itself but will return if I'm on a dark scene for a while and go back to a white one.
 
It's not all white scenes which makes me think its not power related and sometimes the flickering stops when I increase the over-brightening or change the eye care settings to dead-zone, but none of these fix it permanently. 

Here's a video of it flickering. https://youtu.be/vbbf6PtH7HQ

**Comment by psieg** [comment]
Please disable over-brightening to see if that fixes the issue

**Comment by psieg** [comment]
@atunnard did it help? Which version were/are you running?

**Comment by Razer1991** [comment]
I have the same issue. https://youtu.be/a6vCVTxV2BA
![LightpackSetting.jpg](https://www.upsieutoc.com/images/2019/02/08/LightpackSetting.jpg)
is that a hardware issue or software issue? plz help me to solve this problem.

**Comment by atunnard** [comment]
> I have the same issue. https://youtu.be/a6vCVTxV2BA
> ![LightpackSetting.jpg](https://camo.githubusercontent.com/439583189a014677411817ff46b25aa24eb7c6a4/68747470733a2f2f7777772e757073696575746f632e636f6d2f696d616765732f323031392f30322f30382f4c696768747061636b53657474696e672e6a7067)
> is that a hardware issue or software issue? plz help me to solve this problem.

I couldn't fix it, i guessed it was something wrong with the led strip as I can't even get it to display a static colour bypassing the screen monitoring.
