### ISSUE TITLE
High GPU usage on Windows 10 1803

### ISSUE THREAD

**Issue by fingerwarrior** [psieg/Lightpack#193]
Prismatik frequently starts using 10~15% of GPU for a couple of seconds and then goes back to <1%. This is with Windows 10 1803 x64 (17134.285), Nvidia GTX 1070 (driver 399.07). Both task manager and Hwmonitor report same usage stats, with task manager showing 'Lightpack Software' at the top of the list.

![image](https://user-images.githubusercontent.com/8464592/45575916-c84c9c00-b892-11e8-9782-47daf5ce642f.png)

Edit:

Tested more, and the GPU usage is directly linked with GPU core clock, with only desktop showing the GPU runs at 139MHz, and usage shoots up. With a 3D application using the GPU and GPU clock ~1850MHz, the highest I've seen the usage for prismatik go is about 2.5%. Also, the usage is directly linked with Desktop Window Manager (dwm.exe), if dwm usage goes up, prismatik goes up as well. This is probably due to the desktop duplication api, and probably out of your hands.

**Comment by psieg** [comment]
This is normal behavior. When nothing happens on your desktop, the actual frame rate is way lower than what you configured (~3 FPS). When you start moving the mouse or watching a video the capture (and processing) rate jumps up (to 16 FPS in my case). As soon as you stop the mouse/video it will go down again. When something actually produces more frames (such as a game), Prismatik will consume more GPU and CPU resources to process the higher frame rate, up to the delay you have configured.
