### ISSUE TITLE
Macos Mojave slow perfomance

### ISSUE THREAD

**Issue by canh046** [psieg/Lightpack#210]
My macbook pro 15'' touchbar is very slow when i turn on Screen Grabbing (50ms). It's very lag.
GPU monitoring show very high usage.
My MBP use core i7 2.6ghz + 16GB ram & GPU radeon pro 450.
Please fix it.

**Comment by psieg** [comment]
Yeah afaik the grab method on mac is quite ancient, but I don't have a mac...

**Comment by canh046** [comment]
Have any Mac developer can replace grab method on MACOS. Screen mirroring api on windows is very amazing

**Comment by zomfg** [comment]
Can you provide more details?

- how high is your CPU usage now?
- how high was it before Mojave?
- are you sure it's your GPU usage that is high?
- what framerate do you get with 50ms?
- what framerate do you get with 1ms?
- what do you mean by "very lag"? actual lag/delay with ok framerate? or stuttering / frame drops? super low fps?

**Comment by canh046** [comment]
> Can you provide more details?
> 
> * how high is your CPU usage now?
> * how high was it before Mojave?
> * are you sure it's your GPU usage that is high and not CPU?
> * what framerate do you get with 50ms?
> * what framerate do you get with 1ms?
> * what do you mean by "very lag"? actual lag/delay with ok framerate? or stuttering / frame drops? super low fps?

Hi Zomfg
I track it on system monitor, both CPU and GPU are very high usage.
two task named windows server (70%) and primatik (11%) CPU usage
Framerate at 50ms is about 3 to 6 fps
when change it to 1ms it less than 5 fps.

Screen grabbing on Mac use screenshot continues so it had very high usage hardware. On windows have screen mirroring api and scale the second screen after mirroring to low resolution, it's very smooth and amazing.

**Comment by canh046** [comment]
> I'm seeing same kind of CPU usage as you on a 2013 iMac under 10.12.6, and under 10.14.2 in a virtual machine on a similar computer, but in my case I get 30 FPS as expected.
> I tried the last release and a fresh build, same result.
> So maybe it's a weird issue with some driver on a macbook, as #211 lists same hardware, I don't know.
> 
> Yes, there is now a better way for capturing on macOS, but it needs some time.

Because u dont use retina display. When i turn off retina display and it up to 18 fps. But it's still lag when i play video from full HD to 4K :( 
Has anyone can bring screen mirroring api to MAC version?

**Comment by zomfg** [comment]
try [this](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik-grab-test.dmg)

**Comment by canh046** [comment]
> try [this](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik-grab-test.dmg)

Wow,
it's seem to be better performance.
CPU and GPU are down to half of previous version.
Time interval: 33ms and it's up to 30 fps.

**Comment by zomfg** [comment]
How high was the usage?
Is it using the intel gpu?
Are you seeing a difference in usage with settings open/closed?
Are you seeing lack of precision between LEDs?
~30fps is max for 33ms, so that's good.

**Comment by canh046** [comment]
> How high was the usage?
> Is it using the intel gpu?
> Are you seeing a difference in usage with settings open/closed?
> Are you seeing lack of precision between LEDs?
> ~30fps is max for 33ms, so that's good.

with this performance, i feel very happy.
CPU and GPU is use less than 10%

**Comment by canh046** [comment]
if i unplug external monitor it will use Intel GPU, about 10~15% GPU usage

**Comment by zomfg** [comment]
Well, that's promising then. Does it crash a lot right now?

@Kaitoukid93 you could test this too

**Comment by mihalski** [comment]
@zomfg I can't get over how amazing the difference in performance is thanks to your new MacOS AV grabber. Thank you!

**Comment by zomfg** [comment]
Oh thanks! just in case: use the actual build from release tab, not the one I posted in this thread.
It also supports Night Shift if you are into that.

**Comment by mihalski** [comment]
Yes I'm using the release build..

Previously if I was using screen capture the MacOS UI was barely usable and would stutter when dragging windows and even miss mouse clicks. Now it's smooth as butter as if it wasn't even running.

**Comment by zomfg** [comment]
Are you on 10.13 by any chance? There's a weird bug on 10.12 and not on 10.14 and I could not test 10.13

**Comment by mihalski** [comment]
I'm on 10.14.3 (it also worked fine on 10.14.2). Any reason you're still on 10.12?

**Comment by mihalski** [comment]
Could always do a SuperDuper backup and try it on that instead of your main drive. Mojave is a nice upgrade to 10.13 so it would be doubly so to 10.12.

**Comment by AlexKusnezov** [comment]
Hey guys. the ambilight function (screen grab) works only for desktop and not for video. I get only good video reacting if I watch youtube videos in safari but not in chrome and not in vlc or iina. I have a gtx 980 ti on 10.13. Any idea what I'm doing wrong?

**Comment by zomfg** [comment]
What do you mean by "good video reacting"?
What happens with Chrome and VLC?

**Comment by AlexKusnezov** [comment]
> What do you mean by "good video reacting"?
> What happens with Chrome and VLC?

In chrome and vlc I don't get reacting at all. In particular no reaction on video. In chrome it reacts on the website elements, e.g.  Youtube logo. but not on video playback. If I do fullscreen there, nothing happens. The light is still. Same in VLC. It just takes the light from the desktop

In Safari it works perfectly with videos on youtube

**Comment by zomfg** [comment]
Try [this](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/AVScreenShack_10.14.app.zip) (just launching is enough, but you can change settings if you want), you'll see what's being captured (it uses the same method).

**Comment by AlexKusnezov** [comment]
> Try [this](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/AVScreenShack_10.14.app.zip) (just launching is enough, but you can change settings if you want), you'll see what's being captured (it uses the same method).

cool, will try. Thnaks

**Comment by AlexKusnezov** [comment]
Currently I'm on 10.13 High Sierra, because i have only a gtx 980 ti and have to rely on Nvidia Web drivers, so no chance to update to Mojave. The capture works now quite smooth, but cpu and gpu usage is also quite high about 30% both :( but this is maybe because I'm driving 372 led for dual 4k monitors. Does anyone have a similar setup with Mojave?

**Comment by zomfg** [comment]
So Chrome and VLC work fine now?

> cpu and gpu usage is also quite high about 30% both :( but this is maybe because I'm driving 372 led for dual 4k monitors

Very likely, that combined with capture framerate and the size of capture zones.
You can test the impact of the capture alone (well, almost) with that app I linked by setting scale to 0.05 and framerate to whatever you use in Primastik.
Going from 10.13 to 10.14 won't have a _direct_ impact on Prismatik (dark theme aside). Maybe if your current setup underperforms due to drivers/OS issues, but unless your are targeting something like 10fps your usage doesn't look shocking to me.

**Comment by AlexKusnezov** [comment]
@zomfg yes everything works perfect now, this is how it looks: https://www.instagram.com/p/Buyp3RtIRtB/?hl=en
Thanks for helping.
Yes Im running 20fps, but get no UI lags whatsoever and don't mind the cpu load.

Compared to the same setup on windows, Windows is clearly the winner having only less than 10% CPU/GPU load. Maybe because the Windows treats rendering/scaling UI elements in a different way or capture method is better there.
