### ISSUE TITLE
Odroid build failed?

### ISSUE THREAD

**Issue by alexmorbo** [psieg/Lightpack#22]
Hello!

Affter I make qmake -r && make i run this:
```
odroid@odroid:~/Lightpack/Software$ ./scripts/linux/prepare_installer.sh
cp: cannot stat ‘src/bin/Prismatik’: No such file or directory
```
But there is no src/bin folder, why?

**Comment by psieg** [comment]
Thanks for noticing. The binary output has been moved from `src/bin/` to `bin/`. Made me realize my jenkins was setup incorrectly as well.

**Comment by alexmorbo** [comment]
Yep, i found binary file.

But in Odroid C1+ board  Prismatik give me 4 fps :(

**Comment by psieg** [comment]
I'm afarid I'm out of knowledge there. I use the Windows version - I haven't even looked into how screen grabbing works on linux. Does it perform better with the original Prismatik?

**Comment by alexmorbo** [comment]
Its the same, in linux better is boblight

**Comment by psieg** [comment]
Since the build works, I'll close this. Anyone is welcome to look into screen grabbing on linux
