### ISSUE TITLE
Prismatik application won't start on Windows 10 - fails silently

### ISSUE THREAD

**Issue by JonasWechsler** [psieg/Lightpack#240]
Prismatik doesn't start at all on Windows 10- no error message, nothing in the tray, absolutely nothing happens when I try to start it. I've uninstalled and reinstalled several times, and the same thing happens.

I'm on Windows 10 Pro, version 1803, OS build 17134.523

**Comment by zomfg** [comment]
Try deleting your profiles and/or config in `C:\Users\you\Prismatik`

**Comment by psieg** [comment]
Fixed in  5.11.2.19
