### ISSUE TITLE
one color/channel per LED

### ISSUE THREAD

**Issue by EllaBarker** [psieg/Lightpack#241]
To make it short take a look at this picture off fullscreen green: https://imgur.com/7HOUlQ5

long story:  every three LED represents just one color channel (R,G,B) instead of all of them. Further they just turn blue. the picture I uploded is a example of green. Red and blue turns on the other LEDs.

what happened before?
- prismatik updated itself
- updated some arduino library's 
- added a nicer start up animation to the arduino script
- windows 8 only shows a defender signature update installed today

what i already tried:
- the ws2812b working fine and can be individually addressed like they should
- "serial" data transfer to the atmel 32u4 is working without a problem at baud 2'000'000
- reducing baud rate to 115200
- uninstalling the latest version and installing older versions
- trying old versions of the arduino sketch
- rolling back to old versions of the arduino library's

what i have not checked: 
- data generated/output by/from prismatik

Anybody else experiencing this or know further steps to solve the issue?

**Comment by dmadison** [comment]
Can't replicate on my setup with the latest version of Prismatik. What sketch are you using on the Arduino?

**Comment by EllaBarker** [comment]
Sry. Indeed it was the skript. Even the backups of the Skript where broken at lines i did not touched yesterday:
```
 while (!Serial.available());
      b = Serial.read();
      leds[i].r = r >> 1; //divided by 2
      leds[i].g = g >> 1;
      leds[i].b = b >> 1;
```
