### ISSUE TITLE
Restore Version Number on About Tab

### ISSUE THREAD

**Issue by MaddBomber83** [psieg/Lightpack#245]
Version 5.11.2.18 removed the currently installed version number from the about tab.  Please restore it.

**Comment by psieg** [comment]
Which version number do you mean exactly? Can you post a screenshot? Also try 5.11.2.19 please

**Comment by zomfg** [comment]
In my case, building `master` from source has app/commit version in the About, the `.19` binary from releases hasn't. and neither does pre `.19` `master` (by a couple of commits)

**Comment by psieg** [comment]
The official releases should be release builds.
I just built debug and release locally and the debug version was initially missing the version line - after rebuilding it both worked though

**Comment by zomfg** [comment]
I just did several clean&rebuilds and my debug build did not want to show versions any of those times, and the release worked on first try now...

**Comment by psieg** [comment]
The v19 release build does show the version number for me. Considering this fixed, feel free to re-open.
