### ISSUE TITLE
Disable screen grabbing when device gets disconnected

### ISSUE THREAD

**Issue by schrej** [psieg/Lightpack#248]
MacOS 10.14.2, Prismatik 5.11.2.19, Arduino with [Adalight-FastLED](http://github.com/dmadison/Adalight-FastLED)

I'm using Prismatik on my MacBook. Today I noticed it running in the background, capturing my screen after I disconnected it from my monitor and Arduino. Even though its using quite low resources after the latest improvements (that actually made it usable on MacOS, thanks!), it still consumes some resources.

It would be nice if Prismatik would detect when the device is no longer connected and turn itself off automatically.
Maybe just by checking every few seconds as long as the light is turned on.

**Comment by psieg** [comment]
Good idea, should be easy to do

**Comment by extermistmonk** [comment]
Unfortunately, the fix for this broke the way I use Prismatik. I use a plugin that sends grabbed colors across the network to an ESP8266 which controls my Ambilights. Since I don't technically have a device connected, this update broke my setup.

**Comment by psieg** [comment]
Your setup should work if you set up a virtual device. A virtual device won't report errors.

Let me know if this helps

**Comment by extermistmonk** [comment]
Perfect, works great, thanks!

**Comment by psieg** [comment]
Great. Marking as fixed in 5.11.2.20
