### ISSUE TITLE
Led flashing

### ISSUE THREAD

**Issue by Razer1991** [psieg/Lightpack#249]
I have this issue. https://youtu.be/a6vCVTxV2BA
![LightpackSetting.jpg](https://www.upsieutoc.com/images/2019/02/08/LightpackSetting.jpg)
is that a hardware issue or software issue? plz help me to solve this problem.

_Originally posted by @Razer1991 in https://github.com/psieg/Lightpack/issues/189#issuecomment-461776790_

**Comment by psieg** [comment]
Hard to tell. Which device are you using?

**Comment by Razer1991** [comment]
what do u mean "device"?
i used ws2812b led and ambilight

**Comment by zomfg** [comment]
How many LEDs and how are you powering them?

**Comment by Razer1991** [comment]
i used type 60 led/m and 5v4A

**Comment by zomfg** [comment]
And if you re-configure with 10 LEDs for ex?
What baud rate are you using? Is it set on both sides?
Did you test your strip with FastLED/Neopixel demo sketches?

**Comment by Razer1991** [comment]
10 leds for ex? i don't know what u mean
I don't know much about this device, I bought it in the internet and a seller installed a software and setting up for me, he sold many of this devices so i trust his work, but sometimes leds flash like a clip i posted, I contacted him and he tried to figure it out and fix sth, it is worked but not long, I get this problem right after a few days. I remembered he tell me to reduce total brightness below 50% so this device will not use a lot of power to cause flash, but i never set brightness over 20%.
Everything is ok with "mood lamp" mode so i guess its not a hardware problem? It only happens when I use screen grabbing mode.

**Comment by zomfg** [comment]
I meant setting Prismatik to 10 LEDs instead of full length.
What baud rate are you using? Is it set on both sides? (Prismatik and arduino)

**Comment by Razer1991** [comment]
This is my settings 
![Setting-up-Adalight.jpg](https://uphinhnhanh.com/images/2019/02/13/Setting-up-Adalight.jpg)

**Comment by zomfg** [comment]
Try with 10 LEDs (after the screens you posted just set number to 10, the rest of the strip should stay off/constant until you change back to full length later).

**Comment by Razer1991** [comment]
The seller sets up for me with custom mode,now it shows only 138 total leds, the rest (side, top, bottom) have been reset so i dont know which number to fill into that line.
Can u post a picture to show me how exactly what should I do with that settings plz?
BTW, the seller sends me a link to install a driver [http://www.arduined.eu/files/windows8/CH341SER.zip](url), then he starts to set up prismatik.

**Comment by zomfg** [comment]
> only 138 total leds

uuhhh... so you had how many total again? How big is your display?

[This](https://www.youtube.com/watch?v=lxvXuhwYgM4) pretty much shows the process (older version but still applies), including the driver part. Around 1:20 you can put any number of LEDs within the limit of your strip (don't put 5000 if you have 100).

If you don't have flashing with a low number such as 10, it could be either your power supply or your baud rate.
If a full white mood lamp combined with the actual number of LEDs (ALL lit) is fine, then your power supply is probably OK and you need to up your baud rate to something like 500k: the screen around 0:55 in the video for Prismatik AND it has to be done on the device too (firmware update).

**Comment by Razer1991** [comment]
I guess i have 138 leds because when I click random number in a test screen, the led turns white exactly where it should be
My display is 32".
Like I said before, I can use mood lamp with any of brightness level without problem, even at white color (most power consumer the seller said)
About the clip, I saw it and I think I do exactly the same what he did but the problems is still there.
About baud rate, is it safe to set above 115200?

> AND it has to be done on the device too (firmware update) how can I do this?

**Comment by zomfg** [comment]
> I guess i have 138 leds

Look at the back of you display and count them with your eyes to be sure once and for all.

> About baud rate, is it safe to set above 115200?

Yes, worst case you can change again to something more compatible.

> how can I do this?

Either by asking your seller to send you a new binary, or a source code and following his procedure to upload to the board.
or by getting any other adalight sketch (such as [this one](https://github.com/dmadison/Adalight-FastLED)) and changing values yourself and uploading to your board with Arduino IDE or other (this last part will be more or less same as if you go through the seller).
I'd go the seller route given your lack of experience (it's still pretty easy and low risk to do yourself but you'd need to check a couple of videos about arduino/adalight I guess)

But before this, do the test with 10 LEDs...

**Comment by Razer1991** [comment]
Ok so after a few days testing a new config, the flash disappear 💃 , and I guess the reason causes my issue is the seller didnt make a proper setup with led positioning config as pictures below:
Before- Seller
![Prismatik-Setup.jpg](https://uphinhnhanh.com/images/2019/02/21/Prismatik-Setup.jpg)
After- Mine
![Prismatik-Setup-Best.jpg](https://uphinhnhanh.com/images/2019/02/21/Prismatik-Setup-Best.jpg)
So my problem is solved, thanks for your help @zomfg 👍
