### ISSUE TITLE
Alienware AW3418HW

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [psieg/Lightpack#254]
Is it possible to get the screen colors and use them on the LEDs of this monitor?

**Comment by zomfg** [comment]
Seems to be technically possible (or at least was at some point in time), but it has to be implemented...

**Comment by JavierSegoviaCordoba** [comment]
Really I researched on Google and the only thing I have found is this program (older version even) in some forums talking about using it on Alienware Laptops...

So at this moment, it should not work with my monitor no?

**Comment by zomfg** [comment]
I'd be very surprised if this works out of the box... It would mean that they'd implemented Prismatik's protocol, which I doubt. Or maybe someone hacked something to allow this.

From what I understand this stuff needs AlienFX (which looks similar to Razer Chroma...)

If you use your own LED strip it'll work with any monitor (you can build your own thing for under $50, or buy pre-built).
But there's an issue with GSYNC compatibility (see #199), so beware...

**Comment by JavierSegoviaCordoba** [comment]
@zomfg my Alienware Monitor uses AlienFX but this program hasn't the "ambilight" feature. So if my monitor works with AlienFX, Lightpack should work?

**Comment by zomfg** [comment]
oooh I completely forgot I saw it there... well then yeah, you can try, of course
I don't know if it's in a working state though (API and/or hardware could've been updated), there were some issues in the past it seems, see [here](https://www.reddit.com/r/Lightpack/comments/6k66ou/new_user_error_when_setting_up_prismatik/)
