### ISSUE TITLE
Prismatik does not like portrait mode

### ISSUE THREAD

**Issue by RonnieViklund** [psieg/Lightpack#257]
I wanted to try Prismatik with Visual Pinball, I have the monitor on a swivel that can rotate into portrait mode but Prismatik does not seem to like that. From the debug logs:

19:29:51:967 Critical: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Dimension mismatch: screen 1440 x 3440, texture 3440 x 1440
19:29:51:967 Debug: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Lost Access to desktop 0x10001 : 0x887a0001 , requesting realloc
19:29:51:983 Debug: void __cdecl GrabberBase::grab(void) reallocating

**Comment by zomfg** [comment]
#253 duplicate
if you need it now you can try other grabbers
the ddupl one has to be adapted

**Comment by RonnieViklund** [comment]
Sorry my fault for not checking existing issues.

**Comment by Oscar438** [comment]
I'm getting the same log message for a resolution of 1080 x 1920. Are there any plans to adapt the ddupl grabber?

Does anyone know if #258 supports portrait mode?
