### ISSUE TITLE
Screen Grab Color Stuck with Desktop wallpaper color

### ISSUE THREAD

**Issue by Sajedull** [psieg/Lightpack#263]
Mood lamp is ok for me ,but screen grab color not change on linux manjaro ,and im also new in linux is there any special option for enable this ?

**Comment by psieg** [comment]
Does it not grab colors at all or do they not change when you move a window for example?

**Comment by Sajedull** [comment]
Sorry 
It was my Distro Problem ,Now Using Manjaro Xcfe and its ok
