### ISSUE TITLE
Changing of default values

### ISSUE THREAD

**Issue by TheMcSebi** [psieg/Lightpack#267]
Hello,
I'm using Lightpack with a LED strip behind my TV screen mounted above my other monitors. Since I'm not using the TV all the time, I have to change my screen setup quite often (which monitors are turned on in windows, which one is the main screen and sometimes even their position relative to the others).
Every time I do this I have to re-run the configuration wizard, because the zones misalign with the actual image position.
Because I only change my screens, but not the actual order/amount of LEDs it would be convenient to be able to store the values entered in the "Zone placement" screen as defaults.
A checkbox to "Save values as defaults" would do it perfectly.
If you have the spare time, I'd be really happy for such an addition.

**Comment by zomfg** [comment]
Are profiles not enough for your use case?

**Comment by TheMcSebi** [comment]
The tiles seem to loose alignment with the position of the screens when I reenable them. I guess that's because I never drag the top monitor at its exact relative position to the main monitor in the windows settings because you can't set that as default either. Also switching default monitors seems to fuck up the id of the screen in some cases.

**Comment by zomfg** [comment]
Then you need to solve that first, [maybe with registry keys](https://superuser.com/questions/106749/what-registry-key-or-windows-file-determines-where-monitors-are-placed-in-a-mult)

**Comment by TheMcSebi** [comment]
I'v tried playing with registry and external applications before ([DisplayChanger by 12noon](https://12noon.com/?page_id=80) but kept running into issues.
I guess I'll just compile a custom build with my numbers by now.

Either way, wouldn't it make sense to store the values by default, since a taped-in-place LED setup is unlikely going to change too often? Especially compared to windows display settings...

**Comment by psieg** [comment]
That's what profiles are for, yes.
I don't see how default values help with the "screen at a different offset" problem.

What I would suggest is
* Turn off / unplug TV and create /save profile A
* Create new profile
* Turn on / plug in TV
* Set TV as primary display (to avoid the offset problem, windows should automatically switch it back if you unlug and replug)
* Configure and save profile B
* Switch profile before changing screen configuration
* To be safe, you can make the config files read-only in Windows explorer, so if you do it in the wrong order your good profiles won't be overwritten

**Comment by TheMcSebi** [comment]
Turning off my TV doesn't automatically disable the screen in Windows and I'm too lazy to unplug it every time from the back of my computer (TV HDMI ports are even less accessible). I also don't use the ambient light every time I have the TV turned on.

Having the entered values saved just like the COM-port would help my problem, since I would only need to hit "next, next, next, next, custom, next, finish" in order to re-setup my configuration.

Is there any reason against saving those values? I think many people with multiple screens could benefit from this small improvement.
