### ISSUE TITLE
LEDs are randomly flashing 

### ISSUE THREAD

**Issue by MegaVat30** [psieg/Lightpack#268]
HI all!

So have a similar problem like in [this post](https://github.com/psieg/Lightpack/issues/249). However, the image of the fix was deleted so I don't know how to fix it.
I don't have an HDR monitor and the mouse workaround didn't help. The problem occurs only in fullscreen programs and never while in watching a fullscreen video.

Video of the problem:
https://youtu.be/e0JMW3YY6oM

Photo of the unit
https://imgur.com/pt1NLQL

I'm using the original Arduino nano with the WS2812B LEDs (60 LEDs per meter, 114 in total) and the Samsung 28" UH750 UHD 4k QLED Monitor.

UPD: If I turn off the power to the unit (I have the switch for that) for several hours and turn it on again after that, the flickering will be no more. But after some time the LEDs stats flickering again.

**Comment by zomfg** [comment]
Video doesn't work

**Comment by MegaVat30** [comment]
Now you can see it.

**Comment by zomfg** [comment]
Test your strip with custom sketch (any neopixel demo code). You can also try animated moodlamps in Prismatik (RGB for ex).
Make sure your [baud rate is high enough](https://www.partsnotincluded.com/ambilight/calculating-adalight-framerate-limits/) (but not too high) and is configured on BOTH sides.

**Comment by MegaVat30** [comment]
The moodlamp is shutting off after one minute except for the last 12 LEDs which are turned off too after another 1 minute. This is because the SerialTimeout is set to 60 I guess.

Anyway, during the moodlamps mode, there is no flickering and with any test from [NeoPixel-Samples](https://github.com/scottkildall/NeoPixel-Samples) everything working fine.
I also tested LEDs with [this vido](https://www.youtube.com/watch?v=sr_vL2anfXA) without any problems.

The SerialSpeed is set to 500000 and the grab interval is set to 11ms

Will try different values tomorrow. Thanks.

**Comment by MegaVat30** [comment]
So I set the SerialSpeed 256000 and grab interval to 17ms, but I left the LEDs unplugged from the power source for the night and on the next day, I see [this](https://youtu.be/reGhSJQieng). However, no problems when I'm using the moodlamp mod or watching a video.

Turned the LED's power off for a couple of hours and after that, there was no flashing.

Also, I have noticed that when the power to the LEDs are off but the Prismatik is enabled sometimes the LEDs are randomly flashing, just one time for a second.

Will be very grateful for any tips on how I can improve my setup.

**Comment by zomfg** [comment]
> My LEDs are only connected with the data wier on the enter and the signal is traveling along with the arrows counterclockwise. The power wires are connected on both ends of the LED.

as in the only wire that goes from your Arduino to the strip is the signal one?

**Comment by MegaVat30** [comment]
On the start of the LED, I have connected 5V, Data and GR wires. The 5V and GR go to the power supply through PCB board and 1000uF capacitor and the Data go directly to Arduino through the 470ohm resistor. 

The end of the LED is connected only to the 5V and GR through PCB.

On the PCB the wiring is ![this](https://user-images.githubusercontent.com/50380576/58567413-9c135880-8232-11e9-9d3d-36c737cad983.jpg)

**Comment by zomfg** [comment]
Looking at this and the global picture, your LED "+" wires are blue AND red, and so are the "-" ones, what's up with that?

**Comment by MegaVat30** [comment]
I have connectors at the beginning of the LEDs so I could easily detach the wires in case of moving. One of the connectors is reversed in order to connect the wires from the first try. But because I forgot that with the reversing connector also I must reverse colors of the wires it led to this.

In any case, If the wiring was wrong the Meanwell power supply will not start and will not power up the LEDs.

**Comment by zomfg** [comment]
If you leave the device ON, but unplug the USB, does it still randomly flash?
Try with something else, like Ambibox to narrow it down to software/hardware issue.
Try unplugging the green ground wire from the negative rail.

**Comment by MegaVat30** [comment]
> If you leave the device ON, but unplug the USB, does it still randomly flash?
No. It just sits with the last colors that the LEDs was on at the moment. No flashing or random color changing.
If I cut the power with unplugged USB and power it up again the LEDs will continue to shine with the same colors as before until I replug the USB and restart the app.
> Try with something else, like Ambibox to narrow it down to software/hardware issue.
With the Ambibox the issue is still there so this means that the problem is not with Prismatik.
> Try unplugging the green ground wire from the negative rail.
The issue is still there.

So because the problem is not with the software and rather with the hardware or Arduino sketch (I already tried another sketch with no luck.), I'll close this ticket. 

Anyway, thank you for your help. I will post the solution to my problem if I'll found one.

**Comment by MegaVat30** [comment]
I'm posting this comment as I promised. After months of search, I decided to completely replace the wiring from LEDs to the controller and also replace all LED strips on the monitor. And It worked!

Apparently, in my case, I had some faulty LED strips, so replacing them solved the issue.
