### ISSUE TITLE
Unable to Run build-deb.sh

### ISSUE THREAD

**Issue by phillipshreves** [psieg/Lightpack#269]
When trying to run build-deb.sh, it returns this:
`sh build-deb.sh`
`usage: build-deb.sh <arch>`
Is it looking for another argument? What is "arch" referring to?

**Comment by psieg** [comment]
arch is short for architecture, referring to the CPU architecture. These days the most common architecture is amd64 for 64-bit systems. While the name is AMD this includes most Intel CPUs.
