### ISSUE TITLE
LED's don't turn on all at once at start Prismatik

### ISSUE THREAD

**Issue by Kas152** [psieg/Lightpack#270]
Hi,
I have had a small issue for a while now. It is like this: when I start up Pirmatik not all the connected LED's (191) turn on. Only ervery 5 turn on or so, and this goes only for the top and the bottom of the screen, the sides are started up correctly. I have to open the program and then select the option to show all LED's either in color or in white and then all the LED's are working properly. I tried the orgininal Prismatik program from Lightpack, and then the issue is not there.. I also tried different baudrates with no effect, currently I'm running 2000000 in Prismatik. Changing the baudrate in the code from the Arduino made also no diffirence. Prismatic is using Win8 desktop duplication and DX hooking is turned off as I didn't notice any improvement.  This is my setup:

Windows 10 64x
8GB memory
Intel HD Graphics 4600/ Nvidia Geforce GTX 850M (for some reason Prismatik doesn't work with this one so I use the first one)
Arduino Pro Micro with atmega32u4 processor with 191 LED's WS2812B LEDstrip

Anyone an idea how to solve this? Many thanks in advance!

**Comment by Kas152** [comment]
No one? @psieg maybe?

**Comment by psieg** [comment]
So after you do this color zone thingy all zones work properly (and change their color according to the screen content)?
Does it work if you use the static color or moodlight mode?

**Comment by Kas152** [comment]
Hi Patrick!
Many thanks for the reply! And of course for the trouble you take in supporting this program and for forking it.
I tried with the other modes (static color and moodlight), and no problems there. And yes after turning on and off the grabwidgets everything work as it’s supposed to. So it’s a minor glitch but still annoying when rebooting the pc.
Cheers!

Van: Patrick Siegler <notifications@github.com>
Verzonden: donderdag 18 juli 2019 21:05
Aan: psieg/Lightpack <Lightpack@noreply.github.com>
CC: Kas152 <kasper_heddes@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [psieg/Lightpack] LED's don't turn on all at once at start Prismatik (#270)


So after you do this color zone thingy all zones work properly (and change their color according to the screen content)?
Does it work if you use the static color or moodlight mode?

**Comment by psieg** [comment]
That's really weird.
Does simply restarting Prismatik fix it?
If you set a static color to full white that does not help? Because that's kind of what the other thing does...

**Comment by Kas152** [comment]
No unfortunately it does not.  I tried everything possible.  Restarting program, restarting Windows,  reinstalling program, upgrading to Windows 10, different baudrate, setting up a new profile,  you name it..  That's why I came to you.  And considering it doesn't happen with the original build from light pack I got to the conclusion it has to have something to do with your fork..  Anyhow, I can make a log of you want,  would that help?

BTW,  when using the setting average on all LEDs, the issue also does not occur.  But when turning the setting off it goes back to only a few LEDs on.

So the only way I know of now get the program working is to turn the widgets in and off.  Everything else fails to fix permanently the issue when using screen grabbing.

Oh yes,  the static color, when using that all the LEDs turn on but when goin back to screen grabbing I have to turn the widgets in and off before it works. It's like as if they are not recognized at first.
________________________________

**Comment by Kas152** [comment]
Oh yes,  I just discovered that when using winapi option for grabbing, that the LEDs do turn on all at the start.  But this option makes my whole laptop laggy as hell..  Hope this helps.
________________________________

**Comment by psieg** [comment]
I don't have an idea so far.
Does it change if you use a different grab delay (on DDupl)?

**Comment by Kas152** [comment]
I assume you mean the grabinterval in miliseconds? That makes also no diffirence.

Van: Patrick Siegler <notifications@github.com>
Verzonden: zondag 28 juli 2019 19:07
Aan: psieg/Lightpack <Lightpack@noreply.github.com>
CC: Kas152 <kasper_heddes@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [psieg/Lightpack] LED's don't turn on all at once at start Prismatik (#270)


I don't have an idea so far.
Does it change if you use a different grab delay (on DDupl)?

**Comment by NickKorobos** [comment]
Hi, i am having the same problem. When i launch prismatik. The first half row of the bottom screen (approximately 54 leds) do not react to screen grabbing. After that, they work normally. To make them work, i also have enable the colored or white widgets and then disable them.
I think it has to do something with the initial offset value i set during setup (54 value). But when i look into the .ini profile i created, all tge leds have the correct X and Y axis.
I can provide my main.conf and profile.ini files if the can be of use.

I am using 268 WS2815 leds in total, 164 of them enabled at the moment.
Windows 10 64 bit
16GB Ram
Nvidia 1070 ti
Arduino Nano  with atmega328p processor.

**Comment by Kas152** [comment]
@psieg many big thanks for your latest release!!! This fixed the above mentioned issue :-). I dont know what you did, but it worked! I will close the thread now.
