### ISSUE TITLE
Compile for Windows doesn't communicate with USB

### ISSUE THREAD

**Issue by tooljose88** [psieg/Lightpack#276]
When I compile for Windows with Visual Studio 2019 and QT Creator the compile it's successfully, but when I execute the program, the Leds turn on automatically with MoodLamp effect, despite the Prismatik is Turned off.

When I press the button for turn on the lights with Ambilight effect nothing happens, the DirectX  its working because with WLED and UDP communication (with a plugin)  it's working normally. Only turn on the lights at start with the moodlamp color although the effect it's disabled and the lights off, and I can't do anything.

With the releases I have no problems, and Linux version that I have compiled is working. The versions that I'm using are QTCreator 4.10, VStudio 2019, msvc2017_64 and Qt 5.13.1.

**Comment by psieg** [comment]
Normally, prismatik will turn on the lights when started, so the button should be "lights off" not "lights on" at the start.
Did you try running without the debugger attached?
Make sure there's no other instance of prismatik somewhere.

**Comment by tooljose88** [comment]
Yes, I tried without debugger. And there's no other instance running in Task Manager.
Even so, I close the issue because with your compilation there are no problems, and I have already given up trying. Thanks
