### ISSUE TITLE
high memory usage Prismatik

### ISSUE THREAD

**Issue by Kas152** [psieg/Lightpack#277]
Hi,
After running for some time (can be a few days or an hour..), Prismatik starts using absurd amounts of memory. Any ideas what this could be? Many thanks in advance!

Asus N751JK
Windows 10 Pro
Intel® Core™ i7 - 4710HQ Processor
16GB Ram
Integrated Intel® HD Graphics 4600
NVIDIA® GeForce® GTX850M

![Naamloos](https://user-images.githubusercontent.com/52101139/66409596-13cb6e00-e9f1-11e9-9f24-5068f3369b9d.png)

**Comment by psieg** [comment]
That is definitely an absurd amount. Do you have logging enabled? Did you change any settings besides LED arrangement etc?

**Comment by Kas152** [comment]
No, logging is not enabled. And I did not change anything for the rest. Except I upgraded my ram memory from 8 to 16 gb.. So that makes it even stranger.
________________________________

**Comment by psieg** [comment]
Is there an error in the logs? C:\Users\You\Prismatik\

Could you try narrowing it down, i.e. if you use only moodlamp, does it happen? only screengrab?
What if you keep the lights off?

Also, which device are you using?

**Comment by Asryan2a** [comment]
I have the same issue but with ambibox, I would prefer Prismatik but moodlamp is not staying on :(

**Comment by h7896v7347** [comment]
>I have the same issue but with ambibox
Me too. For long time.
@psieg this problem appeared after windows update a few months ago. At the same time prismatic and f.lux memory usage spikes. ( https://forum.justgetflux.com/topic/6985/memory-leak-with-f-lux-4-100-and-windows-10-version-1903/22 )

For me its over 5-10GB after full day. (Working set ~1-2GB and declared memory > 5-10GB)
And it cause heavy writes to pagefile.sys
For now i use task scheduler to restart Prismatic every hour to save SSD writes.

**Comment by zomfg** [comment]
So if it's a gamma ramp leak, one workaround would be switching to Night Light (until it's fixed at least) since it doesn't use gamma tables and thus Prismatik won't either.

**Comment by psieg** [comment]
I don't think we can do anything about the leak inside the API. We reduced the frequency of calls, please report back if you're still experiencing excessive amounts.
