### ISSUE TITLE
dual monitor setup

### ISSUE THREAD

**Issue by CC192** [psieg/Lightpack#281]
Hi there, first  I have to thank for the great job you do here!!

I am trying to set up a dual monitor ambilight setup. I got the following setup:

- w2812b LEDs with 144 LED/m
- 5v 40A PSU
- both screens 1080p, one is 22" the other one is 24"
- 2 arduino nanos, each hooked up to one screen (both on Data6)

The software works great with each screen by itself but I cannot figure out how to set them up to work simultaneously? Is there a way to achieve that with the Prismatic software?
I tried to run two versions of prismatic installed on two different drives, but that did not work (as expected)

**Comment by zell2311** [comment]
I've managed to run two prismatic instances on the same machine.
1. Create a second user
2. Get Prismatik to work under second user being set up to manage the second display's LEDs
3. Log out, log in as the first user
4. Run first instance of Prismatik as usual
5. Holding Shift press the right mouse button on the Prismatik and click Run As...
6. Enter credentials for the second user
That worked for me.

**Comment by psieg** [comment]
Can you give details on why a single Prismatik instance doesn't work for you? Is it because of two screens or because you have two devices?

AFAIK two screens aren't a problem, but I think Prismatik handles only one device at a time (except Lightpack devices)

**Comment by CC192** [comment]
I have 2 screens which I did not combine in resolution (2* 1920x1080Px) I could do both screens off that one Nano, if I did combine the 2 screens into one virtual screen, but then some of my software got problems scaling (work related software)

Since I am not familiar with coding that much I only had an Arduino code for a nano to control one screen off it at a time. I wouldn't know how to program it, so it gives out 2 signals (would the baud rate even manage to do so? I have 233 LEDs in the left and 210Leds on the right screen atm)

**Comment by psieg** [comment]
I still don't understand why you can't have all LEDs "in one strip" and have your zones spread across monitors.
