### ISSUE TITLE
Prismatik doesnt start

### ISSUE THREAD

**Issue by rodlessa** [psieg/Lightpack#285]
Not really sure what happened was working fine but Prismatik just crashed and i cant start now, whenever i try to start via bash returns this:

```
19:23:23:915 Warning: Fail load translation for locale "en_US" pathToLocale ":/translations/en_US"
19:23:23:928 Warning: QObject::connect: No such slot LedDeviceLightpack::ledDeviceUpdateWBAdjustments() in LedDeviceManager.cpp:497
19:23:23:932 Fatal: ASSERT: "highest > 0" in file /usr/include/qt/QtCore/qrandom.h, line 133
```
I tried deleting the main.conf file and running again, but after setting up the leds and colors when the process is finished prismatik just crashed.

**EDIT: Seems the i was able to do a small workaround, used the main branch on aur to install prismatik (i was using the git version) after that i did a new profile, while setting things up as soon as i enabled "Apply color temperature and gamma" the error returned, i did a new profile again without the option restart the pc a few times and was working just fine.**

**Comment by zomfg** [comment]
Were you using exclusively screen capture?
Which Qt version do you have?
