### ISSUE TITLE
Dont Work on Win 10 

### ISSUE THREAD

**Issue by LazarusCRY** [psieg/Lightpack#29]
Hello , first of all I thank you for your work . Unfortunately for Windows 10 64BIT funziana alone while I view the desktop . Sesposto a white window around the screen , the LEDs change color properly . If I watch a fil ( youtube or player ) does not move anything and remain white . The same with the games Battlefield , Counterstrike , The Division etc.
Solutions ? 
I attached my settings
Thank you very much
![screenshot_173](https://cloud.githubusercontent.com/assets/17770401/13681614/47f35c96-e6fe-11e5-9ab4-670b9ba85f6f.jpg)
![screenshot_174](https://cloud.githubusercontent.com/assets/17770401/13681615/47f96c3a-e6fe-11e5-8d6a-41ea015e3c5c.jpg)

**Comment by psieg** [comment]
* The lights match your desktop background and windows in normal operation
* When you play a movie on youtube (fullscreen) the lights go white.
  * Which browser are you using?
* When you play a movie through a player (fullscreen) the lights go white.
  * Which player are you using?
* Does not work in games
  * Is DirectX grabbing enabled (under experimental)? Are you running as admin?

**Comment by LazarusCRY** [comment]
-Chrome
-VLC
-DirectX grabbling disable 
-Run as Admin

**Comment by Tobias-De** [comment]
Maybe your Zones are broken? That can happen if you have multiple Monitors.(happened to me 3 times with the original prismatik software)

**Comment by LazarusCRY** [comment]
I have a 34" 21:9 Gaming IPS Gaming monitor in Display Port 1.2.
R9 390x video card

**Comment by LazarusCRY** [comment]
![image](https://cloud.githubusercontent.com/assets/17770401/13700826/a83dfb30-e783-11e5-9f78-7041b877f8d1.jpeg)

**Comment by Tobias-De** [comment]
So you say: you play direct x games and direct x hooking is disabled.. no Wonder its not working as expected. 
Enable Direct X hooking and try again.

**Comment by psieg** [comment]
Okay, there is something weird going on here.
* Normal grabbing works, but VLC and Chrome fullscreen, both of which do not run in fullscreen exclusive mode, don't work. Can you provide a logfile for a that situation? Please start Prismatik, then switch to chrome and run the video fullscreen, then close prismatik and post the log created at `C:\Users\You\Prismatik\Logs\Prismatik.0.log`
* Game grabbing does not seem to work -> check to make sure it is active, enable experimental settings and check the DX grabbing checkbox

**Comment by LazarusCRY** [comment]
Ok, this is log after play a video in Chrome
[Prismatik.0a.txt](https://github.com/psieg/Lightpack/files/170908/Prismatik.0a.txt)

**Comment by LazarusCRY** [comment]
T|his settings..and no works on game ( dx11 game)
![screenshot_177](https://cloud.githubusercontent.com/assets/17770401/13728152/f4f21eb6-e90e-11e5-9a21-251da68f11ee.jpg)

**Comment by psieg** [comment]
I'm not sure why it doesn't work with WinAPI, but just set the capture source to Win8 Desktop Duplication, then it should work

**Comment by psieg** [comment]
Inspired from [this reddit post](https://www.reddit.com/r/Lightpack/comments/4apbf6/not_working_in_kodi/), you can also try turning down the gamma correction, that might help

**Comment by psieg** [comment]
@LazarusCRY Any update on this? Does any of the above work?

**Comment by LazarusCRY** [comment]
Ok, set for long time To reply. Noè work fine : setting Lumonosity ti Dark Zone and work fine. Change The usb port directly in the PC( not in usb hub) .
This is video ( The orange Wallis not right for The colors;)) Thx for support.
https://drive.google.com/open?id=0B4B8e7nFC34xSDMxZml5M01rdk0

**Comment by psieg** [comment]
Nice setup. Indeed the orange walls mess up the colors, but dark/light still works nicely

Glad to help ;)
