### ISSUE TITLE
Feature request: UDP protocol support

### ISSUE THREAD

**Issue by ruddy17** [psieg/Lightpack#297]
I plan to do a room-scale led setup. Serial over USB is a poor option with my application, as the cable has to be routed accross the whole room. I would like Prismatik to support a device protocol to transmit data to ESP controller wirelessly. I would propose to adopt one (or all) of the protocols from here: [https://github.com/Aircoookie/WLED/wiki/E1.31-&-UDP-Realtime-Control](url)

**Comment by zomfg** [comment]
my 2 cents: a tethered ESP running a serial/adalight-to-UDP/WLED conversion and sending it to another ESP will get you there quicker imo

**Comment by Tom-Archer** [comment]
I forked this repo to do just that. I'm outputting over a UDP socket so that I can run a local Python script to control a Pimoroni Mote without needing a device in the middle.

**Comment by psieg** [comment]
Should be fixed since #305 :)
