### ISSUE TITLE
Multiple Colors on different sides of the monitor / Hotkeys?

### ISSUE THREAD

**Issue by HighOnBuffs** [psieg/Lightpack#306]
Hi i love Prismatik but the software is pretty limiting when it comes to options. 
How can i simply say for example, one side of the screen shows pink static lights while the other does red? Also is there a way to place hotkeys to switch from ambient to static for example?
Thanks!

**Comment by zomfg** [comment]
This is not exactly built-in, but both are doable. Here's how to achieve it (on Windows):

This involves enabling API server in Prismatik and using a little program called AutoHotKey.

In **Prismatik**:
1. enable "Expert mode" in "Profiles" tab
2. enable server in "Experimental" tab
    * then uncheck "listen only on local interface" if you want to control it from other computers
    * leave Key empty
3. (optional) to see command list available in your Prismatik version, in a command prompt type `telnet localhost 3636` (your Prismatik PC address and port from "experimental" tab)
    * you should see "Lightpack...." something something
    * type "help"


Now, **AutoHotKey** (this allows you doing all kinds of crazy things and bind them to, well, hotkeys)
1. [Download](https://www.autohotkey.com/) (I used "Current version", and when asked, "unicode 64")
2. put [this script](https://gist.github.com/zomfg/e93e4e7381e34d5a96e305768d550c39) in a folder of your choice
3. put [this script](https://gist.github.com/zomfg/59908f5c9baf04c9c7abdc8b1f70a2f6) in the same folder
4. open the latter with notepad or whatever, and change this part
```
; Prismatik machine's IP
global PRISMATIK_IP="192.168.1.20"
; port from Experimental tab
global PRISMATIK_PORT=3636
```
5. right click on the same file, "Run Script"

Now, in theory, pressing `Ctrl+1` should do the pink/red thing.
You can re-bind whatever keys you want, you can implement your own things from Prismatik API, as a bonus example I included a profile change on `Ctrl+2`. Look through `prismatik.ahk` file, it should be easy enough to customise for simple use cases combined with help from step 3. in Prismatik part (you can assign a color to each LED if you wish so).

**Caveat**: as of right now, the static color part seems to be breaking other animated modes until you restart Prismatik (I'll look into that). For other modes you can make profiles, bind them and switch between them (until you set the color).

**Comment by HighOnBuffs** [comment]
Amazing, thanks for the detailed answer! I will try all this over the next
few days!
I really love the tool and there is really nothing like it.
Hope you have a great weekend!

Am Sa., 15. Feb. 2020 um 15:53 Uhr schrieb Sergio <notifications@github.com

**Comment by HighOnBuffs** [comment]
So i tried it but when i want to lauch the ahk script it tells me:
"Error at line 7.
#include file .../socket.ahk cant be opened"
So i renamed the first file in socket.ahk thinking it would probably work with that and after that it started but ctr+1 doesnt work for me. 

What did you mean with change that part?:
`;` Prismatik machine's IP
global PRISMATIK_IP="192.168.1.20"
; port from Experimental tab
global `PRISMATIK_PORT=3636`

I tried setting the IP my prismatik tells me under local interface?
When i telnet localhost 3636 it tells me telnet is not a recognized command.
Any chance you could explain further what i need to change exactly?

Thanks so much i can see this being great when i get this working!

**Comment by zomfg** [comment]
Try [this version](https://gist.github.com/zomfg/59908f5c9baf04c9c7abdc8b1f70a2f6) (you'll need to right click and "Run")
It should create `prismatik.log` file in the same directory as the `.ahk` file when you press your key combos, post it here

Telnet part isn't required for this, but [you can enable it](https://social.technet.microsoft.com/wiki/contents/articles/38433.windows-10-enabling-telnet-client.aspx)

**Comment by zomfg** [comment]
@psieg There's some hotkey code in the settings, but not in the UI/conf files, any idea what's the history there?

**Comment by HighOnBuffs** [comment]
https://pastebin.com/4gTk4qqW

Is what i got from the log file. Thanks so muc for taking the time and helping me out!

**Comment by zomfg** [comment]
[New version](https://gist.github.com/zomfg/59908f5c9baf04c9c7abdc8b1f70a2f6)
If that works, change `True` to `False` here to stop logging (if you care about that)
```
global LOG_DEBUG:=True
```

**Comment by HighOnBuffs** [comment]
Awesome this worked! Thank you so much!

Is it possible to have an even 3 way light as well? Like left side right side middle side?

Oh and for some reason when i change the hotkeys to Alt+Ctrl+1 it doesnt seem to work.
Does AHK have problems with tripple inputs?

**Comment by zomfg** [comment]
[Another update](https://gist.github.com/zomfg/59908f5c9baf04c9c7abdc8b1f70a2f6): you can add any number of colors, you can do 1 per LED if you want

`Alt+Ctrl+1` works for me with `^!1::`

**Comment by HighOnBuffs** [comment]
Amazing it works flawless also the hotkeys!
I cant thank you enough! That was the most competent and flawless problem solving ive encountered in a long time!
Hope you have a wonderful week, you are awesome! 💯

**Comment by HighOnBuffs** [comment]
Hi quick question: I started using a VPN recently and eventhough i whitelisted AHK and Prismatik the hotkeys stoped working when running the VPN saying "failed to connect".
Is there a way around that or do i need to whitelist something else?
Thanks in advance!

**Comment by zomfg** [comment]
something like a NordVPN?
what does you [ipconfig](https://www.howtogeek.com/168896/10-useful-windows-commands-you-should-know/) look like?
are AHK and Prismatik on same PC? which IP did you put in AHK script?

**Comment by HighOnBuffs** [comment]
Yeah something like that.
IPconfig shows a different adress as im using a VPN.
I thought it would work just white listening Prismatik and AHK but that
doesnt seem to help.
Yeah they are on the same PC. I put in the right adress of my local
machine. Without VPN on it works flawless.

Am Mo., 2. März 2020 um 19:13 Uhr schrieb Sergio <notifications@github.com>:

**Comment by HighOnBuffs** [comment]
Hi got it to work when typing ipconfig i used the ip4 adress shown from my fritzbox.
Hope it doesnt make the VPN useless but all good for now!

**Comment by HighOnBuffs** [comment]
Hi i remembered you helping me so much it blew my mind with this!
Thanks so much again! I recently switched or rather planning of switching at least partly to Arch Linux and was thinking ok Prismatic exists for linux but how do i use the AHK script on Linux to control my LEDs via hotkeys?

Is there an easy way to use my 2 control scripts on linux or convert them?

`#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
#SingleInstance, force
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

#Include, .\Socket.ahk ; https://gist.github.com/zomfg/e93e4e7381e34d5a96e305768d550c39

; in Prismatik
; go to Profiles, check "Expert mode"
; go to Experimental, check "enable server"
; uncheck "listen only on local interface" if you want to control it from other computers
; leave Key empty

; Prismatik machine's IP ipconfig IPv4
global PRISMATIK_IP:="192.168.200.80"
; port from Experimental tab
global PRISMATIK_PORT:=3636

global LOG_DEBUG:=False

LogToFile(action, msg)
{
	if LOG_DEBUG
		FileAppend, % action . " : " . RTrim(msg, " `r`n") . "`n", .\prismatik.log
}
SendCmd(tcp, action, cmd)
{
	LogToFile(action, cmd)
	tcp.sendText(cmd)
	resp:=RTrim(tcp.recvText(), " `r`n")
	LogToFile(action, resp)
	Return resp
}

SwitchProfile(ProfileName)
{
	myTcp := new SocketTCP()
	if (myTcp.connect(PRISMATIK_IP, PRISMATIK_PORT) = 0)
	{
		Msg:="Failed to connect to " . PRISMATIK_IP . ":" . PRISMATIK_PORT
		LogToFile("profile switch", Msg)
		MsgBox, % Msg
		Return
	}
	LogToFile("profile switch", myTcp.recvText())

	Cmd:="lock`n"
	SendCmd(myTcp, "profile switch", Cmd)

	Cmd:="setpersistonunlock:off`n"
	SendCmd(myTcp, "profile switch", Cmd)

	Cmd:="setprofile:" . ProfileName . "`n"
	if (SendCmd(myTcp, "profile switch", Cmd) = "error")
		MsgBox, % "Could not set profile " . ProfileName . ". Edit prismatik.ahk to contain an existing profile."

	Cmd:="unlock`n"
	SendCmd(myTcp, "profile switch", Cmd)

	Cmd:="exit`n"
	SendCmd(myTcp, "profile switch", Cmd)

	myTcp.disconnect()

	Return
}

SetColors(Colors)
{
	myTcp := new SocketTCP()
	if (myTcp.connect(PRISMATIK_IP, PRISMATIK_PORT) = 0)
	{
		Msg:="Failed to connect to " . PRISMATIK_IP . ":" . PRISMATIK_PORT
		LogToFile("static color", Msg)
		MsgBox, % Msg
		Return
	}
	LogToFile("static color", myTcp.recvText())

	Cmd:="getcountleds`n"
	Result:=SendCmd(myTcp, "static color", Cmd)
	LedCount:=SubStr(Result, InStr(Result, ":") + 1)
	LedCount+=0
	if (LedCount < 1)
	{
		MsgBox, "found zero LEDs"
		Return
	}

	Cmd:="lock`n"
	SendCmd(myTcp, "static color", Cmd)

	Cmd:="newprofile:autohotkey`n"
	SendCmd(myTcp, "static color", Cmd)

	Cmd:="setpersistonunlock:on`n"
	SendCmd(myTcp, "static color", Cmd)

	Cmd:="setstatus:on`n"
	SendCmd(myTcp, "static color", Cmd)

	LedColors  := ""
	LedsPerColor:=Ceil(LedCount / Colors.MaxIndex())
	for colorIndex, color in Colors
	{
		Loop % LedsPerColor
		{
			LedIndex:= A_Index + (colorIndex - 1) * LedsPerColor
			if (LedIndex <= LedCount)
				LedColors  := LedColors  . Format("{:i}-{};" , LedIndex, color)
		}
	}

	Cmd:="setcolor:" . LedColors . "`n"
	SendCmd(myTcp, "static color", Cmd)

	Cmd:="unlock`n"
	SendCmd(myTcp, "static color", Cmd)

	Cmd:="exit`n"
	SendCmd(myTcp, "static color", Cmd)

	myTcp.disconnect()

	Return
}

; For keys
; see https://www.autohotkey.com/docs/Hotkeys.htm
; and https://www.autohotkey.com/docs/KeyList.htm

; set a predefined profile
; Ctrl+1 = ^1::
; Alt+Ctrl+1
^!1::
; change "Lightpack" to desired profile name
SwitchProfile("Flo")
Return

; set a predefined profile
; Ctrl+2 = ^2::
; Alt+Ctrl+2
^!2::
; change "Lightpack" to desired profile name
SwitchProfile("Letterbox")
Return

; Set static colors
; Ctrl+3 = ^3::
; Alt+Ctrl+3
^!3::
; Add any number of colors to the list (don't go over your led count)
; the led strip will be split in equal-ish parts with respctive colors ["color","color"]
Colors:=["199,21,254","255,0,0"] 
SetColors(Colors)
Return

; Set static colors
; Ctrl+4 = ^4::
; Alt+Ctrl+4
^!4::
; Add any number of colors to the list (don't go over your led count)
; the led strip will be split in equal-ish parts with respctive colors ["color","color"]
Colors:=["250,126,30","190,21,255"] 
SetColors(Colors)
Return

; Set static colors
; Ctrl+5 = ^5::
; Alt+Ctrl+5
^!5::
; Add any number of colors to the list (don't go over your led count)
; the led strip will be split in equal-ish parts with respctive colors ["color","color"]
Colors:=["190,21,255"] 
SetColors(Colors)
Return

; Set static colors
; Ctrl+6 = ^6::
; Alt+Ctrl+6
^!6::
; Add any number of colors to the list (don't go over your led count)
; the led strip will be split in equal-ish parts with respctive colors ["color","color"]
Colors:=["250,126,30"] 
SetColors(Colors)
Return

; Set static colors
; Ctrl+7 = ^7::
; Alt+Ctrl+7
^!7::
; Add any number of colors to the list (don't go over your led count)
; the led strip will be split in equal-ish parts with respctive colors ["color","color"]
Colors:=["199,21,254","250,126,30"] 
SetColors(Colors)
Return

; set a predefined profile
; Ctrl+0 = ^0::
; Alt+Ctrl+0
^!0::
; change "Lightpack" to desired profile name
SwitchProfile("Off")
Return`

Thankful for any advise!

**Comment by zomfg** [comment]
I'm not sure there's a direct way to use ahk scripts, I'll let you do more research
but on linux you can easily bind your keys to execute whatever you want (either through your DE/WM or something like [sxhkd](https://wiki.archlinux.org/index.php/Sxhkd))
so if there's no way to run ahk scripts directly, you could invoke, for example, python scripts that talk to prismatik
see examples [here](https://github.com/psieg/Lightpack/tree/master/Software/apiexamples/pyLightpack)
`lightpack.py` takes care of most of the things, you'll just need another script that changes profiles etc and bind keys to that one

**Comment by minhluan259** [comment]
@zomfg Can we have hotkey for setmode (Screen grabbing / Mood lamp / Sound visualization) and turn light ON/OFF ?

**Comment by zomfg** [comment]
I updated the [gist](https://gist.github.com/zomfg/59908f5c9baf04c9c7abdc8b1f70a2f6)
while  you can send those commands on their own, you can achieve the same thing with profiles (one with screen grab, one moodlamp A, one modlamp B, etc) and just flip between those

**Comment by minhluan259** [comment]
@zomfg thank you so much for update.
Can we get current status / mode and make hotkey as toggle?

**Comment by Talesowy** [comment]
Fantastic work! But I have issue: leds are disabled after +/- 40 sec when I switch profile to ctrl+1 What I'm doing wrong?

**Comment by zomfg** [comment]
if that switches to a static color your firmware probably times out, you can try unchecking "send data only if changed"
