### ISSUE TITLE
Memory leaking

### ISSUE THREAD

**Issue by tonisk** [psieg/Lightpack#308]
Noticed that Prismatik has started leaking memory. Was using well over 6GB ram. I killed it and restarted my machine, upgraded Prismatik, but it's still steadily leaking. Similar thing #271 was happening a year or so ago also, but it went away after I reinstalled windows for some other reason. Now it's back again. I think it started also after a windows update. I think this issue #277 has same problem.

https://imgur.com/RVeUh0O

Prismatik unofficial 5.11.2.21
Windows 10.0.18363.657

**Comment by zomfg** [comment]
are you using f.lux or equivalent and have it enabled in Prismatik?
![image](https://user-images.githubusercontent.com/239811/75378569-37c21a00-58d4-11ea-863e-65df67bd5dca.png)

**Comment by tonisk** [comment]
I don't use f.lux, but I have enabled the windows 10 night light, this has worked without any issues before. 
This checkbox is unchecked in in prismatik.

**Comment by tonisk** [comment]
Turned off windows night light and restarted Prismatik. 
Still leaking

**Comment by zomfg** [comment]
So it's not related to #277 hmmm..
is it happening in every mode? (moodlamp, screencapture..)

**Comment by tonisk** [comment]
Let me check.

Ran mood lamp for 5 minutes - no leaks so far.

I have 2 screen grabbing profiles, one with smaller and other with bigger areas.
The one with bigger areas is leaking much faster.

**Comment by zomfg** [comment]
Can you show your Mode and Experimental tabs please
How many leds do you have?

**Comment by tonisk** [comment]
Images of requested tabs https://imgur.com/a/XVypTer
I did not have Experimental turned on before.
I have 104 leds

**Comment by zomfg** [comment]
if you check "send data only if changed" in experimental, does it slow down the leak?

**Comment by tonisk** [comment]
It slows it down considerably if nothing is happening on the screen, but if I move windows or play a movie, it jumps up again.
(did not know about pasting images here)

**Comment by tonisk** [comment]
But even if I have "send data only if changed" turned off, and nothing is changing on the screen, leaking also goes down.
Seems that leaking is depending on the current grab frequency instead

**Comment by raxixor** [comment]
I've also got this problem. Doubled in private bytes used after around 24 hours, screen set up with lighting is sometimes a Wallpaper Engine visualizer/clock, other times videos, browsing, etc.

**Comment by zomfg** [comment]
This is my 2 hour run with videos and other active usage
![image](https://user-images.githubusercontent.com/239811/75604905-dbcae180-5add-11ea-87d2-8841a90c2de8.png)
the bump in the end was from me opening the settings window and displaying capture widgets
"Send data only if colors changed" was unchecked
This is a .21 that I manually installed over .19

**Comment by zomfg** [comment]
10 hours
![image](https://user-images.githubusercontent.com/239811/75612203-b5c73080-5b21-11ea-8590-97c8889ef6ca.png)

Try looking through your logs for `DDupl` in case there are some errors
Try WinAPI grabber to narrow it down to DDupl (or not)

**Comment by tonisk** [comment]
I don't seem to have logs in C:\Users\<user>\Prismatik
How do I get WinAPI grabber?

**Comment by zomfg** [comment]
Both are here
![image](https://user-images.githubusercontent.com/239811/75612637-c679a580-5b25-11ea-95d0-5f8c51f2a541.png)
set level to 1

So first session: keep DDupl and do the logging
Second: restart Prismatik, switch to WinAPI
monitor memory for both

**Comment by tonisk** [comment]
First session: 
Using this profile [Film.zip](https://github.com/psieg/Lightpack/files/4270795/Film.zip)
Nothing new added to log after startup, leaking memory

![image](https://user-images.githubusercontent.com/4385413/75613416-2710de80-5b36-11ea-8811-b553067c34f8.png)

**Comment by tonisk** [comment]
Secon session:
Same profile
Nothing new added to log after startup, leaking even faster

![image](https://user-images.githubusercontent.com/4385413/75613461-a1416300-5b36-11ea-8f6a-227e45bf7e31.png)

**Comment by tonisk** [comment]
Log files for both runs
[Logs.zip](https://github.com/psieg/Lightpack/files/4270803/Logs.zip)

**Comment by tonisk** [comment]
Also, what I've noticed, this other profile is not leaking nearly as much 
[Standard.zip](https://github.com/psieg/Lightpack/files/4270814/Standard.zip)

**Comment by zomfg** [comment]
"Film" has
![image](https://user-images.githubusercontent.com/239811/75614087-507d3a80-5b35-11ea-892e-4344152081cf.png)
checked, which is, indeed, related to #277, uncheck it.

Does "Standard" leak indefinitely too? or does it stabilize at some point?

**Comment by tonisk** [comment]
Good catch, not even sure how this got enabled there. Turned it off and it's leaking much less.
"standard" leaks too, but slowly ~100kB/min

**Comment by zomfg** [comment]
What's your baud rate?

here's your "Standard" profile over 20 min @ 60fps (to amplify the effect) and 9600 baud rate
![image](https://user-images.githubusercontent.com/239811/75626224-1dcf5280-5bc6-11ea-92df-68c40dfaef52.png)

same thing with 500k baud rate
![image](https://user-images.githubusercontent.com/239811/75626242-393a5d80-5bc6-11ea-9da7-249aedb4f89d.png)

This might be a Qt problem and/or the way the serial writes are handled in low baud rate situations.
Try upping your baud rate

**Comment by tonisk** [comment]
I modified my arduino to use 460800 since the beginning

**Comment by zomfg** [comment]
Run [this build](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_test_log_build.zip) with logs @ 1, post them here

**Comment by tonisk** [comment]
Leaking very slowly

Repeating line:
Debug: bool __cdecl LedDeviceAdalight::writeBuffer(const class QByteArray &) bytesToWrite: 0

[Prismatik.0.log.zip](https://github.com/psieg/Lightpack/files/4275703/Prismatik.0.log.zip)

**Comment by zomfg** [comment]
leaking at same rate as before?

**Comment by tonisk** [comment]
I think it was the same. But I give it a comparison run

**Comment by tonisk** [comment]
build 5.11.2.21
![1](https://user-images.githubusercontent.com/4385413/75702746-bc3edf00-5cbe-11ea-841b-d2b4c07dea4f.PNG)

test_log build
![2](https://user-images.githubusercontent.com/4385413/75702759-c365ed00-5cbe-11ea-9bcb-49351115ab87.PNG)

**Comment by x-trend1** [comment]
> Вы используете f.lux или его эквивалент, и он включен в Prismatik?
> ![образ](https://user-images.githubusercontent.com/239811/75378569-37c21a00-58d4-11ea-863e-65df67bd5dca.png)

Can you solve this problem?

**Comment by Joeri87** [comment]
For some month's I was trying to figure out why my memory kept filling up really bad (I have 32GB ram, Intel Core i5 4670K and Intel Z87 chipset running windows 10 1910. I first noticed updating from windows 10 1810 to 1910 and tought it was the windows upgrade. Lightpack had in process manager some ram used, lik 700MB's but my whole ram would be used invisible. I did a clean install and for months it bothered me. I upgraded my ram from 16 to 32 GB and blamed windows 10. Then a week back I noticed suddenly Prismatik was using 4GB! of ram. I closed the processes and 31GB ram used dropped to only 4 GB of ram used in total. After googeling I found this thread. I have no Idea since which version of Lightpack this has happened, but you guys really have a serious bug introduced in this software!!!
I really love the Lightpack and I was very happy support was continued here, but now I have to kill the process every day and restart it. With me it uses about 12GB of ram per day....

**Comment by zomfg** [comment]
and do you have "Apply screen color modifications" on? and does it leak without?
I have the same config except for the gpu (amd) and can't reproduce
what might help is you going back to a very old version like 5.11.2.5, see if leaks, if not jump forward to .8, test, jump, etc

**Comment by Joeri87** [comment]
Yes, Apply screen color modifications = on, i'm going to try now without. I do use windows night mode in the evening. Ill report later if this worked.

**Comment by Joeri87** [comment]
I guess that did it! Apply screen color modifications = off, and stable 4GB of ram used by windows.... Still scary/unsafe this app can make huge memory problems....

**Comment by zomfg** [comment]
@psieg this call is what is leaking when "screen modif" is checked and _Night Light_ is not used (when used, the library takes over and gamma ramp stuff is skipped, btw don't forget the [new build](https://github.com/zomfg/NightLightLibrary/releases/download/v1.3/NightLightLibrary-x64-1.3-win1909preview.zip))
https://github.com/psieg/Lightpack/blob/244c5834bf834a4b1e3e4332fe17cf2521e215bf/Software/grab/WinUtils.cpp#L420
I don't think it was leaking in older windows versions, but I don't know when it started
so if you plan on a new build maybe gamma ramp needs to be disabled (on current win build only maybe?) for now... your call

I tested [redshift](https://github.com/jonls/redshift) that uses gamma ramps too, it also leaks just at a slower rate because they don't do that call often.
And I don't know if _f.lux_ calls same stuff, but they have (or had) a self-test that's checking memory usage and restarts the app when reached certain amount..

**Comment by psieg** [comment]
Yeah I think it's somewhere in the WindowsAPI.
I'd rather not remove the feature, but simply do the call much less often? Most people will use a transition time of several minutes or more, so reloading the ramp only once a minute or so shouldn't be a problem.

**Comment by x-trend1** [comment]
How can i add this future to my NVFBC version?

**Comment by zomfg** [comment]
by pulling and merging the changes and building it or asking the maintainer to do so

**Comment by tonisk** [comment]
Guess its closed
