### ISSUE TITLE
are 288 LEDs too much?

### ISSUE THREAD

**Issue by vsolenoid** [psieg/Lightpack#309]
Hi,
I have a 43" monitor with 2m(288LEDs) of WS2813 on the sides and the top. It worked perfect with Ambibox, but I wanted to check the additional options in Prismatik. 
I couldn't make it run. I was playing with the serialRate, but then decided to reduce the LEDs to 60 and it worked. Over 200 though it's so laggy that there is no use of it. 
So is there anything you can advice or these are just too much LEDs for your program? 
Thanks
Viktor

**Comment by zomfg** [comment]
is it not working at all with 288?
what baud rate and frame rate?

**Comment by vsolenoid** [comment]
Not working at all. It kinda works with 120 max. 15fps

**Comment by zomfg** [comment]
what baud rate?
use [this](https://www.partsnotincluded.com/calculating-adalight-framerate-limits/) to estimate what you need

**Comment by vsolenoid** [comment]
I've tried 115200 and 500000. In Ambibox I'm on 500000 without issues, but here changing the baud rate is of no use

**Comment by zomfg** [comment]
set your logs to 1, post theme here
what board do you have? did you set the baud rate in both firmware and Prismatik?
try [this build](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_test_skip.zip) with logs on 2, post here
