### ISSUE TITLE
Full-frame wizard preset

### ISSUE THREAD

**Issue by psieg** [psieg/Lightpack#31]
From [reddit](https://www.reddit.com/r/Lightpack/comments/448w8m/prismatik_as_it_should_have_been_windows/d18zp8x), a wizard preset covering all screen borders equally would be helpful for custom setups with non-lightpack devices

**Comment by melgu** [comment]
It would be nice if the wizard supports multiple aspect ratios (independent of the screen itself), so you can easily set up the zones for the use with movies.

**Comment by megageektutorials** [comment]
Yes, would be super helpful. It would also be nice to say you want X amount of LEDs on each side (and leave a blank space for something like a monitor stand) and it would auto adjust the size of grab widgets and put them exactly next to each other.
