### ISSUE TITLE
Prismatik doesn't work with nightlight windows 10

### ISSUE THREAD

**Issue by Kas152** [psieg/Lightpack#315]
@psieg-jenkins 

Recently i tried to get primatik to work with the nightlght from windows 10 (x64). But this does not seem to work, all other variants of bluelightfilters i tried dit work. Any suggestions here? Many thanks in advance!

**Comment by zomfg** [comment]
What is your win10 version?

**Comment by Kas152** [comment]
Hi, thanks for getting back to me so fast!Windows 10 x64 pro. Version 1909.
________________________________

**Comment by zomfg** [comment]
I found why, that'll need a patch and some time.

**Comment by Kas152** [comment]
Ok, great! Thanks!
________________________________

**Comment by psieg** [comment]
@zomfg I was going to make a new release today, should I wait another week so we can include that?

**Comment by zomfg** [comment]
@psieg I want to say ship it so the feedback on new stuff can start to come in
(the issue is with my night light library btw)

**Comment by zomfg** [comment]
@psieg here's a [patched build](https://github.com/zomfg/NightLightLibrary/releases/download/v1.3/NightLightLibrary-x64-1.3-win1909preview.zip)

**Comment by psieg** [comment]
@zomfg I'm having some build issues with the 1909preview build:

**Comment by zomfg** [comment]
Hmm link time... could that be because I used a more recent WinSDK this time?
I don't remember which one was it, but I just tested Prismatik release build against `10.0.18362.0` (VS2019) and the 1909preview build (as is from the zip) and it worked.
Which one do you have?

**Comment by psieg** [comment]
I'm running VS2017. The QT builds are vs2017 too. Could you rebuild with 2017 (or add build files to the repo)?

**Comment by zomfg** [comment]
[how about this?](https://github.com/zomfg/NightLightLibrary/releases/download/v1.3/NightLightLibrary-x64-1.3-win1909preview_msvc2017.zip)

**Comment by psieg** [comment]
Perfect, thanks. I'll prepare a new release later today or tomorrow.
