### ISSUE TITLE
Screen grab skipping leds, other modes works fine

### ISSUE THREAD

**Issue by leocb** [psieg/Lightpack#319]
Hello, thanks for this program, it's really nice.

- My setup uses a custom Arduino Pro Micro (16Mhz) running adalight with baudrate @ 921600
- My monitor is a ultra-wide (21:9) 2560x1080
- I'm using Prismatik version 5.11.2.22
- Total of 226 LEDS distributed as:
   - Top: 82
   - Sides: 36 each
   - Bottom: 36 + 36

When using screen grab mode, some LEDs in the horizontal axis are skipped at regular intervals.
When using other modes, like RGB rainbow or music, all LEDs work fine.
I can also confirm all LEDs light up in setup

Program does not complain about insufficient baud and works at 60fps like a boss
I'll gladly provide any more info if you need.

Skipped LEDs in Screen Grab mode
![Screen grab skiped leds](https://user-images.githubusercontent.com/8310271/79700988-e8fb8580-826f-11ea-9c7f-6435e6dac583.jpg)

'RGB is life' mode
![2020-04-19 18 54 20](https://user-images.githubusercontent.com/8310271/79700990-ebf67600-826f-11ea-9148-77f08d3c81ca.jpg)

Device Setup screen (White balance step)
![2020-04-19 18 52 33](https://user-images.githubusercontent.com/8310271/79700992-ee58d000-826f-11ea-999a-c01d659b98f0.jpg)

**Comment by zomfg** [comment]
try [this build](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_5.11.2.21_black_bar_test_2.zip) (don't worry about the version number)

**Comment by leocb** [comment]
This build does not open on my system (win 10). The Icon shows up in the tray, but clicking it does nothing. LEDs also do nothing. Task manager shows it's responding with 12% CPU utilization, memory is not changing

**Comment by zomfg** [comment]
hmmm how about [this one](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_5.11.2.21_simd_test.zip)

**Comment by leocb** [comment]
This one works correctly, no LEDs skipped. 👍

**Comment by psieg** [comment]
@zomfg Judging just from the filname, this is fixed with the SIMD PR?

**Comment by zomfg** [comment]
#340 does it
