### ISSUE TITLE
Protected Metro Apps

### ISSUE THREAD

**Issue by psieg** [psieg/Lightpack#32]
It seems some Metro Apps (DVD players) use the protected content feature of D3D. Evaluate possibilities to get colors from these anyway, most likely by injection as we do for fullscreen D3D games already.

**Comment by andoriyu** [comment]
I assume this is why netflix app doesn't work with Prismatik?

**Comment by psieg** [comment]
So do I. Haven't tested it though

**Comment by psieg** [comment]
I tried using injection to grab or Desktop-Duplication-unprotect the content, but Netflix makes use of the [Media Foundation Protected Media Pipeline](https://msdn.microsoft.com/en-us/library/windows/desktop/ms694197%28v=vs.85%29.aspx), which runs as a seperate [protected Process](https://msdn.microsoft.com/de-de/library/windows/desktop/ms684880%28v=vs.85%29.aspx#Protected_Processes), which we cannot inject into even with administative privileges.Trying to circumvent DRM is entering the global arms race which I don't have the resources for.
