### ISSUE TITLE
Leds flicker since gpu installed on ubuntu

### ISSUE THREAD

**Issue by GMFalka** [psieg/Lightpack#325]
Hi all!

I had this ambilight project for half a year (fully working), then decided to add a discrete card for my ubuntu HTPC. After that, my leds started to flicker. Its only brightness flickering, not color changeing.

The leds are **not** flickering when i boot into windows (+prismatik with same settings as on ubuntu)
The leds are **not** flickering on ubuntu with the dekstop background picture
The leds **do** flicker if i open chrome, play movies with mpv/vlc or i move the cursor to a window element where prismatik is capturing. When opening a movie, it takes about 5-15sec to start flickering.
Also flickers when ubuntu is turning off the display (the slow screen darkening effect)

- Theres a cap between 5v and ground (1000uF 16v)
- Theres a resistor on the data line (470)
- The prismatik host pc + nodemcu + led PSU is connected together on the ground pin. 
- The led is powered from both end ( easured multiple parts on the led strip: 5.2-4.9v) 
- Baud rate is 256000, but same problem on 115200.

It was working right until i added the 1030 GPU...

Moodlight is not flickering either, thats why i think its a screengrabbing problem, maybe some nvidia settings or...

Any help would be greatly-greatly appreciated!

**Comment by zomfg** [comment]
This looks like #320 , try disabling composer and try to log the flickering

**Comment by GMFalka** [comment]
> This looks like #320 , try disabling composer and try to log the flickering

Yap, the flickering looks exactly like mine. I will get back with log later tonight

**Comment by GMFalka** [comment]
> This looks like #320 , try disabling composer and try to log the flickering

[So heres the log](https://pastebin.pl/view/9a88190d)

Started Prismatik, Enabled COLORED grab widget, waited about 25sec then closed Prismatik.
There were a few flickers during this time, and nothing moving was on the screen.

[Heres a video about the flickering](https://photos.app.goo.gl/SBoveAXiJX5nHrNw8) (not the same instance as the log)

**Comment by zomfg** [comment]
This is what your logged frames look like. Do the irregularities in colored widgets correspond to the flicker you observed?

![image](https://user-images.githubusercontent.com/239811/80260597-90215800-8688-11ea-9607-ba4480defaf2.png)

It does not look like there are errors during the execution, so the frames themselves are probably corrupted in shared memory?... would be interesting to see what those look like

**Comment by GMFalka** [comment]
> This is what your logged frames look like. Do the irregularities in colored widgets correspond to the flicker you observed?
> 
> ![image](https://user-images.githubusercontent.com/239811/80260597-90215800-8688-11ea-9607-ba4480defaf2.png)
> 
> It does not look like there are errors during the execution, so the frames themselves are probably corrupted in shared memory?... would be interesting to see what those look like

Thanks for the quick answer!

The red highlights are the "flickerings?"
![image](https://user-images.githubusercontent.com/17993825/80261155-e93dbb80-8689-11ea-83b6-ba4ea82081d3.png)

My last post has a video link, that shows how it looks, sometimes 15-20leds flicker at the same time, sometimes only 1 led.

**Comment by zomfg** [comment]
> The red highlights are the "flickerings?"

you tell me, I think it's what's in the middle: each line is a frame, list of colors with respective led numbers, so the colorful ones in the middle would correspond to when you displayed the colored squares and AFAIK you can't cover them so if they display the wrong color from one line to the other, it might be your flicker

Now you can disable the logs, and try getting flickers with [this build](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_capture.tar):
- run `mkdir -p /tmp/priz` first
- run the binary

It'll save ALL the frames in that folder, so watch out for disk space!!! Maybe reduce capture frame rate and do short sessions. You could also symlink `/tmp/priz` to somewhere with lots of space...
New sessions (quit and restart) will rewrite previous images, so if you saw flicker in a previous session, back up the relevant images before running the next one.

**Comment by GMFalka** [comment]
> > The red highlights are the "flickerings?"
> 
> you tell me, I think it's what's in the middle: each line is a frame, list of colors with respective led numbers, so the colorful ones in the middle would correspond to when you displayed the colored squares and AFAIK you can't cover them so if they display the wrong color from one line to the other, it might be your flicker

I looked it this picture a bit more, and i think all the red higlights are a flicker
The led # numbering mostly corresponds the flicker location and lenght.

![image](https://user-images.githubusercontent.com/17993825/80264870-e5179b00-8695-11ea-8e1e-52973a14bdeb.png)

> 
> Now you can disable the logs, and try getting flickers with [this build](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_capture.tar):
> 
> * run `mkdir -p /tmp/priz` first
> * run the binary
> 
> It'll save ALL the frames in that folder, so watch out for disk space!!! Maybe reduce capture frame rate and do short sessions. You could also symlink `/tmp/priz` to somewhere with lots of space...
> New sessions (quit and restart) will rewrite previous images, so if you saw flicker in a previous session, back up the relevant images before running the next one.

I

Thanks! Tomorrow morning i will report back on that.

**Comment by GMFalka** [comment]
I cant run the binaries. It complains about missing qt 5.14.
`./Prismatik: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.14' not found (required by ./Prismatik)
`
Tried installing the following, but still missing libQt5Core
```
qt-opensource-linux-x64-5.14.0.run
qt-opensource-linux-x64-5.9.1.run
```

**Comment by zomfg** [comment]
[here's 5.12 build](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_capture_5.12.tar)

**Comment by GMFalka** [comment]
> [here's 5.12 build](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_capture_5.12.tar)

Thanks! That worked.

Im uploading a few runs into google Drive, but look what i found in one of the frame

Ubuntu taskbar goes infront of the widget for 1 frame (top)
![image](https://user-images.githubusercontent.com/17993825/80282013-60696300-870f-11ea-8ea1-528ce8d02c82.png)

**Comment by GMFalka** [comment]
Another run, another frame where some of the widgets is just gone (sides top)

![image](https://user-images.githubusercontent.com/17993825/80282080-c35afa00-870f-11ea-9598-d0035b8069f8.png)

**Comment by GMFalka** [comment]
With this information, i looked at the original image you posted.
![image](https://user-images.githubusercontent.com/17993825/80282208-762b5800-8710-11ea-9eac-6ea82199f2d2.png)

If you look at the middle section where the flickers occours, you can see that its not actially flickers, but changed colors to the background color (Check "flicker led color p

**Comment by zomfg** [comment]
try [this](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_capture_5.12_xsync.tar), we never know...
if not, try messing with 'sync to vblank' and/or some other driver/compositor settings :/

**Comment by GMFalka** [comment]
> try [this](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_capture_5.12_xsync.tar), we never know...
> if not, try messing with 'sync to vblank' and/or some other driver/compositor settings :/

Okey, this build doesnt flicker at all! 
Downsides:

- Leds are late by about 1-2sec,
- CPU usage is about 5-6 times bigger (25-35%, intel i3)
- Prismatik program window event lags, like registering icon clicking, settings changeing (even with leds off)

Is this any help fixing this? :) 
Thanks for the awesome help btw!

**Comment by GMFalka** [comment]
So i dived into the nvidia driver settings and started going ham with the switches.

What is OpenGL flipping? I turned that off and the flickering is gone, I think. 😃

**Comment by zomfg** [comment]
LED lag and high cpu usage were always there with the test builds or just the last one?
On my VM I don't have the issue, and cpu usage seems to be unchanged 
Here's a [build without frame recording](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_nocapture_5.12_xsync.tar) just to see...

Yes `allow flipping` and `sync to vblank` come up often when looking into vsync/compositor issues, also be aware that compositor has it's own settings (somewhere) in addition to driver panel. Looks like this would be a better solution.
And yes it would be interesting to try your findings with #320, although I think a different compositor might be involved there, but still

**Comment by GMFalka** [comment]
> LED lag and high cpu usage were always there with the test builds or just the last one?

Just with the xsync build.

> On my VM I don't have the issue, and cpu usage seems to be unchanged
> Here's a [build without frame recording](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_nocapture_5.12_xsync.tar) just to see...

the first xsync build wasnt saving frames either :P 

> 
> Yes `allow flipping` and `sync to vblank` come up often when looking into vsync/compositor issues, also be aware that compositor has it's own settings (somewhere) in addition to driver panel. Looks like this would be a better solution.

To be honest, now that i **disabled** _sync to vblank_ and _allow flipping_ everything is back to normal, 4k 60hz, no vsync issue.

I can test further if you want, but im happy with the current fix.
I certainly owe you a beer for your time, if you have paypal or something.

**Comment by zomfg** [comment]
> the first xsync build wasnt saving frames either :P

did you delete `/tmp/priz` by any chance? it won't save images if the folder does not exist... but yeah maybe I messed up as I was testing stuff too..
 
> To be honest, now that i **disabled** `sync to vblank` and `allow flipping` everything is back to normal, 4k 60hz, no vsync issue.
> I can test further if you want, but im happy with the current fix.
> I certainly owe you a beer for your time, if you have paypal or something.

well I'm happy with this too, as long as others can successfully apply what you found!
and don't worry I got myself a belgian assortment earlier today ;)

**Comment by GMFalka** [comment]
> > the first xsync build wasnt saving frames either :P
> 
> did you delete `/tmp/priz` by any chance? it won't save images if the folder does not exist... but yeah maybe I messed up as I was testing stuff too..

The folder was there, i was monitoring it.

> 
> > To be honest, now that i **disabled** `sync to vblank` and `allow flipping` everything is back to normal, 4k 60hz, no vsync issue.
> > I can test further if you want, but im happy with the current fix.
> > I certainly owe you a beer for your time, if you have paypal or something.
> 
> well I'm happy with this too, as long as others can successfully apply what you found!
> and don't worry I got myself a belgian assortment earlier today ;)

Thanks! If you need a testing subject for new stuff in the future, you can ping me.
Closing :)

**Comment by zomfg** [comment]
Hi! speaking of testing, mind trying [these 4 builds](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_5.12_apxs.tar)?
in normal use (they won't save frames), with current and old driver settings
looking for unusual stuff compared to the normal release: flicker/lag/cpu...

**Comment by GMFalka** [comment]
> Hi! speaking of testing, mind trying [these 4 builds](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_5.12_apxs.tar)?
> in normal use (they won't save frames), with current and old driver settings
> looking for unusual stuff compared to the normal release: flicker/lag/cpu...

Sure, i will get back to you tomorrow

**Comment by GMFalka** [comment]
> > Hi! speaking of testing, mind trying [these 4 builds](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_5.12_apxs.tar)?
> > in normal use (they won't save frames), with current and old driver settings
> > looking for unusual stuff compared to the normal release: flicker/lag/cpu...
> 
> Sure, i will get back to you tomorrow

### Test environment
- Ubuntu 19
- Intel(R) Core(TM) i3-4350T CPU @ 3.10GHz
- 12gb ram
- Nvidia 1030 DDR5
- NodeMCU / 256000
- 95Leds
- 45fps 25ms sampling
- 4k 60hz TV
- MPV with:
           - Using hardware decoding (cuda).
            - VO: [gpu] 1920x1080 cuda[nv12]

### The 4 test builds had the same outcome between the two nvidia settings

**Sync to vbank / Flipping both OFF**
- 21% cpu usage
- No artifacts

**Sync to vbank / Flipping both ON**
- 21% cpu usage
- Very constant (continous) flickering on top side. Not constant, but noticable flickering on bottom and left right sides.

SIdenote: I had some time to test your homeassistant integration, i will write some experience there too

**Comment by GMFalka** [comment]
Also as an another side note. I noticed that on my 96 (30top, 17right, 18left,  31 bottom) strip, the first two led has the same colors. In Prismatik the first widget controls leds #1 - #2 and the second widget controlls led #3 and so on. Thats very strange :)

**Comment by zomfg** [comment]
thanks for the test! at least we got something out of all this
did you try having vblank on / flipping off and vice versa?

I'm not sure I understrand your last point, could you post a picture of your display with colored widgets on?

**Comment by GMFalka** [comment]
> thanks for the test! at least we got something out of all this
> did you try having vblank on / flipping off and vice versa?
> 
> I'm not sure I understrand your last point, could you post a picture of your display with colored widgets on?

Every build was with vsync / flipping OFF then ON

**Comment by zomfg** [comment]
mind trying on/off, off/on so we'd exhaust this thing?..

**Comment by GMFalka** [comment]
> mind trying on/off, off/on so we'd exhaust this thing?..

Sorry if i was unclear, i did every built with ON and OFF, so i did all scenario :)
