### ISSUE TITLE
Strange monitor issue AOC vx2458 with ambilight

### ISSUE THREAD

**Issue by brzozex** [psieg/Lightpack#328]
HI,
I have a strange issue since i put ambilight ( arduino uno + prismatik) on monitor.
When monitor goes to sleep it will wake up at random time (1 - 5 min)and show no signal and goes back to sleep mode. Can't figure out what causing this behavior. I know it's probably not the best place to ask, but maybe one of the members had the same issue. I tried switching off leds from power source, switching off app, switching off arduino from leds. Any other ideas appreciated.

Regards,
Piotr

**Comment by psieg** [comment]
I don't think Prismatik, or LEDs attached to the screen, would change the behavior of the monitor.
Do you mean the system remains on, but puts the monitor to sleep, or you put the system to sleep and so does the monitor?

**Comment by brzozex** [comment]
not related to prismatik and LED's. It was caused by poor signal on long HDMI cable going to tv.
