### ISSUE TITLE
Catalina Install

### ISSUE THREAD

**Issue by channellock** [psieg/Lightpack#344]
Doesn't raise any error messages when installed on Catalina, but doesn't function at all. App icon does not show in Dock when app is launched and I have no access to any functions of the app whatsoever.  Couldn't find any documentation about whether or not Catalina is supposed to be supported yet, but if it is supported why am I having this issue?

thanks

**Comment by zomfg** [comment]
well, it's not _not supported_
did you use it before Catalina?
try [this build](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_5.11.2.22_capture_s0.2.dmg)

**Comment by channellock** [comment]
No I didn't use on any previous OS.  The dmg you linked shows, “Prismatik” is damaged and can’t be opened. You should eject the disk image.

**Comment by zomfg** [comment]
oooh it might be the "unidentified developer" thing...
to confirm you can try [this](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac) with your already installed version
or [this](https://www.imore.com/imore-show-705-look-your-eyes-scroll-your-fingers) with the new .dmg

weirdly enough I can download and launch both without doing anything in particular (but it could be something I did longtime ago)
actually I still need to give access to the screen and maybe the microphone, but that's normal and you get pretty explicit system messages (as opposed to your situation)

**Comment by channellock** [comment]
the one i downloaded from the release page seems to launch, as in it shows up as a running application in activity monitor, i gave it permissions, but it does nothing.  sad   

perhaps someone else that is running catalina can look into it, but as of right now gonna say it just doesnt work

**Comment by zomfg** [comment]
and yet it seems to be working for #262

**Comment by channellock** [comment]
seems to be a similar issue to #36 and #240. maybe something needs to be deleted?  it does appear to be running as CPU takes a heavy load, but with no UI

**Comment by zomfg** [comment]
do you have a new icon near the clock when it runs?
yes you can try deleting `~/.Prismatik`

**Comment by channellock** [comment]
That was it.  ~/.Prismatik to the trash and all is working. THANK YOU
