### ISSUE TITLE
Windows 10 provides native capture APIs that can be considered as alternatives to NVFBC

### ISSUE THREAD

**Issue by sblantipodi** [psieg/Lightpack#348]
Hi all,
it seems that NVFBC is the best bet for nvidia users giving the absolute best experience with Prismatik.

It gives highest framerate using few resouces,
it works pretty everywhere,
it doesn't broke GSYNC.

Unfortunantly we can't use NVFBC due to licesing but now that NVFBC is deprecated NVIDIA is suggesting to use Windows 10 Native Capture APIs.

As you can read from the nvidia site:
https://developer.nvidia.com/capture-sdk

_NVFBC is planned to be deprecated on Windows 10 starting with Windows 10 October 2019 Update for reasons explained in this document.
Windows 10 provides native capture APIs that can be considered as alternatives to NVFBC. Explore this option (Github Sample)._

Will Prismatik ever support Windows 10 provides native capture APIs introduced in Windows 10?

Thanks!

**Comment by zomfg** [comment]
Didn't we talk about this?
https://github.com/psieg/Lightpack/issues/235#issuecomment-579169010

Confirm with [this app](https://www.microsoft.com/en-us/p/simple-screen-recorder/9n5mvvbd0tgw?activetab=pivot:overviewtab) for ex, that it works just as good as NVFBC

**Comment by sblantipodi** [comment]
sorry, closing this issue and continuing there.
