### ISSUE TITLE
5.11.2.23 don't start, language error(?)

### ISSUE THREAD

**Issue by MacKarp** [psieg/Lightpack#354]
Hello, i have updated today Prismatik to version 5.11.2.23 and it's not starting now, im on Linux Mint 19.3 with kernel 5.3.0-53. When i run prismatik from console i get:
`karpiu@karpiu-desktop:~$ prismatik`
`/home/karpiu/main.conf`
`Unportable version`
`Application directory: /home/karpiu/.Prismatik`
`15:12:13:242 Debug: using qt5ct plugin`
`15:12:13:285 Debug: D-Bus system tray: no`
`15:12:13:427 Warning: Fail load translation for locale "pl_PL" pathToLocale ":/translations/pl_PL"`
`15:12:13:622 Debug: pa_context_connect: OK`
`15:12:13:623 Debug: Start main event loop: lightpackApp.exec();`
`15:12:13:653 Warning: void GrabManager::onGrabApplyBlueLightReductionChanged(bool) could`
`not create Blue Light Reduction client`
`Błędna instrukcja (zrzut pamięci)`

Translation for last line would be:
`Incorrect instruction(memory dump)`

**Comment by zomfg** [comment]
post results of
- `lscpu` (or `cat /proc/cpuinfo`)
- [this](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/simdtest_o3.zip)

**Comment by Karpfly2822** [comment]
lscpu:
`karpiu@karpiu-desktop:~$ lscpu`
`Architektura:           x86_64`
`Tryb(y) pracy CPU:      32-bit, 64-bit`
`Kolejność bajtów:       Little Endian`
`CPU:                    4`
`Lista aktywnych CPU:    0-3`
`Wątków na rdzeń:        1`
`Rdzeni na gniazdo:      4`
`Gniazd:                 1`
`Węzłów NUMA:            1`
`ID producenta:          GenuineIntel`
`Rodzina CPU:            6`
`Model:                  42`
`Nazwa modelu:           Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz`
`Wersja:                 7`
`CPU MHz:                4400.020`
`CPU max MHz:            5900,0000`
`CPU min MHz:            1600,0000`
`BogoMIPS:               6600.02`
`Wirtualizacja:          VT-x`
`Cache L1d:              32K`
`Cache L1i:              32K`
`Cache L2:               256K`
`Cache L3:               6144K`
`Procesory węzła NUMA 0: 0-3`
`Flagi:                  fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36` `clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs` `bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl` `vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx` `lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat` `pln pts md_clear flush_l1d`

simdtest:
`SIMD lvl: 1`
`SSE4_1: 1`
`AVX2: 0`
`_mm_setzero_si128`
`_mm_set_epi8`
`_mm_loadu_si128`
`_mm_shuffle_epi8`
`_mm_add_epi32`
`_mm_hadd_epi32`
`_mm_extract_epi32`
`ext128: 67372036`

**Comment by zomfg** [comment]
Do any of [these](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_5.11.2.23_simdtest.zip) work?

@evilstormer, same for you

**Comment by evilstormer** [comment]
> Do any of [these](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik_5.11.2.23_simdtest.zip) work?
> 
> @evilstormer, same for you

In my case these work:
```
Prismatik_c10
Prismatik_c10_o0
Prismatik_c10_o2
Prismatik_g7_o0
Prismatik_g7_o2
Prismatik_g9_o0
Prismatik_g9_o2
```

And these do not work:
```
Prismatik_g7
Prismatik_g7_m86
Prismatik_g7_skipse
Prismatik_g9
```

**Comment by Karpfly2822** [comment]
none of them work for me because:
`/lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found`
`/usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version 'Qt_5.12' not found`

I have installed on my system:
`karpiu@karpiu-desktop:~$ qmake -v`
`QMake version 3.1`
`Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu`
`karpiu@karpiu-desktop:~$ ldd --version`
`ldd (Ubuntu GLIBC 2.30-0ubuntu2) 2.30`

i tried installing manual qt 5.12.8 but it cant install because:
`libc-bin : Required: libc6 (> 2.30) but 2.27-3ubuntu1 is installed` <- i think i correct translated polish words and digging in internet how to upgrade libc6 i read that it can break system, so i give up

**Comment by Karpfly2822** [comment]
Hello, i upgraded my Mint installation to Linux Mint 20, i still can't run 5.11.2.23 but now i can run simdtest.
These work:
`Prismatik_c10`
`Prismatik_c10_o0`
`Prismatik_c10_o2`
`Prismatik_g7_o0`
`Prismatik_g7_o2`
`Prismatik_g9`
`Prismatik_g9_o0`
`Prismatik_g9_o2`

These not:
`Prismatik_g7`
`Prismatik_g7_m86`
`Prismatik_g7_skipse`

**Comment by zomfg** [comment]
you can replace your .23 binary with any of the `_o2` binaries while the next build is getting ready
