### ISSUE TITLE
dual monitor?

### ISSUE THREAD

**Issue by stevebrown4589gmail** [psieg/Lightpack#359]
i was just wondering if it was possible to control the LED's of two monitors with one controller.
i am running windows 10.
if it helps i will be using a nock off Arduino nano.

**Comment by gastonMM** [comment]
alguna solucion para tener dos pantallas? yo tengo mi monitor de PC y la TV

**Comment by psieg** [comment]
The Software and controller don't care what your LEDs are attached to, so with some wiring and configuring work multiple monitors should be no problem.

**Comment by psieg** [comment]
Closing this as everything should work. Feel free to re-open if something is not working for you.
