### ISSUE TITLE
use prismatik with igpu only.

### ISSUE THREAD

**Issue by ntreik** [psieg/Lightpack#364]
Hi, this is not an issue by all means but is it possible to utilise igpu (intel graphics) only for prismatik but have your monitor connected to discrete gpu through display port? I tried the easy way by adding prismatik to run with power saving gpu (intel)  but i had no screen grabbing

**Comment by zomfg** [comment]
IF you can clone the display from discrete to iGPU (I think it was possible at some point, but might be gone now) you could try telling Prismatik to capture the one on iGPU. If this cross-adapter cloning still works you could get one of those dummy HDMI plugs to fake a display later.

**Comment by ntreik** [comment]
well i wanted to use that idle gpu for something useful but it seems like a headache.thank you anyway
