### ISSUE TITLE
Is color picker inaccurate?

### ISSUE THREAD

**Issue by sblantipodi** [psieg/Lightpack#365]
Hi, it seems that color picker is pretty inaccurate in prismatik or probably I don't understand something... :)

I'm using this test image, my LED matrix is configured accordingly in the prismatik conf file.

![test_led_full](https://user-images.githubusercontent.com/4722227/86100230-d778fa00-bab8-11ea-9c32-a5c6062f41be.png)

When I display this image in full screen I would expect to see a blu led and a purple led, a blu led and a purple led, and so on.

But the result on the led strip is a mix of blu and purple color repeated on all my 95 LEDs.

![IMG_20200629_233037](https://user-images.githubusercontent.com/4722227/86100599-5cfcaa00-bab9-11ea-8bde-ec95d9f4294e.jpg)

Why? is this a bug of prismatik?

Thanks

**Comment by zomfg** [comment]
make a virtual device, display the widgets in Mode tab, check Device tab

**Comment by sblantipodi** [comment]
> make a virtual device, display the widgets in Mode tab, check Device tab

probably I'm too ignorant but I haven't understood, what should I do exactly? O_o

**Comment by zomfg** [comment]
from Device tab run the wizard, select virtual device, configure as usual, your leds should not work now, select grab mode and show widgets in Mode tab (or you can hide widgets and try your test image), back in Device tab you'll see colored virtual leds

**Comment by sblantipodi** [comment]
sorry if I'm pretty hard to understand xD
but what this does exactly?

I have defined a led matrix with a X,Y for every led, 
suppose that I defined 
LED 1 with X=100 and Y=100
what I expect is to see the color in position X=100 Y=100 on LED 1.

isnt' this right, why should I change that led matrix?

I prefer to manual edit the config file, how can I manual edit it? if possible?
thanks a lot for the help zomfg

**Comment by zomfg** [comment]
oh yeah, might be simpler like that
change these in `main.conf`
```ini
[General]
ConnectedDevice=Virtual

[Virtual]
NumberOfLeds=95
```
then you can show widgets or your test image and look in device tab, you should see the color of each zone and compare to what you saw on your leds before
![image](https://user-images.githubusercontent.com/239811/86188923-64b36180-bb40-11ea-87de-c178822184d5.png)

**Comment by sblantipodi** [comment]
ok it was my fault in my config. thank you so much for the continued support dear zomfg.
