### ISSUE TITLE
Prismatik segfaults on Ubuntu20.04 with --nogui option

### ISSUE THREAD

**Issue by the-black-eagle** [psieg/Lightpack#368]
As per the title, if I try to run Prismatik from the command line with the --nogui option, it segfaults. 

```15:00:21:781 Debug: void LiquidColorGenerator::stop()
15:00:21:781 Debug: void MoodLampManager::initColors(int) 180
15:00:21:781 Debug: static int SettingsScope::Settings::getMoodLampLamp()
Segmentation fault
```
From the backtrace in gdb, it crashes at `#0` here
```Thread 1 (Thread 0x7ffff359f6c0 (LWP 1553502)):
#0  0x00007ffff76b6375 in QWidget::testAttribute_helper(Qt::WidgetAttribute) const () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00007ffff76bf2e2 in QWidget::winId() const () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x0000555555584436 in LightpackApplication::initGrabManager() (this=0x7fffffffde60) at LightpackApplication.cpp:706
#3  0x000055555558076e in LightpackApplication::initializeAll(QString const&) (this=0x7fffffffde60, appDirPath=...) at LightpackApplication.cpp:167
#4  0x000055555558cf85 in main(int, char**) (argc=2, argv=0x7fffffffe028) at main.cpp:143
```
The nogui option would be ideal as this particular screen has no window manager so I can't minimize Prismatik and if I run it with a GUI it covers the TV picture :(

**Comment by zomfg** [comment]
try [this](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/prismatik_5.11.2.23_nogui_test_amd64.deb)

**Comment by the-black-eagle** [comment]
Same result unfortunately

**Comment by zomfg** [comment]
same backtrace? you 100% sure you ran the new binary?
```sh
$ md5sum ./prismatik
b101709165784abba69fa4595c876fdb  ./prismatik
```

**Comment by the-black-eagle** [comment]
> same backtrace? you 100% sure you ran the new binary?

Apparently not!  Yeah, can confirm that that does work now with the --nogui option.  Thanks for the quick fix!
