### ISSUE TITLE
Switching from Win8 Desktop Duplication to WinAPI as capture source doesn't work

### ISSUE THREAD

**Issue by alexdie** [psieg/Lightpack#37]
When switching capture sources from desktop duplication to WinAPI while Lightpack is running the setting isn't applied and lightpack needs to be restarted in order to apply the setting.

**Comment by psieg** [comment]
Hi,

unfortunately I can't reproduce the problem. Can you give more details (how do you know which grabbing is active?) or provide a log file?

Best

**Comment by alexdie** [comment]
I discovered this behaviour (or thought I did) while gathering information for #10 .

I have issues while using Win8 Desktop Duplication and no issues when using WinAPI capturing. However, switching from Win8 Desktop Duplication to WinAPI while Lightpack is running doesn't alleviate the issues, I need to restart Lightpack. That is why I - maybe wrongly - assumed the capture source wasn't switched properly.  

Where are the log files for Lightpack located?

**Comment by psieg** [comment]
The logs are at C:\Users\You\Prismatik\logs\ I didn't have time to reproduce #38 yet

**Comment by alexdie** [comment]
[Prismatik.1.txt](https://github.com/psieg/Lightpack/files/271333/Prismatik.1.txt)
[Prismatik.0.txt](https://github.com/psieg/Lightpack/files/271332/Prismatik.0.txt)

In the .1. log I started Lightpack in Win8 Desktop Duplication mode and started Dota 2. I then switched to WinAPI capturing. The fps issues are still present. I quit Lightpack and restart it, starting the .0. log. Everything is back to normal performance.

**Comment by psieg** [comment]
According to the logs, the grabber switch is done as expected. This is I believe indeed just a "shadow" of #38, but not a bug in itself, as switching seems to work.
