### ISSUE TITLE
Prismatik crashing on "Screen grabbing" mode - Linux Mint/Ubuntu

### ISSUE THREAD

**Issue by Eltsch** [psieg/Lightpack#374]
On my Linux Mint 20.0 machine Prismatik is crashing when switching to Screen grabbing mode. (window closes) Mood lamp and Sound visualization is working properly after adding my user to the dialout group to get access to /dev/ttyUSB0 via usemod -a -G dialout <username>

When i open Prismatik via terminal and Screen grabbing is set, it crashes with the Error: "illegal instruction (core dumped)" which isn't very helpful.

On my Windows machine everything is working fine.

Using:
- Linux Mint Cinamon 20.0 64bit
- Intel Core i5 2320
- Radeon HD 6670
- Prismatik 5.11.2.23 via .deb
- Arduino Nano + Adalight WS2812 Script

**Comment by zomfg** [comment]
temporary fix in #354

**Comment by Eltsch** [comment]
thx for the fast reply. I'll try it as soon as possible :)
