### ISSUE TITLE
Not closing UDP connection when program closes 

### ISSUE THREAD

**Issue by camcs1** [psieg/Lightpack#376]
### Bug description 
When I close Prismatik the WLED device remains in live mode. 

### Environment Description 
Prismatik Version 5.11.2.23
WLED version 0.10.0 (Configured as UDP DRGB in prismatik)
Windows 10 1909

Also as a bonus it would be nice if there was a toggle in the UI to start/stop sending data, or alternatively the turn lights on/off toggle acting like this.  

Thanks,

Cameron

**Comment by zomfg** [comment]
What did you put in the Timeout field
![image](https://user-images.githubusercontent.com/239811/89133098-6db99900-d519-11ea-8be4-2c2d45a596f7.png)
putting a low value (like 5) should solve your issue (hover your mouse over the field for a more detailed description)

And I'm not sure I understand what would the toggle accomplish? The big on/off button stops the data after sending an OFF frame

**Comment by camcs1** [comment]
That's fixed it!

I thought the lights on/off toggle was working as intended as it turned the lights off, but it stopping sending sending data is ideal

Sorry for the misunderstanding & thanks,

Cameron
