### ISSUE TITLE
Need Help with Sketch to make my Vision work

### ISSUE THREAD

**Issue by DerDude87** [psieg/Lightpack#379]
Bevorstehende Änderungen am Verlauf
Der Übersetzungsverlauf steht bald nur noch zur Verfügung, wenn du angemeldet bist. Er wird dann zentral über Meine Aktivitäten verwaltet. Der bisherige Verlauf wird durch dieses Upgrade gelöscht. Speichere also Übersetzungen, auf die du später noch zugreifen möchtest.
OK
1589/5000
Hello, I urgently need help to implement a project.

The RGBW LEDStripes SK6812 and an Arduino Nano with 181 LEDS are used if I am correct, because the programming with "simple rgbw" sketch with the Adafruit_Neopixel.h Libary starts with 0 and all LEDs only with a number of 180 LEDs shine completely.

In any case, I would like to achieve the following effects.

From LED 0 (outside right the first LED) and from LED 180 (outside left first LED) 3 LEDs should run synchronously to the center of the stripe, the middle one should shine brighter than the outside ones.

After 5 LEDS spacing, the next 3 LEDS come and this is repeated up to the middle of the stripe, all move to the middle at the same time.

All LEDs except for the groups of three should pulsate with less brightness in one color, so they almost go out and become brighter again.

The effect of a warp core should be modeled if it helps to understand what I want.

Unfortunately, when converting existing sketches, I already fail because the lights move synchronously from the ends of the stripe to the center. Not to mention the groups of three and the intervals or the pulsation of the entire five-way intervals between the groups of three.

I would be very grateful for a sketch that I only have to load onto the controller using the Arduino app. I can usually adjust the colors myself and, in principle, the speed of the effects.

In any case, a big thank you.

___### _Translatet with google-translator___________________

Best regards - Manu
____________________________________________________________________________________________________________________________________
Hallo, ich benötige für die Umsetzung eines Projekts dringend Hilfe. 

Zum Einsatz kommen die RGBW LEDStripes SK6812 und ein Arduino Nano mit 181 LEDS wenn ich richtig liege, da die Programmierung mittels "simple rgbw"-Sketch mit der Adafruit_Neopixel.h Libary mit 0 beginnt und alle LEDs erst mit einer Bezifferung von 180 LED´s gänzlich leuchten. 

Jeden Falls möchte ich folgende Effekte erwirken. 

Von der LED 0 (rechts aussen die erste LED) sowei von der LED 180 (links aussen erste LED)  sollen synchron jeweils 3 LEDS zum Mittelpunkt des Stripes laufen, dabei soll die mittlere heller leuchten als die äußeren. 

Nach 5 LEDS Abstand kommen dann die nächsten 3 LEDS und das wiederholt sich bis zur Mitte des Stripes,  alle   wandern gleichzeitigzur Mitte. 

Alle LEDS ausser der Dreiergruppen sollen mit weniger helligkeit in einem Farbton pulsieren also nahezu ausgehen und wieder heller werden. 

Es soll dabei der Effekt eines Warpkernes nachempfunden werden, wenn das dabei hilft, zu verstehen, was ich möchte. 

Ich scheitere beim umbauen bestehender Sketche leider bereits daran, dass die Lichter synchron von den Enden des Stripes zum Mittelpunkt wandern. Ganz zu schweigen von den 3ergruppen und den Abständen oder dem Pulsieren der gesamten 5erabstände zwischen den 3ergruppen. 

Ich wäre sehr sehr dankbar über einen Sketch den ich nur noch mittels Arduino App auf den Controller laden muss. die Farben kann ich in der Regel selbst einstellen und vom prinzip her auch die Geschwindigkeit der Effekte. 

Auf jeden Fall schon Mal ein dickes Dankeschön. 

Beste Grüße - Manu

**Comment by psieg** [comment]
Sorry, I don't think this is the right place for that question - It seems you want to control the LEDs from the Arduino App, but this forum is for issues with the Prismatik software.
