### ISSUE TITLE
Will it work with non indivisually addressable led strip ?

### ISSUE THREAD

**Issue by Namangarg110** [psieg/Lightpack#392]
https://www.amazon.in/gp/product/B07X2R2FG2/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1
like this one

**Comment by zomfg** [comment]
Prismatik does not care about what type of LEDs you use (here you'll be running with 1 looong LED effectively)
and LEDs don't care about Prismatik
but your controller has to be aware of both, and in this case I doubt it can understand Prismatik

**Comment by Namangarg110** [comment]
> Prismatik does not care about what type of LEDs you use (here you'll be running with 1 looong LED effectively)
> and LEDs don't care about Prismatik
> but your controller has to be aware of both, and in this case I doubt it can understand Prismatik

    So basically it won't work

**Comment by psieg** [comment]
A non-individually addressable strip, by definition, shows one color on all LEDs. You could use it with a single capture zone, showing the average color on all LEDs.
