### ISSUE TITLE
Plugin not running on version higher than 5.11.2.21 on Windows

### ISSUE THREAD

**Issue by lgoette** [psieg/Lightpack#396]
Plugins are not executed on Windows in versions higher than 5.11.2.21. It works in higher versions on Linux and in 5.11.2.21 on Windows. I guess its a problem wih the python executable.

**Comment by zomfg** [comment]
what plugins?

**Comment by lgoette** [comment]
I tested it with this one: https://github.com/lgoette/Prismatik-ArtNet
Have a look at the ini file. The plugin works on all Linux versions and on Windows 5.11.2.21 but not higher versions.

**Comment by zomfg** [comment]
is [this](https://github.com/zomfg/Lightpack/releases/download/5.11.2.24/Prismatik_5.2.11.23_win_plugexec.zip) better?
if not, run `Prismatik.exe` (from that build) from a command prompt and look for errors

**Comment by zomfg** [comment]
FYI: you can use these for system specific stuff instead of uncommenting `Execute=...`
```ini
Execute=python whatever.py
ExecuteOnWindows=python.exe myscript.py
ExecuteOnOSX=/some/path/sh myscript.sh
ExecuteOnNix=myscript.sh
```

**Comment by psieg** [comment]
@lgoette I assume that build works for you?
