### ISSUE TITLE
MacOS Big Sur suppport?

### ISSUE THREAD

**Issue by schoenwaldnils** [psieg/Lightpack#399]
I know Big Sur still in beta. But better start early than late.

Prismatic Version 5.11.2.24_485

I can start it. It shows in the menu bar.
I also can use the 'turn off' button.

But when I try to open the settings, the Activity Monitor is ramping up to 100% and says Prismatic is not responding.

**Comment by zomfg** [comment]
on x86_64?

**Comment by schoenwaldnils** [comment]
do you mean this?

macOS Big Sur 11.0 Beta (20A5384c)
Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz

**Comment by zomfg** [comment]
yes, thanks
try [this build](https://github.com/zomfg/Lightpack/releases/download/5.11.2.24/Prismatik_5.11.2.24_bigsur.dmg)

**Comment by schoenwaldnils** [comment]
Yes! Thanks! I can open the Settings and setup the lights 🎉 

But some of the LEDs are flickering pretty much 🤔   
https://i.schoen.world/ambilight5.mp4
And some seem to not what to decide what color they should choose 🤔   
https://i.schoen.world/ambilight6.mp4

On PC the LEDs and the app are working great though :)

**Comment by zomfg** [comment]
how about [this one](https://github.com/zomfg/Lightpack/releases/download/5.11.2.24/Prismatik_5.11.2.24_bigsur_b13dec9_nodither.dmg)

**Comment by zomfg** [comment]
do you have "apply color modification" enabled? try without
if that does not help, set logs to 2, play first 1:30 of that video you got there and post the file here

> Thanks, the flickering is gone!

@psieg / @Womifa that was rolling back to b13dec9cf8e42d137e8569b4ebca0f8eb3d51a15

**Comment by schoenwaldnils** [comment]
Yes, "Apply screen color modification" was enabled.
Without it the problems are gone! 🎉

**Comment by zomfg** [comment]
could you enable it again and test [this build](https://github.com/zomfg/Lightpack/releases/download/5.11.2.24/Prismatik_5.11.2.24_bigsur_b13dec9_gamma.dmg) please

**Comment by schoenwaldnils** [comment]
Used the build, enabled it and had no problems 👍

**Comment by zomfg** [comment]
thanks!

**Comment by franz67fw** [comment]
Hello Zomfg ,
I am French so I apologize in advance for my mistakes ...
I'm currently running the Big Sur OS on my Macbook Air but when I install the latest version of Prismatik it won't launch in the Dock or anywhere else, so I have no way to use my superb ambient LED strip around my TV (I'm connected via HDMI so it should work ...)
Could you help me with this?
I heard that there was some manipulation to be done in Terminal ...?
thank you in advance !

**Comment by ywjung328** [comment]
> Hello Zomfg ,
> 
> I am French so I apologize in advance for my mistakes ...
> 
> I'm currently running the Big Sur OS on my Macbook Air but when I install the latest version of Prismatik it won't launch in the Dock or anywhere else, so I have no way to use my superb ambient LED strip around my TV (I'm connected via HDMI so it should work ...)
> 
> Could you help me with this?
> 
> I heard that there was some manipulation to be done in Terminal ...?
> 
> thank you in advance !

Check the menubar. You can find the icon.

**Comment by zomfg** [comment]
^ that, assuming you launched it and did the configuration part (to start fresh you can delete `~/.Prismatik` folder)

the terminal part is for when the os refuses to launch it https://appletoolbox.com/how-to-open-apps-downloaded-from-anywhere-macos-sierra/ (but prismatik does not use the dock, only tray icon near the clock)

if you are on M1 see #406 for special builds (even if you are not you can try those too, just make sure to pick the universal/fat dmg in that case)

**Comment by franz67fw** [comment]
I lauch it with Ctrl + right click/open but it still doesn’t appear near the clock

Cordialement,
Mr Weinum François

Le 26 févr. 2021 à 20:31, Sergio <notifications@github.com> a écrit :

﻿

^ that, assuming you launched it and did the configuration part (to start fresh you can delete ~/.Prismatik folder)

the terminal part is for when the os refuses to launch it https://appletoolbox.com/how-to-open-apps-downloaded-from-anywhere-macos-sierra/ (but prismatik does not use the dock, only tray icon near the clock)

if you are on M1 see #406<https://github.com/psieg/Lightpack/issues/406> for special builds (even if you are not you can try those too, just make sure to pick the universal/fat dmg in that case)

**Comment by franz67fw** [comment]
Whatever version I try, it tells me to "eject the disk image"
