### ISSUE TITLE
There is a problem that the log file monopolizes the HDD.

### ISSUE THREAD

**Issue by YOTV** [psieg/Lightpack#414]
There is a problem that the log file monopolizes the HDD.
I don't know the cause.
![explorer_LG25j2F2fi](https://user-images.githubusercontent.com/57837208/100509112-3ef2bd00-31b1-11eb-94b2-304c0f033bf1.png)

**Comment by zomfg** [comment]
what is your log level (expert tab) and did you change it?

**Comment by YOTV** [comment]
When I checked it, it seems that I changed the log level without noticing it.
