### ISSUE TITLE
Crash: "illegal hardware instruction" on M1 Mac

### ISSUE THREAD

**Issue by melgu** [psieg/Lightpack#422]
The configuration wizard still works (& lights turn on), but after that the app immediately crashes and cannot be started again.

```
/Applications/Prismatik.app/Contents/MacOS/main.conf
Unportable version
Application directory: /Users/melvin/.Prismatik
[1]    1109 illegal hardware instruction  /Applications/Prismatik.app/Contents/MacOS/Prismatik
```

**Comment by psieg** [comment]
Can you test [this version](https://github.com/psieg/Lightpack/suites/1656150467/artifacts/30773143) please?

**Comment by melgu** [comment]
@psieg Thanks for the quick reply. Sadly, I still get the same error with that version.

**Comment by jaezh** [comment]
Same here

**Comment by zomfg** [comment]
see #406

**Comment by melgu** [comment]
I'll close this, as progress discussed in #406.
