### ISSUE TITLE
mood mode lamp works very short time

### ISSUE THREAD

**Issue by javilink** [psieg/Lightpack#436]
Hi.

      When you activate the mood lamp mode, it lasts for a very short time. Maybe a few minutes ... Is it possible for this to last longer? Sometimes I like to use a fixed brightness.

i use it through adalight mode.

regards

**Comment by zomfg** [comment]
it's probably your firmware that times out
try unchecking "send data only if changed" in expert tab

**Comment by javilink** [comment]
hi thank you for your answer. I have the options like this:

![image](https://user-images.githubusercontent.com/68188125/104904387-65e39900-5981-11eb-838b-8b5d39b1d857.png)


"send data only if changed" doesn´t appear. the closest thing is "send data only if colors changed" and I've got that option unchecked

**Comment by zomfg** [comment]
that's the one
also you seem to be using an old version, any reason for that?

**Comment by javilink** [comment]
you mean the software version? i think, I have installed the last one.

![image](https://user-images.githubusercontent.com/68188125/104906738-65003680-5984-11eb-8948-fceceb12a1c3.png)

firmware appears unknow, this is the usb-serial driver version

![image](https://user-images.githubusercontent.com/68188125/104907144-e8ba2300-5984-11eb-8546-0edfddbc1601.png)

**Comment by zomfg** [comment]
so you have the official one, this repo is an independent spin-off of that
and the releases are [here](https://github.com/psieg/Lightpack/releases), try that instead

**Comment by javilink** [comment]
Okay. When first uninstalling the official one, and installing it, will the configuration made in the wizard be lost?

and another question, with the updater_signature what do I have to do? copy it to the windows folder where the installation is done?

![image](https://user-images.githubusercontent.com/68188125/104911811-b8c24e00-598b-11eb-9be7-abddcb10b3e4.png)

**Comment by zomfg** [comment]
configuration _should_ stay and be compatible (but just make a copy, it's in your home dir)

don't worry about the signature

**Comment by javilink** [comment]
Thanks a lot. I have installed this version that you have told me. And great it has worked. I'm very grateful to you.
