### ISSUE TITLE
Windows Desktop laggy when using WinAPI

### ISSUE THREAD

**Issue by Jannomag** [psieg/Lightpack#441]
Hi,
I noticed that the desktop is quiet laggy, like window movement, window resize and also the cursor, when using Prismatik with WinAPI instead of Win8 Desktop Duplication.
I'm using Prismatik 5.11.2.27, DIY Arduino Uno build with Adalight as setup, also I'm using a 144Hz 27" 1440p monitor.

My system specs:
AMD Ryzen 7 3800X
Nvidia GTX 1070
16GB DDR4-3600

Windows 10 20H2 Build 19042.746
Drivers are all updated.

Using Win8 Desktop Duplication works better on desktop but it's not working on most games for me.

Any fix for this?

**Comment by psieg** [comment]
WinAPI is a terrible old method. It basically takes a screenshot everytime using an API that goes back to Windows XP or more.

Desktop Duplication is the fix... it should work for most games. If it doesn't, but gaming with WinAPI works fine for you, you can switch the capture method when you start/stop gaming - sorry, that's the best we can do :/

Which games does DDupl not work for?

**Comment by Jannomag** [comment]
I just had this issues with Hitman 3 and Kingdom Come Deliverance. Can't remember other games, yet.I tried both games with fullscreen and borderless mode.
