### ISSUE TITLE
Turning lights off/closing Prismatik doesn't turn my led strip off

### ISSUE THREAD

**Issue by matfortu** [psieg/Lightpack#447]
Hi, i noticed that when i turn the leds off from Prismatik or when i shutdown my PC/close Prismatik the lights remain powered on at minimum luminosity level instead of turning off completely. I have my led strip connected to a WLED flashed ESP8266 with Prismatik sending data via DRGB UDP and everything else works just perfectly.

**Comment by zomfg** [comment]
try "scene luminosity threshold" at 0

**Comment by matfortu** [comment]
Yeah, if i turn that voice completely down they turn off, but it just destroys my eyes in the dark

**Comment by zomfg** [comment]
I assume you have DRGB timeout set to 255, as a workaround you could set WLED default to black/off and change the timeout in Prismatik to something like 2-10

**Comment by matfortu** [comment]
i managed to set WLED to start up with all the leds turned off, but i cant find the timeout setting you mentioned in Prismatik, could be the RefreshDelay option in the .ini file? i have that option set to 100 currently

**Comment by zomfg** [comment]
in device wizard or in your `main.conf` file under `[Drgb]`

**Comment by matfortu** [comment]
now it's working perfectly, thanks a lot!
