### ISSUE TITLE
No lights displaying

### ISSUE THREAD

**Issue by Drov3r** [psieg/Lightpack#449]
I have set up an led strip with an Arduino Nano when i plug it in the lights all go red green and blue when i try to hook up to software i use the RGB is life mode and I can see the RX light on the Arduino flashing quickly indicating it it is receiving information. But my leds dont light up at all. So to conclude I have proven the led strips work with the rgb showing in the setup and I believe the  information has been sent to the Arduino. I have tried Adalight and Ardulight. I have also lowered the baud rate incase there was transmission errors. Any Help would be appreciated.

**Comment by zomfg** [comment]
are you setting the same baud rate on both sides?

**Comment by Drov3r** [comment]
I found a reddit post https://www.reddit.com/r/Lightpack/comments/5qhxut/prismatik_adalights_arduino_help/ that had the same problem but they changed to pin 2 they talk about the spi but i dont think its that but hey it works
