### ISSUE TITLE
Api not working properly in 5.11.2.27

### ISSUE THREAD

**Issue by lgoette** [psieg/Lightpack#450]
A plugin of mine is sending the request "getcountleds\n" `self.connection.send(b"getcountleds\n")` but the result I receive is "%2\r\n" instead of usable data. It worked fine in version 5.11.2.25. I can provide more Information if needed :)

**Comment by zomfg** [comment]
fixed in #428

**Comment by lgoette** [comment]
Oh nice. Then lets wait for the realease :D

**Comment by lgoette** [comment]
Is this project deprecated or something like that or what is the reason for such a long time with no release? :)

**Comment by psieg** [comment]
I guess "mature" is a better term. I was waiting for something else to come up so the release wouldn't only include this change, but thanks for the ping, I'll make one
