### ISSUE TITLE
screen grab fps always 0

### ISSUE THREAD

**Issue by btsken** [psieg/Lightpack#457]
my sound visualization is working

but when I switch to screen grab, the led color will keep the original color

and the fps shows 0/33 fps

here is my profile, my os is win10, using 5.11.2.27

[General]
LightpackMode=Ambilight
IsBacklightEnabled=false

[Grab]
Grabber=DDupl
IsAvgColorsEnabled=false
OverBrighten=100
IsSendDataOnlyIfColorsChanges=true
Slowdown=33
LuminosityThreshold=2
IsMinimumLuminosityEnabled=true
IsDX1011GrabberEnabled=false
IsDX9GrabbingEnabled=false
IsApplyGammaRampEnabled=true
IsApplyColorTemperatureEnabled=false
ColorTemperature=8326
Gamma=2.71

**Comment by zomfg** [comment]
the light in your profile appears to be off

> IsBacklightEnabled=false

**Comment by psieg** [comment]
@btsken is this still an issue?

**Comment by btsken** [comment]
It solved, after I change capture to win8 desktop duplication

**Comment by psieg** [comment]
ok, thanks for the update, happy to hear it works for you now :)
