### ISSUE TITLE
Building for Windows not working 

### ISSUE THREAD

**Issue by limdev212** [psieg/Lightpack#458]
I have successfully built my own version for Ubuntu but I cannot get it to build using Windows. 

I am using Visual Studio and have tried a couple of different Platform Toolsets. 

When using Visual Studio 2015 v140 I get a lot of compiler errors as seen below: 
![image](https://user-images.githubusercontent.com/43649082/114881993-657d6180-9dfb-11eb-8200-2e959fd54ce1.png)

When using the latest toolset I am getting linker errors after compilation for unresolved external symbols:
![image](https://user-images.githubusercontent.com/43649082/114882764-32879d80-9dfc-11eb-81bd-097d9ae44461.png)

I am using Qt Version 5.14.2 and have my system variables for %QTDIR% set to 

![image](https://user-images.githubusercontent.com/43649082/114882588-01a76880-9dfc-11eb-8923-f99b25b256a6.png)

Seems like it's having an issue linking to the Qt DLLs but I'm not quite sure. 

Any help would be greatly appreciated. Build is to update some UI elements and would love to be able to integrate possibly with the source Prismatik. 
![image](https://user-images.githubusercontent.com/43649082/114883251-a6c24100-9dfc-11eb-9d73-3ff10ee1fac0.png)

**Comment by zomfg** [comment]
> I am using Qt Version 5.14.2 and have my system variables for %QTDIR% set to

try without %

**Comment by limdev212** [comment]
Thank you for the reply! 

Updated the system variable to remove the % 

![image](https://user-images.githubusercontent.com/43649082/114934219-8a8cc700-9e31-11eb-9104-64b251e7eb89.png)

With build tools 2019 v142 I am still getting the linker errors: 

![image](https://user-images.githubusercontent.com/43649082/114933500-a348ad00-9e30-11eb-89f5-8870bca2817b.png)

Same compiler errors for v140 
![image](https://user-images.githubusercontent.com/43649082/114934764-40581580-9e32-11eb-8bdb-c482e6eb2cbc.png)

**Comment by zomfg** [comment]
did you run `scripts/win32/generate_sln.bat` in VS dev command prompt while in `Software` folder?

**Comment by limdev212** [comment]
So I have created a clean build and just seems I am getting linker errors only for QTimer now. After re-generating the .sln using the .bat file from the Software folder. 
![image](https://user-images.githubusercontent.com/43649082/114944267-2b35b380-9e3f-11eb-8b50-a19248d39053.png)

**Comment by ParasMore** [comment]
@limdev212 Hello can you help me i also want create full new version of this on my on for windows i dont know how to do it can you help me with that?? also let me know if there is any video for this thank you

**Comment by zomfg** [comment]
Then I don't know what's wrong with your setup
After setting up VS/Qt/QTDIR, all I have to do is:
- open VS dev command prompt
- cd to `Software`
- copy `build-vars.prf.default` to `build-vars.prf` and to test with bare minimum, remove everything except
```
win32 {
  DEFINES += NO_OPENSSL
  TARGET_ARCH = x86_64
}
```
- run `.\script\win32\genrate_sln.bat`
- open `Lightpack.sln`, right click `Prismatik` and build or run or whatever

**Comment by limdev212** [comment]
@zomfg Hey, just got some time to test this now and it is building correctly for me, thank you for your help :D
