### ISSUE TITLE
Bad performance after Windows Update KB5001330

### ISSUE THREAD

**Issue by S-fly** [psieg/Lightpack#459]
After installing Win10 update KB5001330, there is a massive performance drop during screen grabbing in games. Since the installation of this update, almost every game is unplayable when Prismatic is running. The frame rates dropping by 10-15% and the frame time doubles arrhythmically, even if the utilization of the CPU and GPU is only 50% each. This causes massive lag and stuttering. Changing the grap interval has no effect.

I am aware that the cause is probably a bug in KB5001330 or a change to the desktop duplication and therefore cannot be solved here. But maybe someone has a solution or a workaround.

**Comment by Robert-K** [comment]
Installing KB5001330 on my machine cause several programs to stop working altogether, including Prismatik.
No error message, nothing. Doesn't even show up in task manager 🙁

**Comment by zomfg** [comment]
seems to be a windows issue https://www.bleepingcomputer.com/news/microsoft/microsoft-pushes-emergency-fix-for-windows-10-kb5001330-gaming-issues/
