### ISSUE TITLE
Two instances of Prismatik at the same time

### ISSUE THREAD

**Issue by Janoo1606** [psieg/Lightpack#461]
Hi,
i have two monitors with different led devices on different COM ports.
Would it be possible to create a Prismatik installation with a slightly different name and different config folder?
This would be the best solution for me and maybe some others.
Unfortunately, I don't know how time-consuming such a change would be.
But maybe it's just a small change of the program name and the folder names.
So you could use both programs at the same time for one monitor each.

Maybe someone has an approach or a solution to this :)

**Comment by psieg** [comment]
Let's keep the discussion in #280
