### ISSUE TITLE
Version 5.11.2.28 Crash after clean install

### ISSUE THREAD

**Issue by adrianis86** [psieg/Lightpack#464]
Version 5.11.2.28 crashes after clean install and fresh configuration
Windows 10, 21H1, OS build 19043.985, Windows Feature Experience Pack 120.2212.2020.0

No issues until version 5.11.2.27 included

**Comment by psieg** [comment]
When exactly does it crash? After a fresh installation the wizard should start, right?

**Comment by adrianis86** [comment]
Hi, psieg
Same issue with the version from the link.
My default mode is Moodlamp.
It starts ok with that mode.
As soon i try to switch to Screen grabbing mode - the app would unload and can't be started again.

**Comment by adrianis86** [comment]
Here are the logs from Event Viewer:
Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program Prismatik.exe because of this error.

Program: Prismatik.exe
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

Additional Data
Error value: 00000000
Disk type: 0

-----------

Faulting application name: Prismatik.exe, version: 5.11.2.28, time stamp: 0x60a6b366
Faulting module name: Prismatik.exe, version: 5.11.2.28, time stamp: 0x60a6b366
Exception code: 0xc000001d
Fault offset: 0x00000000000faf74
Faulting process id: 0x2858
Faulting application start time: 0x01d74dbabed4e60b
Faulting application path: C:\Program Files\Prismatik\Prismatik.exe
Faulting module path: C:\Program Files\Prismatik\Prismatik.exe
Report Id: 6842d585-9055-49d9-b9c9-4e9f8b4352b8
Faulting package full name: 
Faulting package-relative application ID:

**Comment by psieg** [comment]
0xC000001D is STATUS_ILLEGAL_INSTRUCTION.
What system are you running on?

**Comment by psieg** [comment]
Looks like the culprit is somewhere in #462, but the change to `simdupgrade` looks ok. @zomfg in case you notice something

**Comment by adrianis86** [comment]
> 0xC000001D is STATUS_ILLEGAL_INSTRUCTION.
> What system are you running on?

Windows 10, 21H1, OS build 19043.985, Windows Feature Experience Pack 120.2212.2020.0

**Comment by psieg** [comment]
What hardware is it running on I mean

**Comment by adrianis86** [comment]
> What hardware is it running on I mean, which CPU?

Intel 2 Duo E5xxx

**Comment by psieg** [comment]
Please try replacing the Prismatik.exe with [this one](https://github.com/psieg/Lightpack/files/6528553/Prismatik.zip).

It should show a message on startup about which extensions it detected

**Comment by zomfg** [comment]
I wonder if this isn't the same situation, but msvc #356

**Comment by adrianis86** [comment]
> Please try replacing the Prismatik.exe with [this one](https://github.com/psieg/Lightpack/files/6528553/Prismatik.zip).
> 
> It should show a message on startup about which extensions it detected

![prsmtk](https://user-images.githubusercontent.com/6066994/119394717-2fc17780-bcdb-11eb-844d-8b0008d38ff6.png)

**Comment by psieg** [comment]
Hm, so if your hypothesis for #356 was correct, it can't be entirely the same here because it didn't even detect SSE4.1. That would mean some normal code was automatically optimized to SSE or AVX (as the CPU supports neither).

@adrianis86, please try [this version](https://github.com/psieg/Lightpack/files/6541545/Prismatik_no_AVX_flags.zip) which has the optimization flags from #426 for windows removed. If that fails, try [this](https://github.com/psieg/Lightpack/files/6541574/Prismatik_revert_win_changes.zip), which has both lines reverted.

**Comment by zomfg** [comment]
SSE4.1 came with C2D E8xxx

**Comment by adrianis86** [comment]
> Hm, so if your hypothesis for #356 was correct, it can't be entirely the same here because it didn't even detect SSE4.1. That would mean some normal code was automatically optimized to SSE4 or AVX2 (as the CPU supports neither).
> 
> @adrianis86, please try [this version](https://github.com/psieg/Lightpack/files/6541545/Prismatik_no_AVX_flags.zip) which has the optimization flags from #426 for windows removed. If that fails, try [this](https://github.com/psieg/Lightpack/files/6541574/Prismatik_revert_win_changes.zip), which has both lines reverted.

It works with both versions!

![Screenshot 2021-05-25 23 58 56](https://user-images.githubusercontent.com/6066994/119567929-96b35f00-bdb5-11eb-8f7c-6797d5f2ccb1.png)

**Comment by psieg** [comment]
Hm, thanks. I guess we'll just revert the `QMAKE_CFLAGS_AVX2` for Windows then...

**Comment by adrianis86** [comment]
> Hm, thanks. I guess we'll just revert the `QMAKE_CFLAGS_AVX2` for Windows then...

Thank you.

What are the advantages of that flag for the hardware, that supports it?
Maybe it should be enabled for the hardware, that does support it and disabled, if not supported?

**Comment by psieg** [comment]
Since we only have one release for all systems we'll have to keep it off. It may speed up some things a bit on newer CPUs but I don't think we do much else besides the color aggregation in a similarly parallelizable way.

Removed in #474

**Comment by adrianis86** [comment]
> Since we only have one release for all systems we'll have to keep it off. It may speed up some things a bit on newer CPUs but I don't think we do much else besides the color aggregation in a similarly parallelizable way.
> 
> Removed in #474

Thanks.
Is there an ETA for the updated version?

**Comment by psieg** [comment]
I want to try to fix something else before packaging a new release. If there wasn't one in two weeks, ping me ;)

**Comment by adrianis86** [comment]
> I want to try to fix something else before packaging a new release. If there wasn't one in two weeks, ping me ;)
> 
> If you're not using the API, .28 doesn't have much more than .27 though so you're not missing out on a lot

ping :)

**Comment by psieg** [comment]
Released, thanks

https://github.com/psieg/Lightpack/releases/tag/5.11.2.29
