### ISSUE TITLE
'GLIBC_2.29' not found and `Qt_5.12' not found on prismatik v5.11.2.28 Ubuntu 18.04

### ISSUE THREAD

**Issue by alexishida** [psieg/Lightpack#471]
I installed prismatik Version 5.11.2.28 and when I use display this errors:

prismatik: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by prismatik)
prismatik: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by prismatik)

And I uninstall  Version 5.11.2.28 and install Version 5.11.2.27 work very well.

**Comment by zomfg** [comment]
sounds like ubuntu 20 deb on 18

**Comment by psieg** [comment]
@alexishida did you double-check which deb version you are using?
