### ISSUE TITLE
LEDs Stay On after shutdown when Minimum luminosity level is active

### ISSUE THREAD

**Issue by DanielGlezca** [psieg/Lightpack#472]
Hey guys, first I’d like to thank you for maintaining this project alive and open source. I find it useful and adds a super cool aesthetic to my monitor. Everything is fine except when turning off the lights digitally (by turning off using Prismatik or after shutdown) the leds stay on, very dim light but noticeable.

Hardware involved: 
•	ESP32-Running Wled 0.12
•	Led strip 136 leds
•	PC (Windows 10 build 19042)

I did some testing, turns out it only happens when Minimum luminosity level (MLL, from now on) is active (I use level 2 for eye comfort, but it happens at any level). If PC is shut down or the lights are turn off in Prismatik, the light strip stays barely lit (according to the MLL). Setting the MLL to zero or using dead-zone in Eye care settings the lights turn off correctly. 
I would like to turn completely off the lights after shutdown using MLL, maybe I’m missing some configuration settings, or you have any advice. Greetings.

**Comment by psieg** [comment]
Should be fixed in https://github.com/psieg/Lightpack/releases/tag/5.11.2.29

**Comment by comfreak89** [comment]
Oh no, that was actually a feature for me. I use it as permanent background lightning in my living room :)
