### ISSUE TITLE
Flickering LEDs after latest Windows update

### ISSUE THREAD

**Issue by ScruffR** [psieg/Lightpack#480]
Does anybody else see issues with LEDs flickering after the most recent Windows 10 update?

Everything worked fine till just a few days ago but now two Windows 10 machines seem to have troubles feeding the Arduino Nano with a constant data stream.
I have 130+ LEDs and about the last 50 keep displaying random colours with a "refresh rate"  of about 1Hz. When I then move the mouse these LEDs start flickering wildly.

**Comment by DrSaad77** [comment]
I have a similar problem. Flickering on Windows 10. I dont know if it is due to Windows update.
My setup got 96 LEDs, and also tried to add a 2200microF before the strip stip, it did not help.
With AmbiBox and Prismatik, the same issue is present.

**Comment by ScruffR** [comment]
@psieg, any comment on this?

**Comment by psieg** [comment]
Does it flicker with mood light mode?
We've seen windows updates mess with the grabbing part, but not with the basic talk-to-device part. If it's only the last N, it sounds more like a device communication issue like baud rate.

**Comment by ScruffR** [comment]
As far as I remember it happened in all modes. 
However, I'll have to reinstall the setup in order to test since it was quite annoying. 

I'll report back with more details when I'm set.

But it in deed only was the last ~50 LEDs of 130+.

**Comment by Lichtschimmer** [comment]
I have the same issue since the update of Windows. The last 50 or so LEDs flicker randomly. I tried creating fresh profiles and reinstalling already but nothing helps.

**Comment by h7896v7347** [comment]
Same problem here **only in Win8 Desktop Duplication mode**. When mouse move ~3/10 zones flicker to White. 

It was OK yesterday. I did update Windows(10.0.19043), AMD drivers & prismatik yesterday... But there was no flickering after multiple reboots. 

Problem only came up today.

Installing an earlier version of Prismatik does not solve the problem

**Comment by psieg** [comment]
Do you guys have HDR screens? #255 has flickering when moving the mouse, it should be fixed with the lastest version (.31)

**Comment by ScruffR** [comment]
One one machine I have an HDR screen, but on two other machines with the same issue I have "standard" screens.
I'll have to have another try with the latest version.

**Comment by h7896v7347** [comment]
> Do you guys have HDR screens? #255 has flickering when moving the mouse, it should be fixed with the lastest version (.31)

Non HDR screen (SDR,10bit). Last update **fixed** flickering for me. Thanks a lot!

**Comment by ScruffR** [comment]
Solved for me too 👍
