### ISSUE TITLE
Bitdefender detects trojan when installing?!

### ISSUE THREAD

**Issue by KoningWilly** [psieg/Lightpack#494]
Bitdefender detects trojan when installing?!

**Comment by psieg** [comment]
Make sure to download from the releases page on github.

Accroding to [VirusTotal](https://www.virustotal.com/gui/file/42b47e9d83d0ad4473b256caae0e776bc7e5e574498af5b1ff50454e54848a25) BitDefender says it's clean.

Also see #295
