### ISSUE TITLE
Flashing with HDR enabled

### ISSUE THREAD

**Issue by FluffyDiscord** [psieg/Lightpack#507]
Hi, I have GSync compatible 160 hz monitor and wherever I play games and have big fps fall or jump, led flickers quickly. I can see that the Lightpack capture rate goes quickly up and down (from 0 to 60) and when that happens, leds flicker. I can not reproduce this issue using Hyperion Alpha or old Ambibox.

Can 100% reproduce in HDR mode. 

Can I do anything to help debug this issue ?

**Comment by psieg** [comment]
So this only happens when the FPS changes rapidly? How do the LEDs flash? All white? Random colors?
If you use a longer capture interval, does it still happen?

**Comment by FluffyDiscord** [comment]
> So this only happens when the FPS changes rapidly? How do the LEDs flash? All white? Random colors? If you use a longer capture interval, does it still happen?

1. When I play a game and my fps is really stable, it does not flicker at all. But once I drop few fps, it starts to flicker.
2. Looks to me, like it only flashes all white and then back to their respective color.
3. At longer capture time it also happens, but flashing isn't that fast :D

Video bellow, it speaks for itself:
https://seafile.mossshine.club/f/b6a8f9a3e01b4121b97d/

**Comment by zomfg** [comment]
this does look similar to other HDR cases #255 

also, unrelated, hover mouse above your red fps count in prismatik, it'll probably explain how your baud rate is too low

**Comment by FluffyDiscord** [comment]
> this does look similar to other HDR cases #255
> 
> also, unrelated, hover mouse above your red fps count in prismatik, it'll probably explain how your baud rate is too low

My baud rate is set to 500k. My setup fits perfectly within this rate as I have 142 LEDs at 59fps

**Comment by FluffyDiscord** [comment]
![image](https://user-images.githubusercontent.com/10332247/144297952-1ad9c727-1ff4-4ba9-9b90-49f69c39bac3.png)

the red text only happens when I let my pc sleep and use hdr, not always, but from time to time, as it resets my baudrate for some reason and I have to restart my pc, but that would be a Windows issue

The blinking is still present

**Comment by FluffyDiscord** [comment]
fixed in #511
