### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by Roycinger** [psieg/Lightpack#513]
Hi folks,

I recently found this awesome project.
As I have a spare Arduino and a few meters of ws2812b around, I wanted to realize this as a holiday project.
I have dual Monitor setup like this and plan to wire the strips like in the picture below:
![image](https://user-images.githubusercontent.com/7791335/147936770-e267c8d4-746f-4a60-9de8-ddaf3921dbe8.png)

I'm a bit unsure how to set up the strips in the config wizard, especially when it comes to:
- not grabbing the 2 middle parts of the screens where no LEDs are attached (right edge of left monitor, left edge of right monitor)
- driving a single LED strip from 1 Arduino for 2 independant displays.

Any help is greatly appreciated!

**Comment by zomfg** [comment]
> * not grabbing the 2 middle parts of the screens where no LEDs are attached (right edge of left monitor, left edge of right monitor)

worst case you can manually move/resize grab squares however you want
you could try getting close to what you want with device wizard and finish off by hand

> * driving a single LED strip from 1 Arduino for 2 independant displays.

as long as the monitors are connected to the same computer/Prismatik it should just work™

**Comment by Roycinger** [comment]
> > * not grabbing the 2 middle parts of the screens where no LEDs are attached (right edge of left monitor, left edge of right monitor)
> 
> worst case you can manually move/resize grab squares however you want you could try getting close to what you want with device wizard and finish off by hand
> 
> > * driving a single LED strip from 1 Arduino for 2 independant displays.
> 
> as long as the monitors are connected to the same computer/Prismatik it should just work™

Thanks!
Another issue that I see is the following:
Different sections of the (continuous) strip would need to handle different screens, for example:
Screen 1: LED 1-32, LED 116-166
Screen 2: LED 33-115

Could that be a potential issue?

**Comment by zomfg** [comment]
shouldn't matter

**Comment by Roycinger** [comment]
![image](https://user-images.githubusercontent.com/7791335/147983084-7dc674f4-6945-42d6-8fed-813f580a97dc.png)
How could I only add 1-80 on the bottom, right and top edge? Unfortunately, there's only one field for "sides", not for left and right side individually

**Comment by zomfg** [comment]
yeah... you'll need to move them by hand unfortunately... 💀
.. or generate coordinates on your own with external tool (excel, script...)

**Comment by Roycinger** [comment]
I just found that out. 
I edited my profile .ini file by hand, it seems to work now.
A little odd but it works at least ;)

**Comment by Bestsage** [comment]
Hello, I've a question, how do i have to code my arduino uno for an ambilight with ws2811?
