### ISSUE TITLE
Status LED on Arduino with Adalight sketch

### ISSUE THREAD

**Issue by Roycinger** [psieg/Lightpack#515]
Hi there,
is it possible to somehow turn off the Arduino's power and RX LEDs by software or would that have to be done by either turning it off in the Adalight sketch or removing the LED from the Arduino itself?

thanks!

**Comment by zomfg** [comment]
check the schematic, they are most likely hardwired between tx/rx and vcc
so removing or a piece of black tape...

**Comment by Roycinger** [comment]
I managed to disable the RX LED in the pins_arduino.h
For the power LED, that seems to be hardwired, so I'm most likely going to desolder the LED.
Thanks!
