### ISSUE TITLE
Source files corrupted with 5.11.2.9

### ISSUE THREAD

**Issue by Garwinski** [psieg/Lightpack#52]
I tried to install 5.11.2.9, but I get errors in the installation, saying the source file is corrupted for some files. This is for the following files:
libeay32.dll bass.dll basswasapi.dll msvcr120.dll msvcp120.dll
Clicking ignore for all cases, prismatik fails to load, saying basswasapi.dll and bass.dll are missing.

**Comment by Cr4zyy** [comment]
Same issue for me. I tried grabbing bass and basswasapi.dll from the linked http://www.un4seen.com/ in the readme but it still fails to start (0xc000007b)

**Comment by psieg** [comment]
No Idea what went wrong there. I built a new Installer, please try again

**Comment by Cr4zyy** [comment]
New one seems to install and run fine, thanks :^)

**Comment by Garwinski** [comment]
It works again for me, as well as the new "over-brightness" feature. I am going to play around with it for a bit, thanks!
