### ISSUE TITLE
Change serial port from settings UI?

### ISSUE THREAD

**Issue by irfan798** [psieg/Lightpack#522]
Sometimes my usb serial port name changes after reboot and sleep.

Is it possible to change serial port on settings without executing wizard?

Currently i can solve the issue my changing `SerialPort` configuration under `main.conf` and then restarting the Prismatik

---
It seems we have the function to change it, but it is only called from wizard:
https://github.com/psieg/Lightpack/blob/18a659242adc07f092655afd2d1be2437ab01551/Software/src/Settings.cpp#L863-L867

https://github.com/psieg/Lightpack/blob/7124b83d689cb0b5d892050490528e8fac86ce43/Software/src/wizard/GlobalColorCoefPage.cpp#L122-L126

But it seems like all the dynamic settings about port were commented out:

https://github.com/psieg/Lightpack/blob/92e2c5af2c510aa956f7463109038f11d9fb1be1/Software/src/LightpackApplication.cpp#L663-L673

https://github.com/psieg/Lightpack/blob/39cdb72de24638a9a97fe0ebf9c442e3215bc2bd/Software/src/LedDeviceAdalight.cpp#L211

It seems it is only possible to change when creating a `new LedDeviceAdalight()`;

Was there a reason to comment those slots?
How can we activate them again, do they cause spesific bugs?

**Comment by psieg** [comment]
Not sure why there were commented out. I guess most of the work would be in creating the UI to set this outside the wizard.

Why do you need to change your serial port this often?

**Comment by irfan798** [comment]
I have several USB's connected
And somehow they change `/dev/ttyUSB0` to `/dev/ttyUSB1` or vice versa on reboots and waking from sleep.
Also on re-plugging.
I dont know if this is a general case or just somehow an edge case.
Btw i am using _Arduino Nano_ to control the leds.

I just figured it was reading the port information from `main.conf` while reading the source code.
I can manage with it now (chaging the port then restarting prismatik), but it would be great if we can just change it from _Device_ screen, just a text input next to _Run configuration wizard_

![image](https://user-images.githubusercontent.com/6182106/151231107-2a7a7863-fdb5-4dcb-a461-67b50aa94321.png)

I will try to uncomment those lines and add a textbox when i have time.

**Comment by zomfg** [comment]
have you tried `/dev/serial/by-id/...` or `/dev/serial/by-path/...` instead of `/dev/tty..` ? those might be less likely to change
you can also try udev rules for arduino
