### ISSUE TITLE
4k monitor

### ISSUE THREAD

**Issue by LucasLyu** [psieg/Lightpack#526]
Hello everybody.

I have the latest version of prismatik installed on my MacMINI M1 and a 4k display connected. I can't get a correct screen grabbing. It only records a quarter of my screen, as if my screen were smaller.

**Comment by LucasLyu** [comment]
> 大家好。
> 
> 我在我的 MacMINI M1 上安装了最新版本的 prismatik，并连接了 4k 显示器。我无法正确抓取屏幕。它只记录了我屏幕的四分之一，就好像我的屏幕更小一样。

**Comment by LyuLucas1207** [comment]
Hi,

I have a few things I’d like to discuss with you. If you’re open to it, would you mind sharing a preferred way to contact you?

Thanks,  
Lucas Lyu
lyulucas2003@gmail.com
