### ISSUE TITLE
Can't get screen grabbing working

### ISSUE THREAD

**Issue by Petoodle** [psieg/Lightpack#53]
I have just found your Prismatic version and I am very excited to try it! I had the official Prismatic before, and it worked just ok. Now however, I can't get screen grabbing working. Mood lamp kind of works, but screen grabbing gives literally 0.00 FPS. Any ideas of settings I forgot to do? I went through the Configuration Wizard like 10 times.

I am using the adalight code, ambibox still works just fine as well.

**Comment by psieg** [comment]
First wild guess: You're on Windows 7?

What do you mean by adalight code?

**Comment by Petoodle** [comment]
Yes indeed, I am on windows 7. Is that not compatible with your version?

With adalight I mean I have a bought a ws2812b ledstrip which I connected
to my arduino. The program to receive the data on my arduino is called
adalight. It is one of the installation options in prismatic.
Op 15 jun. 2016 16:23 schreef "Patrick Siegler" <notifications@github.com>:

**Comment by psieg** [comment]
Desktop Duplication was added with Windows 8, so that is not going to work. If you stick to WinAPI grabbing, it should work just like the original one.

**Comment by Petoodle** [comment]
Oh, thank you! My mistake :)
Op 15 jun. 2016 16:43 schreef "Patrick Siegler" <notifications@github.com>:

**Comment by Kelvets** [comment]
Hey psieg, is the Desktop Duplication mode significantly better than WinAPI in terms of grabbing and color fidelity? I might consider upgrading to Win10 from Win7 if that's the case, because right now the color reproduction is pretty poor. For instance, the yellow-ish planet in this [video](https://youtu.be/xpcoO7bTV48?t=37) is reproduced as blue in the LEDs ([photo](http://imgur.com/BYDaVKJ))! Is there nothing that can be done to correct this?

Also, what does the "Enable DX hooking" option do?

Thank you!

**Comment by psieg** [comment]
No problem :)

**Comment by psieg** [comment]
@Kelvets DDupl has better performance but is not going to change the colors. DX hooking allows caputring the content of fullscreen games (if you're not on Win10)

**Comment by Petoodle** [comment]
Okay, so if you do update to windows 10 (which I am planning to do in a
while), are there options to capture full screen games?
Op 16 jun. 2016 11:08 schreef "Patrick Siegler" <notifications@github.com>:

**Comment by psieg** [comment]
Yes, you get it "for free" with Desktop Duplication. You can activate DX grabbing on Win10 too, but I haven't found any game where that was necessary yet.
