### ISSUE TITLE
Feature Request : Dynamically switch between profiles

### ISSUE THREAD

**Issue by switch-code** [psieg/Lightpack#537]
I have a couple of profiles for different media: movie (widescreen), fullscreen, 4:3 movies etc.
Would be since if lightpack can detect which type of format is being played and changed which areas to screen capture.
A lot of time there are black bars and other bars that I don't want to be captured.

**Comment by zomfg** [comment]
it's not trivial to detect reliably
you can try this old draft #312

**Comment by pacifikballa** [comment]
One way around it (although not seamless like how u want it) is to assign macro's for each profile.

**Comment by switch-code** [comment]
Fair enough, ideally it would be seamless but right now I'm manually switching profiles and its not the best but it works.
