### ISSUE TITLE
New Release Missing Files

### ISSUE THREAD

**Issue by MaddBomber83** [psieg/Lightpack#54]
Hello; the new release 5.11.2.9 is missing several DLLs when installing on windows.

**Comment by psieg** [comment]
See #52, please download the installer again.
If that doesn't work, please be more specific as to what is missing

**Comment by MaddBomber83** [comment]
#52 was my issue too; although I tried that at first; the new download
works.  Thank you; and I do apologize for not looking through the issues
more thoroughly.  Only looked at open items.

**Comment by psieg** [comment]
No worries
