### ISSUE TITLE
Some issues regarding the Linux flatpak package

### ISSUE THREAD

**Issue by kennethso168** [psieg/Lightpack#541]
Hi, thanks a lot for the project and it is very nice to have a flatpak package (On the other hand, hyperion.ng only has an outdated rpm for Fedora which does not install on Fedora 36)

However, after I installed the flatpak package by running `flatpak install prismatik_5.11.2.31.flatpak`, I encounter the following issues. I can probably guess some of the causes. If the author wishes, I can create a PR, but that will take some time.

## Issue 1: No launcher after installing

Problem: After installing, there is no launcher to launch the program in Gnome

Workaround: Launch in terminal `flatpak run de.psieg.Prismatik`

Possible cause: Possibly wrong path for the desktop file:
https://github.com/psieg/Lightpack/blob/bc1465cb18b329b24082e4786a007b0a8394e044/Software/dist_linux/flatpak/manifest.yml.template#L55

According to the [flatpak docs](https://docs.flatpak.org/en/latest/conventions.html), desktop files should be placed in `/app/share/applications/`

## Issue 2: After setting the configuration once, the configuration does not persist after reboot

Workaround: Launch with config dir set to flatpak-specific persistence directory (e.g. `flatpak run de.psieg.Prismatik --config-dir ~/.var/app/de.psieg.Prismatik/data`)

Possible cause: Although I can see that there is an override to allow the flatpak to access `~/.Prismatik`:
https://github.com/psieg/Lightpack/blob/bc1465cb18b329b24082e4786a007b0a8394e044/Software/dist_linux/flatpak/manifest.yml.template#L12

I believe that the flatpak does not have the permission to create this directory in the first place. I believe that it is better practice to store the config within the flatpak-specific persistence directory

P.S.: Also better if the flatpak is made available on Flathub

**Comment by ypo777** [comment]
@kennethso168  Can you guide me how can I run flatpak version of yours?
