### ISSUE TITLE
Trouble installing on Fedora/Flatpak

### ISSUE THREAD

**Issue by EddoWagt** [psieg/Lightpack#560]
I want to install prismatik through flatpak on my fedora installation, but the .flatpak seems outdated and does not install to the correct location, but when I clone the repo, cd to ~/Software/dist_linux and run
`./build-natively.sh flatpak`

I get the error 

`+ flatpak install --user --assumeyes org.kde.Sdk//5.15 org.kde.Platform//5.15
Looking for matches…
error: No remote refs found for ‘org.kde.Sdk//5.15’`

I tried doing `flatpak install org.kde.Sdk` but that didn't work...
What am I doing wrong?

**Comment by EddoWagt** [comment]
Still doesn't work for me.
I can manually install kde.org.Sdk version 6.4 just fine, but it will still try to install it with
`flatpak install --user --assumeyes org.kde.Sdk//6.4`, but that gives me the same error as before, just with a different vesion number

**Comment by zomfg** [comment]
try adding flathub remote with `--user`, or remove `--user`  here
https://github.com/psieg/Lightpack/blob/459753083f599fe5110fc3d5d472185858b54530/Software/dist_linux/flatpak/build.sh#L18

**Comment by EddoWagt** [comment]
Thanks, that makes it start building, unfortunately I get another error when I try that...

`make[1]: *** [Makefile:2318: stuff/PulseAudioSoundManager.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/run/build/prismatik/Software/src'
make: *** [Makefile:50: sub-src-make_first] Error 2
Error: module prismatik: Child process exited with code 2`

I appreciate the help though, but I honestly have no idea what these errors even mean

**Comment by zomfg** [comment]
set this back to one of available `5.15`s
https://github.com/psieg/Lightpack/blob/459753083f599fe5110fc3d5d472185858b54530/Software/dist_linux/flatpak/build.sh#L2
and comment this out
https://github.com/psieg/Lightpack/blob/459753083f599fe5110fc3d5d472185858b54530/Software/build-vars.prf.default#L34

**Comment by EddoWagt** [comment]
Thank you, that solved it!

Screen grabbing is not working, but that is another issue. Atleast I have a bit of backlight now

**Comment by zomfg** [comment]
> Screen grabbing is not working

probably Wayland...

**Comment by EddoWagt** [comment]
Shittt, is it not possible under wayland?

**Comment by zomfg** [comment]
#90 not yet

**Comment by EddoWagt** [comment]
That's unfortunate, I hope work on it is continued. I'll make due for now, thank you very much for your help!
