### ISSUE TITLE
Backup of the settings

### ISSUE THREAD

**Issue by metwork** [psieg/Lightpack#577]
Hello,

this is not really a bug report, but I haven't found another way to contact the devs. Sorry for any inconvenience!
I would like to know if there's a way to back up the settings for the LED strip. I found the Profiles and was able to copy them, but if it's possible, I don't want to redo the initial wizard to set up my LED strip as my LED strip is hidden, and therefore it's hard to count the number and location of the LEDs.

Thank you very much for your work and this great fork of Lightpack!

Best regards

**Comment by zomfg** [comment]
Wizard will autostart if you don't have `main.conf` (same place as `Profiles`), which also contains your last used profile name, so copy both

**Comment by metwork** [comment]
Thank you very much, worked like a charm!
