### ISSUE TITLE
[Request] CustomDistributor offset and rotation.

### ISSUE THREAD

**Issue by ZereoX** [psieg/Lightpack#59]
As part of https://github.com/psieg/Lightpack/commit/0905019780cb898abb119f66979033c084dbad61, CustomDistributor was added to the wizard which greatly helps non-lightpack users, but it is currently impossible to adjust the rotation of the LEDs (Clockwise or Counterclockwise) as well as add an offset to define the starting LED.

![clockwise anti-clockwise](https://cloud.githubusercontent.com/assets/761853/16361004/0b51dec2-3b4d-11e6-8420-6a9fcaaa4e01.png)

**Comment by zapoc** [comment]
Yes really need this feature

**Comment by psieg** [comment]
Added in b7feedd929631e6fd4d2847ce0a40248c59a2811
