### ISSUE TITLE
Screen capture doesn't properly work with SpaceEngine game specifically

### ISSUE THREAD

**Issue by Kelvets** [psieg/Lightpack#60]
I'm using Windows 7 64-bit and have the 64-bit version of Prismatik. When running SpaceEngine version [0.9.7.4 RC 2](http://en.spaceengine.org/forum/21-3022-1) fullscreen, the LEDs will not continually update with screen grabbing as normal, but will instead freeze in a single frame. The grab frequency counter will still update as normal. If I alt+tab and then go back to the game, the frame will update for the current scene, but be frozen again. The problem goes away when playing in windowed mode, though. I've tried forcing D3D9 hooking and changing grab frequency in Prismatik, and enabling/disabling V-sync in SpaceEngine, but no dice.

I don't expect you to fix Prismatik just for one application, as that would be too much work for a bug that's probably on SpaceEngine's side. But I'm reporting it nonetheless, in case you want to investigate it to find out what exactly goes wrong and whether it could be an issue in other apps as well.

P.S: it just occurred to me, perhaps this is due to SpaceEngine's fullscreen being proper fullscreen and not borderless windowed? Or vice-versa?

**Comment by psieg** [comment]
I don't have a Win7 system anymore ;-) but I believe this is consistent with "exclusive fullscreen" games. This in turn means, DX hooking should kick in.

Try checking the Logs (``C:\Users\You\Prismatik\Logs``)

**Comment by Kelvets** [comment]
The logging wasn't working, so I disabled and enabled the lights again for it to begin logging. Then I opened SpaceEngine, loaded the gameplay, alt+tabbed so it would refresh the lights for the new scene I looked at, and closed the game. Here's the log:

```
20:58:16:902 Debug: void __cdecl SysTrayIconPrivate::onTrayIcon_Activated(enum QSystemTrayIcon::ActivationReason)
20:58:17:822 Debug: void __cdecl SettingsWindow::backlightOff(void)
20:58:17:823 Debug: void __cdecl LightpackApplication::setStatusChanged(enum Backlight::Status) 0
20:58:17:823 Debug: void __cdecl LightpackApplication::startBacklight(void) m_backlightStatus = 0 m_deviceLockStatus = 0
20:58:17:823 Debug: void __cdecl SettingsScope::Settings::setIsBacklightEnabled(bool)
20:58:17:823 Debug: enum Lightpack::Mode __cdecl SettingsScope::Settings::getLightpackMode(void)
20:58:17:823 Debug: void __cdecl GrabManager::start(bool) false
20:58:17:823 Debug: void __cdecl GrabberBase::stopGrabbing(void) WinAPIGrabber
20:58:17:823 Warning: grabScreensCount:  3707
20:58:17:823 Debug: void __cdecl MoodLampManager::start(bool) false
20:58:17:823 Debug: void __cdecl LiquidColorGenerator::stop(void)
20:58:17:823 Debug: void __cdecl SoundManager::start(bool) false
20:58:17:823 Warning: QObject::startTimer: Timers cannot be started from another thread
20:58:17:823 Debug: void __cdecl SettingsWindow::startBacklight(void) m_backlightStatus = 0 m_deviceLockStatus = 0
20:58:17:823 Debug: void __cdecl LedDeviceLightpack::switchOffLeds(void)
20:58:19:218 Debug: void __cdecl SysTrayIconPrivate::onTrayIcon_Activated(enum QSystemTrayIcon::ActivationReason)
20:58:20:004 Debug: void __cdecl SettingsWindow::backlightOn(void)
20:58:20:005 Debug: void __cdecl LightpackApplication::setStatusChanged(enum Backlight::Status) 1
20:58:20:005 Debug: void __cdecl LightpackApplication::startBacklight(void) m_backlightStatus = 1 m_deviceLockStatus = 0
20:58:20:005 Debug: void __cdecl SettingsScope::Settings::setIsBacklightEnabled(bool)
20:58:20:005 Debug: enum Lightpack::Mode __cdecl SettingsScope::Settings::getLightpackMode(void)
20:58:20:005 Debug: void __cdecl GrabManager::start(bool) true
20:58:20:005 Debug: void __cdecl GrabberBase::startGrabbing(void) WinAPIGrabber
20:58:20:005 Debug: void __cdecl MoodLampManager::start(bool) false
20:58:20:005 Debug: void __cdecl LiquidColorGenerator::stop(void)
20:58:20:005 Debug: void __cdecl SoundManager::start(bool) false
20:58:20:005 Debug: void __cdecl SettingsWindow::startBacklight(void) m_backlightStatus = 1 m_deviceLockStatus = 0
```

**Comment by psieg** [comment]
The log only shows you turned the lights on and off, as far as I can see.
It doesn't really matter though, as I found out the game is OpenGL-based, so DX hooking won't work.

If you can't run the game in windowed (borderless) mode, I'm afraid you're out of luck

**Comment by Kelvets** [comment]
I see. Thank you for pursuing this matter, I appreciate it!

**Comment by psieg** [comment]
You're welcome

**Comment by Kelvets** [comment]
Oh sorry, I don't mean to re-open this, just wanted to say that I managed to work around it by using Borderless Gaming application on "fixed size" mode, then setting the in-game option to "windowed" with height and width values equal to my resolution. Lightpack is now working properly with it.
