### ISSUE TITLE
Custom Option in configuration for  5.11.2.31

### ISSUE THREAD

**Issue by kakakahoy** [psieg/Lightpack#600]
Hello, I was following a guide in youtube in setting up my LED lights and I got to the point in which the LEDS are to be configured around the monitor. However, there isnt a 'custom' buttom anymore, just andromeda, cassio, and pegasus. Can I get help please?

Video link: https://www.youtube.com/watch?v=E2IyTD1lADM

**Comment by zomfg** [comment]
you didn't get it from here probably

**Comment by psieg** [comment]
+1, please make sure to download from https://github.com/psieg/Lightpack/releases and try again. If that doesn't help, feel free to re-open
