### ISSUE TITLE
Prismatik doesn't work after update to windows 11

### ISSUE THREAD

**Issue by DavaJun** [psieg/Lightpack#604]
Hello, I found a problem with prismatik when I start master installing all going good, my led work with white light, but when I try to use another one settings it doesn't work. 
![image](https://github.com/psieg/Lightpack/assets/47446020/9d480399-1536-4065-820c-cfe9aad1ea27)
And this icon send me a message thet I should looking for logs files.
[Prismatik.0.log](https://github.com/psieg/Lightpack/files/13257235/Prismatik.0.log)
help me, please.

**Comment by Exioncore** [comment]
19:45:11:314 Warning: void __cdecl LedDeviceArdulight::open(void) Serial device "COM7" open fail, will retry. Error 11 "

Check if your lights are on COM port 7. It's likely that after the update the COM port changed. 
You can check which COM port you need to use by unplugging the device while in "Device Manager" with the entry "Ports (COM & LPT)". Whichever COM port disappears is the one that your lights are actually on.

**Comment by psieg** [comment]
Thanks @Exioncore for taking a look at this. I'll mark it closed - @DavaJun please reopen if that didn't help
