### ISSUE TITLE
White Light, Not changing

### ISSUE THREAD

**Issue by Edit-Mr** [psieg/Lightpack#607]
I have been using this app with Arduino Nano for about a year, and it's working just fine. However, today, after I opened the app, all the lights became white and did not change with the content.

I've tried changing the port rate, reinstalling, and reuploading.

I can change the brightness and edit the gamma in the configuration wizard, however the lights are not changing with the screen.

Also, I can't find my log file. I can only see main.conf, Plugins and Profiles folder.

Can anyone help?

**Comment by psieg** [comment]
Logging is disabled by default, you need to turn it on in settings (set level to > 0). Your problem sounds more like a device side issue though, not sure.

**Comment by Edit-Mr** [comment]
@psieg I bought a new SSD these days so I reinstall the whole operating system. Everything is fine now.
I don't think its a device side issue because I didn't change anything and now it's fine.
