### ISSUE TITLE
Desktop Duplication with NVIDIA Surround

### ISSUE THREAD

**Issue by iblake12** [psieg/Lightpack#61]
The software seems to not capture anything under the new Desktop Duplication when using Nvidia Surround technology, only WinAPI works.

**Comment by psieg** [comment]
I have been successfully using it with Surround for years. Can you please provide more specifics (you system, how do you know it's surround, what have you tried) and log files?

**Comment by psieg** [comment]
@iblake12 ping

**Comment by iblake12** [comment]
Sorry, i'll try and provide some logs for you soon, everything works fine when surround is off but when its turned on the lights simply dont turn on

**Comment by Cr4zyy** [comment]
Just tested surround myself, here's the log, starts on WinAPI (timestamp 16:05), then switched to DD (timestamp 16:06)

> 16:05:21:047 Debug: void __cdecl LightpackApplication::onFocusChanged(class QWidget *,class QWidget *) SettingsWindow
> 16:05:21:047 Debug: void __cdecl SettingsWindow::onFocus(void)
> 16:05:21:047 Debug: void __cdecl LightpackApplication::onFocusChanged(class QWidget *,class QWidget *) SettingsWindow
> 16:05:21:052 Debug: enum Grab::GrabberType __cdecl SettingsScope::Settings::getGrabberType(void)
> 16:05:21:052 Debug: void __cdecl SettingsWindow::onGrabberChanged(void) GrabberType:  3 , isDx1011CaptureEnabled:  true
> 16:05:21:052 Debug: void __cdecl SettingsScope::Settings::setGrabberType(enum Grab::GrabberType) 3
> 16:05:21:052 Debug: enum Grab::GrabberType __cdecl SettingsScope::Settings::getGrabberType(void)
> 16:05:21:130 Debug: void __cdecl GrabManager::onGrabberTypeChanged(const enum Grab::GrabberType) 3
> 16:05:21:131 Debug: bool __cdecl GrabberBase::isGrabbingStarted(void) const DDuplGrabber
> 16:05:21:131 Debug: void __cdecl GrabberBase::stopGrabbing(void) DDuplGrabber
> 16:05:21:131 Warning: grabScreensCount:  247
> 16:05:21:131 Debug: class GrabberBase *__cdecl GrabManager::queryGrabber(enum Grab::GrabberType) grabberType: 3
> 16:05:21:131 Debug: int __cdecl SettingsScope::Settings::getGrabSlowdown(void)
> 16:05:21:131 Debug: void __cdecl GrabberBase::setGrabInterval(int) WinAPIGrabber
> 16:05:21:131 Debug: void __cdecl D3D10Grabber::startGrabbing(void) D3D10Grabber
> 16:05:22:017 Debug: void __cdecl GrabberBase::startGrabbing(void) WinAPIGrabber
> 16:05:22:017 Debug: void __cdecl D3D10Grabber::stopGrabbing(void) D3D10Grabber
> 16:05:24:526 Debug: void __cdecl LightpackApplication::onFocusChanged(class QWidget *,class QWidget *) null
> 16:05:24:526 Debug: void __cdecl SettingsWindow::onBlur(void)
> 16:05:24:526 Debug: void __cdecl LightpackApplication::showLedWidgets(bool) false
> 16:05:24:526 Debug: void __cdecl GrabManager::setVisibleLedWidgets(bool) false
> 16:06:01:958 Debug: void __cdecl LightpackApplication::onFocusChanged(class QWidget *,class QWidget *) SettingsWindow
> 16:06:01:959 Debug: void __cdecl SettingsWindow::onFocus(void)
> 16:06:01:959 Debug: void __cdecl LightpackApplication::onFocusChanged(class QWidget *,class QWidget *) SettingsWindow
> 16:06:02:045 Debug: enum Grab::GrabberType __cdecl SettingsScope::Settings::getGrabberType(void)
> 16:06:02:045 Debug: void __cdecl SettingsWindow::onGrabberChanged(void) GrabberType:  7 , isDx1011CaptureEnabled:  true
> 16:06:02:045 Debug: void __cdecl SettingsScope::Settings::setGrabberType(enum Grab::GrabberType) 7
> 16:06:02:045 Debug: enum Grab::GrabberType __cdecl SettingsScope::Settings::getGrabberType(void)
> 16:06:02:099 Debug: void __cdecl GrabManager::onGrabberTypeChanged(const enum Grab::GrabberType) 7
> 16:06:02:100 Debug: bool __cdecl GrabberBase::isGrabbingStarted(void) const WinAPIGrabber
> 16:06:02:100 Debug: void __cdecl GrabberBase::stopGrabbing(void) WinAPIGrabber
> 16:06:02:100 Warning: grabScreensCount:  447
> 16:06:02:100 Debug: class GrabberBase *__cdecl GrabManager::queryGrabber(enum Grab::GrabberType) grabberType: 7
> 16:06:02:100 Debug: int __cdecl SettingsScope::Settings::getGrabSlowdown(void)
> 16:06:02:100 Debug: void __cdecl GrabberBase::setGrabInterval(int) DDuplGrabber
> 16:06:02:100 Debug: void __cdecl D3D10Grabber::startGrabbing(void) D3D10Grabber
> 16:06:03:019 Debug: void __cdecl GrabberBase::startGrabbing(void) DDuplGrabber
> 16:06:03:019 Debug: void __cdecl D3D10Grabber::stopGrabbing(void) D3D10Grabber
> 16:06:03:053 Debug: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Lost Access to desktop 0x5041f : 0x887a0026 , requesting realloc
> 16:06:03:082 Debug: void __cdecl GrabberBase::grab(void) reallocating
> 16:06:03:674 Debug: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Lost Access to desktop 0x5041f : 0x887a0026 , requesting realloc
> 16:06:03:705 Debug: void __cdecl GrabberBase::grab(void) reallocating
> 16:06:04:301 Debug: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Lost Access to desktop 0x5041f : 0x887a0026 , requesting realloc
> 16:06:04:330 Debug: void __cdecl GrabberBase::grab(void) reallocating
> 16:06:04:925 Debug: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Lost Access to desktop 0x5041f : 0x887a0026 , requesting realloc
> 16:06:04:957 Debug: void __cdecl GrabberBase::grab(void) reallocating
> 16:06:05:552 Debug: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Lost Access to desktop 0x5041f : 0x887a0026 , requesting realloc
> 16:06:05:580 Debug: void __cdecl GrabberBase::grab(void) reallocating
> 16:06:06:176 Debug: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Lost Access to desktop 0x5041f : 0x887a0026 , requesting realloc
> 16:06:06:206 Debug: void __cdecl GrabberBase::grab(void) reallocating
> 16:06:06:832 Debug: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Lost Access to desktop 0x5041f : 0x887a0026 , requesting realloc
> 16:06:06:862 Debug: void __cdecl GrabberBase::grab(void) reallocating
> 16:06:07:455 Debug: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Lost Access to desktop 0x5041f : 0x887a0026 , requesting realloc
> 16:06:07:492 Debug: void __cdecl GrabberBase::grab(void) reallocating
> 16:06:08:085 Debug: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Lost Access to desktop 0x5041f : 0x887a0026 , requesting realloc
> 16:06:08:112 Debug: void __cdecl GrabberBase::grab(void) reallocating
> 16:06:08:706 Debug: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Lost Access to desktop 0x5041f : 0x887a0026 , requesting realloc

here's a debug log from as soon as DDup is enabled http://pastebin.com/ZHmcp0MR

**Comment by psieg** [comment]
@Cr4zyy Reallocating shouldn't happen twice a second. Does it show anything for you or LEDs stay black?

**Comment by Cr4zyy** [comment]
I don't have surround set-up right now, I wasn't getting any colour information but I had the minimum brightness set and that worked to illuminate the LEDs.

**Comment by KDaxion** [comment]
I am also having this issue, I wasn't running surround up until yesterday and once I actually enabled it prismatik sort of just stopped grabbing in windows 8 desktop duplication mode. Using ambibox I can use one of the other grabbing modes, but windows 8 ddm doesn't seem to work there either. If I turn up the scene luminosity threshold I do get the LEDs to light-up, but they are just a dim white.

Log: http://pastebin.com/VmTJgvrY

**Comment by psieg** [comment]
Hi guys,

* Please name your graphics card (it might be a driver issue)
* Do you have another screen besides the (virtual) surround screen?
* Does the simple Desktop Duplication sample from [this comment](https://github.com/psieg/Lightpack/issues/81#issuecomment-253462648) work on your system?

Thanks

**Comment by KDaxion** [comment]
Willdo, I'll see if I can test today, I just yesterday updated to my graphics drivers to latest. Will report back results before the weekend.

**Comment by KDaxion** [comment]
Managed to fix this by updating/switching drivers.

**Comment by psieg** [comment]
Okay, I'll close this as it seems to have been a driver issue

**Comment by Alex-Coullweb** [comment]
Surround appears to be still causing some issues for me. Desktop Duplication works fine when I have surround disabled but throws errors when enabled. ("Lost Access to desktop")

Nvidia 770 4GB (2x SLI) - No other screens apart from virtual 5768x1080 setup. Same things happens for the Desktop Duplication sample further above thus probably not an issue with the software, more driver related as suggests.

Could anyone suggest a driver version to revert to for me to test out?

Troubleshooting steps taken, reverted to late 2016 driver with a DDU wipe. Currently still not working for me.

**Comment by psieg** [comment]
Sorry to hear. Indeed if the sample crashes there is nothing I/we can do other than report to NVIDIA. I had this setup (also a single surround screen) working a few months ago, so there should be a usable driver more recent than 2016 - good luck!

**Comment by Alex-Coullweb** [comment]
Thanks for the quick response. By any chance, do you know which driver version you were running? Also were you running Sli? Many thanks

**Comment by psieg** [comment]
No SLI, this might be the culprit. I can't remember the version, sorry
