### ISSUE TITLE
md5deep deprecated in favor of hashdeep under Ubuntu 16.04

### ISSUE THREAD

**Issue by ZereoX** [psieg/Lightpack#62]
Upon attempting to build a .deb from source, I discovered that md5deep is deprecated under Ubuntu 16.04 as it is replaced with hashdeep. Simply swapping mentions of md5deep in build-deb.sh with hashdeep fixes the issue.

I've attached a screenshot of the latest md5deep (4.4-2) package for 16.04:

![screenshot from 2016-07-03 01-53-04](https://cloud.githubusercontent.com/assets/761853/16543992/16f83ec8-40c1-11e6-8309-506151404fad.png)

[build-deb.txt](https://github.com/psieg/Lightpack/files/344889/build-deb.txt)

**Comment by psieg** [comment]
Thanks, fixed in 89e5e0f62bf180755b143a4e083d1e40d8a37b40
