### ISSUE TITLE
Minimum luminosity level does not respect color calibration

### ISSUE THREAD

**Issue by MaddBomber83** [psieg/Lightpack#63]
The minimum luminosity level bypasses the color calibration done to each zone.  The expected function is to mimic full calibration at reduced brightness.

To reproduce:
- Mode > Screen Grabbing > Appearance of grab widgets > **set to white**
- On arrow, take one color from one zone and **set to 0**
- Mode > Screen Grabbing > Appearance of grab widgets > **set to do not show**
- **Display a full white image** > Note that previously changed zone has a **different** color as compared to the unchanged zones
- **set minimum luminosity level to 1**
- **Display a full black screen** > Note that previously changed zone has the **same** color as compared to the unchanged zones

This bypass is very noticeable on devices that require significant adjustment to display correct color temperature such as mine where 6500k = R/G/B 100/83/64.  Without this adjustment (and at minimum luminosity level) the LEDs produce a very cold (completely blue) color temperature.

To demonstrate desired behaviour:
- Mode > Screen Grabbing > Appearance of grab widgets > **set to white**
- On arrow, take one color from one zone and **set to 0**
- Mode > Screen Grabbing > Appearance of grab widgets > **set to do not show**
- **Display a full white image** > Note that previously changed zone has a different color as compared to the unchanged zones

**Then**
- Device > Overall brightness > **set to 1** > Note that previously changed zone has a **different** color as compared to the unchanged zones, but at a lower brightness/illumination level.

**Comment by psieg** [comment]
Fixed in 9e6bd1bbccf219a6305e77b99436ff6f24c487a2

**Comment by MaddBomber83** [comment]
verified, thank you for the update!
