### ISSUE TITLE
Smoothing setting not persisting after standby

### ISSUE THREAD

**Issue by togetec** [psieg/Lightpack#64]
I'm on Windows 7 64 bit and using the 64 bit version. When I put my computer in standby with prismatik open the smoothing is not at the correct setting after resuming my computer. If I have smoothing set to 0 before standby smoothing is at max after resuming although the slider is still set to 0. 
[Prismatik.0.log.txt](https://github.com/psieg/Lightpack/files/368209/Prismatik.0.log.txt)

**Comment by psieg** [comment]
The setting does not seem to be the issue here. There's a lot of DeviceError going on... How is the Lightpack connected to your computer?

**Comment by togetec** [comment]
They're connected through a USB hub. Plugging directly into the computer gave a slew of connection problems like windows saying the usb device is not recognized. When I get it working primatik crashed immediately upon resuming. I'll attach the log in case it is a bug but if nobody else has these problems fixing the smoothing is something I can live with and you can close the issue.
[Prismatik.0.log.txt](https://github.com/psieg/Lightpack/files/376969/Prismatik.0.log.txt)

**Comment by psieg** [comment]
@togetec have you looked at this again? There shouldn't be any (persistent) device errors either...

**Comment by psieg** [comment]
I believe I have reproduced the issue. do you power off the Lightpack devices during sleep?

**Comment by togetec** [comment]
I have not looked into this any further.
I have the settings to keep lights on after locking, lights off after suspend, and light on after exit.

**Comment by psieg** [comment]
The question was: Is the Lightpack *device* powered off, as in USB power is disconnected, during sleep?

**Comment by togetec** [comment]
They are connected to a laptop. I checked the BIOS and USB power does suspend during sleep.

**Comment by psieg** [comment]
fixed for windows in b3b37ac6a03e83cb0ecda0dce2a397453ae01282

**Comment by togetec** [comment]
You are awesome! Tell me your paypal so I can buy you a beer

**Comment by psieg** [comment]
My paypal is paypal@psieg.de. Thanks, happy to help :)
