### ISSUE TITLE
5.11.2.10 corrupt files

### ISSUE THREAD

**Issue by schoenda** [psieg/Lightpack#67]
Cant install latest version, a few files are corrupt according to the installer. Tried downloading several times. Anybody else? Thanks.

BTW these drivers are awesome!

**Comment by lijamez** [comment]
Yeah, I'm getting corrupt files too.

**Comment by psieg** [comment]
I don't know what's wrong here, the file itself is fine but the version uploaded to github is not -.-
Re-uploaded, please try again
