### ISSUE TITLE
Not working with No Man's Sky anymore after I updated to new GeForce driver

### ISSUE THREAD

**Issue by Kelvets** [psieg/Lightpack#69]
The backlights were working fine with No Man's Sky, but when I updated from driver 269 to the newest (272) they stopped working completely with NMS specifically. The lights don't turn on at all. I've tried restarting the computer and completely clean-reinstalling the driver, to no avail. Any clue why this happened/how to fix it? Thanks.

Additional info: curiously, if I alt+tab the (borderless window) game so that the window stays in the background, the lights will turn on and work with it appropriately. As soon as the game window regains focus, however, lights go out.

**Comment by psieg** [comment]
Well, obvious thing first: does it work if you go back to 269?
Which Windows version? Is DX injection enabled?

**Comment by Kelvets** [comment]
I went back to 268.39 (that's the version I had, not 269, my bad) and even reinstalled your fork, to no avail. I also tried setting the game to fullscreen, didn't work either.

I'm on Windows 7 using WinAPI mode and with DX hooking enabled. I didn't change any options from when it used to work with the game, so setup that's probably not it.

I wonder what the driver reinstall could have changed that fucked things up for this game.

**Comment by psieg** [comment]
Maybe a change in resolution? I'm not sure if DX injection works with different resolutions right now. Try checking the logs whether injection is happening ('injecting clean process' or something)

**Comment by Kelvets** [comment]
Hey, I ended up moving to a new place where my monitor sits too far away from a wall for lightpack to look good. Thus, I have no idea when I'll start using it again. You may close the ticket, thanks for all your help on my multiple tickets!
