### ISSUE TITLE
OS X build

### ISSUE THREAD

**Issue by psieg** [psieg/Lightpack#7]
It seems Travis offers OS X slaves, which would allow releasing OS X builds without me having a OS X slave at hand. Verify and test that

**Comment by psieg** [comment]
http://blog.travis-ci.com/2014-05-13-multi-os-feature-available/
Travis are currently not accepting requests for Mac CI workers, so that's on hold for now

**Comment by melgu** [comment]
Mac Builds seem to be working again:
https://www.traviscistatus.com

I'd love if you could add Mac Builds to your releases.
Anyways, keep up the awesome work!

**Comment by psieg** [comment]
I'll take a look if/when I find time

**Comment by psieg** [comment]
Could an interested mac user please test [this build](https://psieg.de/lightpack/osx_builds/Prismatik_5.11.2.7_24.dmg)

**Comment by melgu** [comment]
It says I need to log-in.

**Comment by psieg** [comment]
sorry, try again

**Comment by melgu** [comment]
Works like a charm. I didn't test all features, but the main ones seem to work without issues.

**Comment by psieg** [comment]
Seems to work as intended. Please post issues if something doesn't work, but beware I can't do any test on OS X...

**Comment by melgu** [comment]
The latest version _5.11.2.9_ doesn't work on El Capitan. (_5.11.2.8_ works though).

I get the following message in the Terminal:

> $ /Applications/Prismatik.app/Contents/MacOS/Prismatik ; exit;
> dyld: Library not loaded: /usr/local/Cellar/qt5/5.6.1/lib/QtGui.framework/Versions/5/QtGui
>   Referenced from: /Applications/Prismatik.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
>   Reason: image not found
> Trace/BPT trap: 5
> logout
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
> Deleting expired sessions...22 completed.

**Comment by psieg** [comment]
Hi

please try this one: https://psieg.de/lightpack/osx_builds/Prismatik_5.11.2.9_49.dmg

**Comment by melgu** [comment]
I still get the same error.

**Comment by psieg** [comment]
That's weird, nothing changed about packaging since 5.11.2.8.
This is a newer build, try that one: https://psieg.de/lightpack/osx_builds/Prismatik_5.11.2.9_50.dmg

**Comment by melgu** [comment]
Sadly no change.

**Comment by melgu** [comment]
I tried the latest version and I got the same error message as before.

> /Applications/Prismatik.app/Contents/MacOS/Prismatik 
dyld: Library not loaded: /usr/local/Cellar/qt5/5.6.1-1/lib/QtGui.framework/Versions/5/QtGui
  Referenced from: /Applications/Prismatik.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
  Reason: image not found
Trace/BPT trap: 5

I looked inside the application at the position that is mentioned in the error log.
`/Applications/Prismatik.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets`
The mentioned QTWidgets file is there, but it's a different one. Even if I replace this one with the old one from version 2.11.2.8 the error still remains the same.

So I tried to look inside the folder `/usr/local/Cellar/qt5/5.6.1-1/lib/QtGui.framework/Versions/5/QtGui` that is mentioned above. The folder `/usr/local/Cellar/` doesn't exist.

As I don't know enough about the building process of the application, I can't tell you more. But i hope, this is helping in some way.

The latest working version is 2.11.2.8
All versions after that one bring up the error message above.

**Comment by dreamer-dead** [comment]
Yep, it seems that QtWidgets is trying to load QtGui dynamic library from non-existing path

Here is output for downloaded Prismatik_5.11.2.9_50.dmg package
```
$ otool -L /Volumes/bin\:Prismatik/Prismatik.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
/Volumes/bin:Prismatik/Prismatik.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets:
	@executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.6.0, current version 5.6.1)
	/usr/local/Cellar/qt5/5.6.1-1/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.6.0, current version 5.6.1)
```

@psieg, is `/usr/local/Cellar/qt5/5.6.1-1` a place where Qt SDK installed on your build machine?
Usually `/usr/local/Cellar/` is a storage for brew-controlled software on Mac.

**Comment by psieg** [comment]
Hi,

thanks for looking into this. As I don't have a mac, the build runs on a Travis CI which uses brew to install Qt. The [travis.yml](https://github.com/psieg/Lightpack/blob/master/.travis.yml) runs `macdeployqt` which I hoped would take care of the packaging. That process worked when I first setup the build and stopped working lateron without any changes to the yml file.

**Comment by dreamer-dead** [comment]
I can try to build the package on my Mac.
If build script uses direct path to the Qt SDK with version, than it can be a reason for this issue.
Obviously, end user may not have a path like `/usr/local/Cellar/qt5/5.6.1-1`.

**Comment by dreamer-dead** [comment]
Oh, I suppose this is a possible source of the issue - https://github.com/Homebrew/homebrew-core/issues/3219

**Comment by psieg** [comment]
I think you found the problem :+1:
I'll look into specifying a different qt version in the travis script tomorrow

**Comment by psieg** [comment]
Guys, please try [this build](https://psieg.de/lightpack/osx_builds/Prismatik_5.11.2.10_70.dmg). It should be using Qt5.5

**Comment by melgu** [comment]
The version number inside the settings app is wrong (it still says 5.11.2.8) but except that it works!

**Comment by melgu** [comment]
This version works!

(Sorry about my last reply. I started the wrong version.)

**Comment by dreamer-dead** [comment]
This looks good, otool shows correct relative paths for Qt dynamic libraries

```
$ otool -L /Volumes/bin\:Prismatik\ 1/Prismatik.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets 
/Volumes/bin:Prismatik 1/Prismatik.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets:
	@executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.5.0, current version 5.5.1)
	@executable_path/../Frameworks/QtGui.framework/Versions/5/QtGui (compatibility version 5.5.0, current version 5.5.1)
	@executable_path/../Frameworks/QtCore.framework/Versions/5/QtCore (compatibility version 5.5.0, current version 5.5.1)
```

**Comment by psieg** [comment]
Great! I updated the latest release with a new build
