### ISSUE TITLE
Application causes AMD display driver crashes in Windows 10

### ISSUE THREAD

**Issue by taylor-madeak** [psieg/Lightpack#73]
Windows 10 resets the AMD display driver in the following conditions:

1 - AMD Radeon Crimson 16.x.x drivers are in use with a Radeon R9 270x.
2 - Prismatik (unofficial fork) is running in Windows 8 desktop duplication API mode (DX hooking is disabled).
3 - A web browser is attempting to play a video using HTML5 video player (e.g. Youtube), especially when trying to view full screen

Affected applications:

Firefox
Chrome
Steam

Replication steps:

1 - Configure Prismatik for normal use with desktop duplication API for windowed applications.
2 - Attempt to play a video full-screen with an HTML5 player.  Youtube is a good test for this, as it defaults to using HTML5 over Flash now.
3 - Windows will reset the video driver multiple times, causing the screen to freeze and/or go black temporarily.  In the worst cases, the system will BSOD and restart.  Event Viewer will contain entries about Windows blocking the web browser application from accessing the display driver.

Other troubleshooting steps taken include driver reversion and OS re-installation.  Please let me know what logs or other information you need to help narrow down the root cause of this issue.  Currently, I have resolved the crashing by closing Prismatik for normal web browser use, and only running it while gaming.

**Comment by psieg** [comment]
* As you tried reinstalling Windows, I guess you don't know of an older driver that works, right?
* Is DirectX hooking enabled?

**Comment by taylor-madeak** [comment]
- Windows 10 deploys Radeon Crimson 16.1.1 during installation.  All Crimson 16.x series drivers are impacted by this, but I have not tested with the 15.x series.
- DX hooking is disabled.

**Comment by psieg** [comment]
Hi,

Can you try [this sample application](https://github.com/psieg/Lightpack/files/444647/DesktopDuplication.zip) and see whether the problem occurs? This should help narrow down the source. The app is [https://code.msdn.microsoft.com/windowsdesktop/Desktop-Duplication-Sample-da4c696a](a microsoft sample) if you want to build it yourself.

**Comment by taylor-madeak** [comment]
I'm not at home, so I've asked my wife to test it for me.  This is the result:

![desktop_duplication_test](https://cloud.githubusercontent.com/assets/12554820/18105201/022e777e-6eab-11e6-9fda-31dfa569e0e8.jpg)

Hall of mirrors.  This is not the same as what I see on my work PC, which is using AMD Catalyst drivers.

I haven't tried WinAPI grabber recently, as the reason I'm using this fork is for the increased performance offered by your use of the Win8 Desktop Duplication API.

**Comment by psieg** [comment]
How is the hall of mirrors different from your work PC? When run fullscreen, that's what the program should do. The question is whether keeping the program running in the background kills your driver when watching HTML5 videos...

**Comment by taylor-madeak** [comment]
I think she just sent me a confusing image.  I tested it myself before leaving for work this morning, and was able to watch several Youtube videos with it running without crashing the driver.  I don't know whether or not this eliminates the desktop duplication API as the root cause, so I have switched the application over to WinAPI for testing.  I'll comment again when I have results from that.

**Comment by taylor-madeak** [comment]
Okay, here are the results of my testing.  The video driver resets unpredictably under the following conditions:

- Prismatik running using WinAPI and using web browsers
- Prismatik running using DirectX hooking and using web browsers
- Prismatik running using Win8 DDAPI and using web browsers

It seems worse when using desktop duplication, but it does occur in all configurations.  The _only_ happens when running web browsers on either of my displays (not just the display with the capture zones configures).  

If I am playing a game (usually Elite: Dangerous or Fallout 4) in full screen or borderless window with Prismatik running, no display driver crashes occur.  I do, however, take a measurable framerate hit when using the DirectX hooking option.

Are there any debug logs that I can provide that would help with root cause analysis?

**Comment by psieg** [comment]
Sure, there are logs in ``C:\Users\You\Prismatik\Logs``, you can check those. Maybe increase the debug level.

But the behavior you describe does not make any sense to me. Does it happen if Prismatik is in Moodlight mode? Are you sure it is linked to Prismatik at all? Try running Prismatik without admin please.

**Comment by taylor-madeak** [comment]
Here are the log files, the most recent being 09/01/2016:

[logs.zip](https://github.com/psieg/Lightpack/files/452749/logs.zip)

I have never run the application in Moodlight mode, so I don't currently know if it crashes then.  I have run both with and without specifying admin rights, and experience display driver resets in both states.

**Comment by psieg** [comment]
Please increase the debug level and try again. The logs look normal so far.
Please try moodlamp and original prismatik.

**Comment by taylor-madeak** [comment]
> Please increase the debug level and try again. The logs look normal so far.

I'd love to, but the option doesn't seem to be documented on the main repo page.  Is there a command line switch?  Or do I need to set debug level during compile?

> Please try moodlamp and original prismatik.

Ran in Moodlamp mode for 24 hours with heavy web browser and casual game (Bejeweled, courtesy of my wife) usage.  No crashes occurred in that time.

**Comment by psieg** [comment]
The experimental tab has a corresponding option below the grabber selection.
I'm still not convinced. You're saying
* Issue occurs with Prismatik in any grab mode, both DDupl and WinAPI (without DX hooking)
* Issue does not occur with Desktop Duplication Sample
correct?
Please try to rule out other apps as source/interference, so close all other apps than the browser. Let's focus on games lateron.

**Comment by taylor-madeak** [comment]
That's correct.  I have already ruled out other apps as the source of the interference: it's most definitely Prismatik.  Please try not to take this personally, because I'm not directly pointing at your changes to the application as the root cause.  I simply reached out to you because your fork is the version I'm using and because Woodenshark has been inactive on his Github for the past 2 years (which you have noted).  I'm focused on solving the problem, and this branch is the only one I can foresee doing anything to actually fix it.

I will get you the requested detailed debug logs.

**Comment by psieg** [comment]
No worries. I just doesn't make sense to me that it happens with both Desktop Duplication and WinAPI, but not with the Desktop Duplication sample.
Can you run the test again with WinAPI? Or even better, does it happen with the last official version?

**Comment by taylor-madeak** [comment]
It's currently set to WinAPI and display driver reset events still occur while it is running (no messages from Windows any more since reimaging my machine, but both screens go black for a few seconds and Windows logs the event).  The only application in use is Firefox, but I have also tested with Chrome.

I've asked my wife (who is using the computer right now, as I'm at work) to help out by increasing the log level (can't believe I missed that).  She'll collect logs after at least 3 driver reset events occur.

This may be relevant, but did not resolve the issue for me:
https://community.amd.com/thread/180166

I haven't used either the official Prismatik fork or the v6.0.0 beta for a long time, as their capture methods didn't work well with full-screen windowed games and they had a much higher impact on my overall game performance than this branch.

**Comment by taylor-madeak** [comment]
Patrick, let's go ahead and close this.  I made the change described in the link included in my last comment, and increasing that timeout period from the default 2 seconds seems to have resolved the issue this time.  Thanks for your help.
