### ISSUE TITLE
[Suggestion] Make third_party dir for non Prismatic sources

### ISSUE THREAD

**Issue by dreamer-dead** [psieg/Lightpack#75]
There is some code that was taken from other repos, like `hidapi` or `qtsingleapplication`.
What do you think about moving it to a separate dir like `Software/third_party`?
Later it will be possible to link third party code as a git-submodule, or share across Prismatic modules.

Here is my commit with that
https://github.com/dreamer-dead/MyLightpack/commit/8d04f1fbca75c51da93545d3a2a5ff6038ec2f28

Note that I moved Prismatic app code from `Software/src` into `Software/prismatic` but this is not necessary right now and can be omitted.

**Comment by psieg** [comment]
Definitely worth considering. I'll get back to you next week

**Comment by dreamer-dead** [comment]
OK then, I will make a PR with that in your fork.

**Comment by psieg** [comment]
Hey, are you still working on this?

**Comment by psieg** [comment]
Closing some old issues, sorry for the spam, if any.
