### ISSUE TITLE
Offset and Custom Rotation options don't apply to saved "Lightpack.ini"

### ISSUE THREAD

**Issue by ZereoX** [psieg/Lightpack#77]
The custom distributor and offset options that were added in b7feedd are not properly saved in the "Lightpack.ini" file created.

The UI is properly updated during the Setup Wizard, but upon clicking finish, the .ini is always the same as the Custom.

I attempted 6 config:

-  Default

-  -9 Offset

- +51 Offset

- Anti-clockwise

- A-C + 9 Offset

- A-C - 51 Offset

All of which created the same config file.

[Lightpack.ini](https://github.com/psieg/Lightpack/files/455963/Default.txt)
[Setup Wizard](https://cloud.githubusercontent.com/assets/761853/18262287/1920345e-73ce-11e6-8ec9-afe36168e792.png)

**Comment by psieg** [comment]
The file does contain custom positions and sizes up until LED_60. What does the screen look like if you make the grab widgets visible in Prismatik after the wizard finishes?
Please also check the device in use and its number of LEDs

**Comment by ZereoX** [comment]
Thanks for taking a look. I was in the process of creating media to attach so I might as well.

![Actual Result](https://cloud.githubusercontent.com/assets/761853/18281574/4463c254-742b-11e6-8314-0acec77fc289.png)
![Expected Result](https://cloud.githubusercontent.com/assets/761853/18281575/447dcadc-742b-11e6-80eb-7f657f64115a.png)

**Comment by psieg** [comment]
fixed in 8e080d13013dc9a63dddb2d1f5426f9e3f8948a4
