### ISSUE TITLE
Mac HiDPI support

### ISSUE THREAD

**Issue by psieg** [psieg/Lightpack#79]
https://www.reddit.com/r/Lightpack/comments/4yeote/grab_zones_not_accurate_5k_imac_extra_monitor/

**Comment by dreamer-dead** [comment]
Patrick, do you know anything about Prismatic v6 ?
It can be downloaded as a beta from lightpack site http://www.lightpack.tv/downloads.php
Is it a proprietary software now?

**Comment by psieg** [comment]
Prismatik 6.0.0 beta is mainly UI changes, AFAIK it does not include any changes in the grab mechanisms. The source is not available.

I can tell you this: The next official release will be from this repo ;)

**Comment by dreamer-dead** [comment]
OK.
I've read about Lightpack2 and it seems like a big step.
It scans the original HDMI signal instead of grabbing the screen buffer.
It will be a pity if they will not open the source code.

**Comment by ShtokyD** [comment]
I had same issue on my MacBook Pro 15" 2017 but fixed it by just changing monitor resolution on my MacBook, turned out that by default it was set to 1680x1050, so Prismatik captured that. But after changing it to full 2880x1800 in the monitor settings everything is working correctly now!

**Comment by psieg** [comment]
Should be fixed
