### ISSUE TITLE
Device configuration - LED offset

### ISSUE THREAD

**Issue by LoadedScissors** [psieg/Lightpack#83]
This is a really big step up from the original Prismatik, so first of all, thank you!

I think I've found a bug in the custom offset when setting up a device. 

I have an adalight, my configuration is 86 LEDs with a 43 LED offset for position 1.  When I put the offset of 43 into the configuration wizard the screen shows what I would expect. However, once saved and activated, showing the current configuration shows the numbering with the offset removed. Furthermore, the lighting effects are in line with a non-offset configuration. I have tried configuring the same setup with no offset and I get an identical result. Leading me to believe that the offset only shows the difference while configuring but does not actually save it.

A fix would be greatly appreciated, renumbering the text file manually is no fun!

**Comment by psieg** [comment]
See #77, it's fixed but I haven't made a new release yet. Probably will soon. Thanks for the detailed report though ;)

**Comment by LoadedScissors** [comment]
Ah, brilliant thank you!
