### ISSUE TITLE
Grab widgets/zones don't resize when screen resolution changes back after duplicating monitor

### ISSUE THREAD

**Issue by soulhunter123** [psieg/Lightpack#84]
Windows 7 64-bit with an Nvidia graphics card.

Quite often I duplicate my monitor to my TV (using Windows button + P). This decreases the resolution of my screen because my TV's resolution is lower than my monitor. Prismatik resizes the grab widgets (Andromeda pattern) when I duplicate the screens, but when I go back to normal "Computer Only" mode, the grab zones don't resize back to the original larger resolution.

Here's how to replicate:

1. Plug in two displays with different resolutions:
- Monitor at 1440p
- TV at 1080p
2. Duplicate display using Windows+P. Your res should now be lower (1080p).
3. Change back to single display (monitor only). Your res should now be 1440p.
4. Show the grab widgets in Prismatik and they will be at the lower resolution.

**Comment by psieg** [comment]
The reason is that the resizing to lower resolution is done by windows automatically. An automatic save/restore would be needed.

**Comment by psieg** [comment]
As a workaround, making the config file read-only (and maybe restarting Prismatik) should get you the old widget positions back. But this is on the list (next time I get around to working on it....)

**Comment by soulhunter123** [comment]
Making the config file (C:\Users\User\Prismatik\Profiles\Lightpack.ini) read-only did seem to work. Thank you.

**Comment by psieg** [comment]
It does, however that is working around the actual problem. Leave the issue open until a real fix is developed.

**Comment by psieg** [comment]
Should be fixed

**Comment by NeilvdM** [comment]
> Should be fixed

@psieg I downloaded software 6.0.0.104 (revision 6dcfd4d), firmware 7.5 yesterday.
I have 2 x 1080p monitors running. Once I wake up my pc, the widgets have moved.
I will try the suggestion of making the profile read only, but just though Ill post coz you mentioned that it should be fixed now.

Thanks

**Comment by psieg** [comment]
The 6.x branch is unmaintained. The commit you linked is from 2016. Please try the latest release from the downloads page.

**Comment by NeilvdM** [comment]
> The 6.x branch is unmaintained. The commit you linked is from 2016. Please try the latest release from the downloads page.

Yes I know it it is a very old post, was the most relative I could find.
from https://lightpack.tv/pages/downloads, that version is the latest available
