### ISSUE TITLE
Add color calibration page(s) to wizard

### ISSUE THREAD

**Issue by dmadison** [psieg/Lightpack#86]
Hello!

I recently calibrated my Adalight setup, and I thought it would be nice if the color coefficients could be integrated into the GUI somewhere - either within the config wizard or in the device panel. Basic RGB sliders would suffice.

**Comment by psieg** [comment]
see https://www.reddit.com/r/Lightpack/comments/448w8m/prismatik_as_it_should_have_been_windows/d00s9yk/

The grab widgets have small arrows that allow setting RGB mutlipliers for each zone. It is well hidden if you don't know where to look.

**Comment by dmadison** [comment]
You're right, that's quite hidden!

Is there a setting in the GUI to adjust all zones at the same time?

**Comment by psieg** [comment]
There isn't at the moment.

Any ideas on where you would expect such an option and how to make this more intuitive?

**Comment by dmadison** [comment]
Assuming a minor change to the current implementation: a small checkbox at the bottom of the screen (where the gap for the monitor stand is) that toggles between adjusting all zones would make the most sense, although it's not very intuitive unless you know the calibration options are in that screen.

If we were to rewrite how this works, this would be the ideal setup:

- A dedicated wizard under the "Device" tab specifically for calibration. Not everyone needs or wants to calibrate, so I don't think including calibration options under the main config wizard would make sense.
- Screen 1: Display full white over the entire screen with an info window in the center (no capture widgets). On the info window: sliders for Blue/Yellow and Green/Magenta adjustment, with a checkbox to enable Red/Cyan (normally disabled). No grab widgets so visual adjustment is easier.
- Screen 2: Still on a full-white screen, the original grab widgets would show up and let the user customize calibration per-LED. Info box just explains how the currently-implemented 'arrows' on the grab widgets work.

I put together some mockups in Photoshop to help explain:
![lightpackcalmockup_screen1](https://cloud.githubusercontent.com/assets/24282108/21334770/dba7dcf6-c627-11e6-9d39-58d1659b1d07.jpg)
![lightpackcalmockup_screen2](https://cloud.githubusercontent.com/assets/24282108/21334774/e13e0c44-c627-11e6-8dce-bacc55782479.jpg)

**Comment by psieg** [comment]
@dmadison why do you consider the red slider advanced?

**Comment by dmadison** [comment]
Because adjusting two channels affects the balance of the third, and red is the typically the channel that is held constant when adjusting white balance. Adjusting all three will unnecessarily lower the overall brightness.
