### ISSUE TITLE
Logitech Gaming Software

### ISSUE THREAD

**Issue by dw87** [psieg/Lightpack#92]
I have been using your Lightpack (as it should have been) fork of the Prismatik software with an [AmbiBox](http://lab-team.com/index.php/en/products/ambibox) for about 2 weeks.
This week, I bought a [Logitech G933](www.logitech.com/g933) wireless Headset, which has it's own RGB lighting and uses the Logitech Gaming Software.  I have installed the software but not yet connected the Headset's USB receiver.  

Since then, my computer now takes over 5 minutes to boot or restart, when the AmbiBox is connected (BIOS time ~180 seconds or more).  If I disconnect the AmbiBox then it boots within it's normal time (BIOS time ~24 seconds).  

I can see nothing in the Windows Event Logs to indicate what is causing this issue, but if I unplug the AmbiBox device, it boots or restarts in a normal length of time.  

Can you help?

**Comment by dw87** [comment]
As a quick update, I decided to upgrade the Firmware of my LightBox from 6.2 to 7.5, and since doing this my machine now starts up and restarts in a sensible time again.  My most recent BIOS time was 9.9 seconds.  I do not know whether something had been corrupted when installing the Logitech Gaming Software, but everything seems to be working fine now.

**Comment by psieg** [comment]
Great to hear. As the problem was during POST, aka before Prismatik was up and running, the only thing that could fix it was firmware indeed
