### ISSUE TITLE
Disable Logging

### ISSUE THREAD

**Issue by lalalandrus** [psieg/Lightpack#93]
Even though logging is set to level zero, the program still creates logs up to 300 kb per session (one day of computing). Running an SSD and probably wont impact write cycles too much, this seems like an awful lot of writes for logs that will never get read. 

There should be a way to disable logging completely so that there is no unnecessary wear on SSD's.

Thanks

**Comment by psieg** [comment]
Hi,

if you are worried about SSD write cycles, there are probably *significantly* more important applications that write way more than 300kb per day.
Anyway, as this is is currently not intended as 300k are negligible (btw what is it? access denied warnings?) it is not currently supported nor on the roadmap.

As a workaround, you should be able to mark the existing log files as readonly, effectively preventing Prismatik from writing logfiles

Best

**Comment by psieg** [comment]
Since 5.11.2.16, Log Level 0 does not create log files any more
