### ISSUE TITLE
Setmode via API is not working

### ISSUE THREAD

**Issue by mihalski** [psieg/Lightpack#94]
I'm using the latest version Unser MacOS Sierra and here's the problem I am having:

```
Connected to localhost.
Escape character is '^]'.
Lightpack API v1.4 - Prismatik API v2.0 (type "help" for more info)
lock
lock:success
getmode
mode:moodlamp
setmode:ambilight
ok
getmode
mode:moodlamp
exit
Goodbye!
Connection closed by foreign host.
```
and the inverse:
```
Connected to localhost.
Escape character is '^]'.
Lightpack API v1.4 - Prismatik API v2.0 (type "help" for more info)
lock
lock:success
getmode
mode:ambilight
setmode:moodlamp
ok
getmode
mode:ambilight
exit
Goodbye!
Connection closed by foreign host.
```
Seems like there might be a bug in the API set mode command handling.

Regards,
Michal

**Comment by psieg** [comment]
Found and fixed, thanks. Will be included in the next release.

**Comment by psieg** [comment]
ref: https://github.com/woodenshark/Lightpack/issues/30

**Comment by mihalski** [comment]
That's awesome! Thanks.
I was getting worried nobody was going to read this :P

Regards,
Michal
