### ISSUE TITLE
Retina icon in menubar

### ISSUE THREAD

**Issue by danielcompton** [psieg/Lightpack#96]
It would be neat if the Lightpack icon was a retina icon. Also, it could be good to give the option of a black icon, which fits with the conventions on macOS. I might take a look at this, as it seems quite self contained.

<img alt="screenshot of safari technology preview 7-03-17 4-45-23 pm" src="https://cloud.githubusercontent.com/assets/811954/23640928/77137b68-0355-11e7-9ea6-e8851d036ba9.png">

It would also be good for it to to dim itself when the focus is on another window:

<img width="240" alt="screenshot of safari technology preview 7-03-17 4-50-35 pm" src="https://cloud.githubusercontent.com/assets/811954/23641068/4299f140-0356-11e7-989a-050647c5fac2.png">

**Comment by psieg** [comment]
So on macos the tray icons dim themselves if the app is not in focus? This means only one icon can be not dimmed?

**Comment by danielcompton** [comment]
This might be a better picture illustrating what happens:

<img width="1213" alt="screenshot of safari technology preview 9-03-17 9-10-08 am" src="https://cloud.githubusercontent.com/assets/811954/23721906/34a761c8-04a8-11e7-8ae0-1f7ca6f67011.png">

On the monitor where there is no window focus, the menubar turns translucent, and the menubar icons are dimmed. I suspect this is because those menu bars are using [Template Images](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/ToolbarIcons.html) which are grayscale PDF's, and the system can apply the appropriate transformations. I'm guessing that QT may not be doing quite the right thing here, or perhaps we need to update to a newer version of QT?
